### ISSUE TITLE
Upgrade MSW to 2.0

### ISSUE THREAD

**Issue by Will-Mann-16** [anymaniax/orval#1005]
## What are the steps to reproduce this issue?

1. Install msw
2. See it is version `^2.0.2`
3. Notice that all mock files generated like `.msw.ts` fail ts compilation due to build issues that `rest` isn't defined.

## What happens?
In MSW 2.0 they have added a breaking change for the mocking system, namely replacing `rest` keyword with `http`.
[https://mswjs.io/docs/migrations/1.x-to-2.x/](https://mswjs.io/docs/migrations/1.x-to-2.x/).
…

## What were you expecting to happen?
I expect that the new MSW 2.0 functionality be implemented, using the new `http` keyword and different responses.
…

## Any logs, error output, etc?
N/A.
…

## Any other comments?
N/A.
…

## What versions are you using?

**Operating System:** MacOS
**Package Version:** 6.19.1
**Browser Version:** N/A

**Comment by melloware** [comment]
I assigned it to you @Will-Mann-16
