### ISSUE TITLE
Zod: schema with a file that contains minItems and maxItems in a two-dimensional array will result in an error

### ISSUE THREAD

**Issue by yusuken1983** [anymaniax/orval#1027]
## What are the steps to reproduce this issue?

1. Prepare a `openapi.yaml` containing the minItems and maxItems limits in a nested two-dimensional array.

```yaml
openapi: 3.0.3
info:
  title: Sample
  version: 1.0.0
paths:
  /api/sample:
    post:
      summary: sample
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResSampleModel"
components:
  schemas:
    ResSampleModel:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            type: array
            minItems: 2
            maxItems: 5
            items:
              type: string
```

2. Output the zod schema from the above yaml file.

## What happens?

Constants in the zod file contain unnecessary commas.
![image](https://github.com/anymaniax/orval/assets/9739219/35cdab7d-3e2b-430b-9f54-cc49216e8a47)

## What were you expecting to happen?

Constants in zod files do not contain unnecessary commas.

## Any other comments?

My guess is that the args.consts in this line is an array, and when the string is concatenated with the array, the array automatically becomes a string containing commas.

https://github.com/anymaniax/orval/blob/v6.20.0/packages/zod/src/index.ts#L293

## What versions are you using?

**Operating System:** Ubuntu 20.04
**Package Version:** 6.20.0
**Browser Version:** -

**Comment by melloware** [comment]
PR's are welcome!

**Comment by sirtimbly** [comment]
Can confirm this bug exists for the given input. Attempting to debug and add a test for it.
