### ISSUE TITLE
Zod: required field

### ISSUE THREAD

**Issue by jamalsoueidan** [anymaniax/orval#1029]
## What are the steps to reproduce this issue?

```yaml
type: object
properties:
  name:
    type: string
required:
  - "name"
```

## What happens?

Doesn't actually create the required zod? is there something im missing?

```js
export const test = zod.object({
  name: zod.string(),
});
```

I was expecting:
```js
export const test = zod.object({
  name: zod.string().required(),
});
```

Right now the required actually just remove the optional in zod, so if I don't add required in openapi, I get

```js
export const test = zod.object({
  name: zod.string().optional(),
});
```

## What were you expecting to happen?

I'm expecting somehow that in my body request that it adds required.
and not in the response, I don't think it's important.

@melloware

**Comment by melloware** [comment]
@sirtimbly @yusuken1983 another Zod issue interested in fixing?

**Comment by yusuken1983** [comment]
@melloware @jamalsoueidan 
`required()` is used to specify that an object is required, so no primitive properties are needed.
Primitive properties are required by default.

Please refer to the official website.
https://zod.dev/?id=required

**Comment by jamalsoueidan** [comment]
@yusuken1983  I don't exactly understand your answer.

But in any validation lib, it requires me to add the required at the end, so it actually validate the property.

**Comment by yusuken1983** [comment]
@jamalsoueidan 
cannot chain `required()` to `string()`.
Please check the example to see how it works.
https://stackblitz.com/edit/typescript-tvtrnz?file=index.ts

**Comment by melloware** [comment]
Marking as invalid and closing per @yusuken1983 's explanation.
