### ISSUE TITLE
Generating a fetch client instead of axios for Next.js

### ISSUE THREAD

**Issue by aayushatfastrope** [anymaniax/orval#104]
Hi, I'd like to use fetch instead of axios for the basic setup since it's lightweight. Is there a way that's possible right now?

**Comment by anymaniax** [comment]
Hello, sure you can use the next version. You can install it with yarn global add orval@next. You just need to set up a global mutator with your preferred HTTP client (check the doc here https://next.orval.dev/reference/configuration#overridemutator). If you use Next.js you can also use react-query (https://react-query.tanstack.com/docs/guides/ssr). It's cool, easy to use and you also have an integration with orval (https://next.orval.dev/guides/react-query).

**Comment by OliverDudgeon** [comment]
I also would like to use the `Fetch API` instead of `Axios`. I don't see this mentioned anywhere in the docs so I'm adding to this issue. Is there any plans to use Fetch? E.g. in `react-query` requests are made via a e.g. `fetch(url)` instead of an e.g. `axios.get(url)`.

**Comment by anymaniax** [comment]
You can already do it you need to use a mutator check [here](https://github.com/anymaniax/orval/blob/master/samples/react-app-with-react-query/src/api/mutator/custom-instance.ts). you can replace Axios by fetch or any other http client

**Comment by melloware** [comment]
This will be supported in 6.32.0 with this ticket: https://github.com/anymaniax/orval/issues/1387
