### ISSUE TITLE
Reserved keyword not properly fixed, causing parse error in generated code

### ISSUE THREAD

**Issue by Pierstoval** [anymaniax/orval#1041]
## What are the steps to reproduce this issue?

1. Check this repo: https://github.com/pierstoval/orvaltest
2. Just check out the `assets/openapi/index.ts` file, in the `apiImportsIdPatch` variable, at the bottom of the file
3. See the `import` variable: it's actually interpreted by Typescript as the internal `import` keyword, twice

## What happens?

The file becomes impossible to import because of a parse error.

Here is the generated code:

```typescript
const apiImportsIdPatch = <TData = AxiosResponse<ImportJsonld>>(
    id: string,
    import: NonReadonly<Import>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/imports/${id}`,
      import,options
    );
  }
```

## What were you expecting to happen?

File to not have a parse error, possibly by changing "import" variable name into something like "_import" or whatever that might fix the issue.

## Any other comments?

I talked about this in https://github.com/anymaniax/orval/pull/314 and it was said it should've been working.
That's why I created a reproducer with Orval's latest version

## What versions are you using?

**Operating System:** Ubuntu 20.04 as WSL2 virtual machine; with Node.js 18.17.1
**Package Version:** Latest as of today: 6.20.0
**Browser Version:** Not applicable

**Comment by melloware** [comment]
Any PR or investigation will be appreciated as it looks like the code should detect `import` as a keyword.

**Comment by Pierstoval** [comment]
I agree, for now I don't have time to dig into Orval's source code, as I have no idea on how it works under the hood, but I may try whenever I have the time for that.

I could also fund a day or two of work, if needed, for anyone in Orval's core team who would be okay to work on this

**Comment by anymaniax** [comment]
@Pierstoval found a fix thanks for the issue

**Comment by Pierstoval** [comment]
That's perfect! Thanks a lot @anymaniax 🎉 Will try this out!

**Comment by Pierstoval** [comment]
Tested as of latest release, works perfectly 👏

**Comment by melloware** [comment]
Excellent thanks for reporting back!
