### ISSUE TITLE
Nullable enums generate 

### ISSUE THREAD

**Issue by paulst-cais** [anymaniax/orval#1049]
## What are the steps to reproduce this issue?

The following YAML:

```
type: string
nullable: true 
enum:
  - asc
  - desc
  - null
```

## What happens?

We get two keys for null, one with a string, the other with the _expected_ null value

```
export const SortDirection = {
  asc: 'asc',
  desc: 'desc',
  null: 'null',
  null: null,
} as const;
```

## What were you expecting to happen?

We should get a single key for null, the value in the enum should be ignored, generating something like:

```
export const SortDirection = {
  asc: 'asc',
  desc: 'desc',
  null: null,
} as const;
```

**Note:** we actually need to specify this or automatic validation on the BE fails with 40x errors, as null is not a part of the expected set.

My understanding is from here: https://swagger.io/docs/specification/data-models/enums/

Is that OAS3 specifies that:

> Note that null must be explicitly included in the list of enum values. Using nullable: true alone [is not enough](https://github.com/OAI/OpenAPI-Specification/blob/main/proposals/2019-10-31-Clarify-Nullable.md#if-a-schema-specifies-nullable-true-and-enum-1-2-3-does-that-schema-allow-null-values-see-1900) here.

## Any other comments?

Happy to look at creating a PR here if we agree that my understanding of the spec is correct?

## What versions are you using?

**Operating System:** OSX 14 Sonoma
**Package Version:** 6.17.0
**Browser Version:** …

**Comment by melloware** [comment]
Have you tried 6.20.0 ?  There were recent fixes around Nullable?

**Comment by paulst-cais** [comment]
You're absolutely correct, just upgraded the library and those fixes seem to have solved this.

Apologies, I should have checked with the latest version.
