### ISSUE TITLE
Cannot generate types for referenced response component with empty content

### ISSUE THREAD

**Issue by jackoob** [anymaniax/orval#1054]
## What are the steps to reproduce this issue?

With orval v6.20.0

test.yaml

```
openapi: 3.0.3

info:
  title: test
  description: |
    test
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        418:
          $ref: '#/components/responses/418'

components:
  responses:
    418:
      description: Im a teapot
```

orval.config.js
```
export default defineConfig({
  test: {
    input: './test.yaml',
    output: {
      mode: 'tags',
      target: 'src/generated/test/test.ts',
      prettier: true,
      mock: false,
      override: {
        mutator: {
          path: 'src/lib/axios.ts',
          name: 'test',
        },
      },
    },
  },
});
```

## What happens?

🛑  test - TypeError: Cannot read properties of undefined (reading 'example')

## What were you expecting to happen?

🎉 test - Your OpenAPI spec has been converted into ready to use orval!

## Any other comments?

Defining empty error in swagger and rendering with orval for React Query results in type error. 

To overcome that with defining empty application/json response results in another bug (will report soon). Using content: examples: {} will suppress this bug

## What versions are you using?

**Operating System:** Sonoma 14.1
**Package Version:** 6.20.0
**Node Version:** node 20.5.1

**Comment by vitkarpov** [comment]
Might be related to https://github.com/anymaniax/orval/pull/1109

**Comment by melloware** [comment]
@jackoob please try 6.24.0.  I will reopen if you report back it's still broken.
