### ISSUE TITLE
Deserializing OpenAPI date and datetimes as JavaScript Date objects

### ISSUE THREAD

**Issue by techquestions** [anymaniax/orval#106]
I would like to add an option to the library, so that the user can deserialize date and datetime objects ([both have type `string` and format `date` and `date-time`, respectively](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#data-types)) as JavaScript `Date` object.

I have already tested it and this change in `scalar.ts` seems to actually be the only change needed (to be added inside the `string` case statement):

```
      if(item.format === 'date' || item.format === 'date-time') {
        return {
          value: 'Date' + nullable,
          isEnum: false,
          type: 'string',
          imports: [],
          schemas: [],
        };
      }
```

This would only support ISO 8601 dates and date times (default in the OpenAPI specification) but that is what most of the people use in the REST APIs these days.

However, there will also be change needed in the Axios instance, so that dates are properly deserialized as `Date` objects (currently these are `string`s).

Would you be open for such change? Do you think we should make it optional, via dedicated field in the configuration object?

**Comment by anymaniax** [comment]
Hello,

First thanks for your interest and your investigation.

For me, the string is the appropriate default type since the type Date doesn't exist in a JSON. But we could find a proper way to override this and transform them into Date objects. More like a mix of [this](https://orval.dev/reference/configuration#format) and the [mutator](https://orval.dev/reference/configuration#mutator) functionality.

To solve this at the moment you could use the [mutator](https://orval.dev/reference/configuration#mutator) feature to transform your payload automatically and normally everything should work correctly since I am using the type returned by the mutator function.

**Comment by techquestions** [comment]
> For me, the string is the appropriate default type since the type Date doesn't exist in a JSON

JSON is a bit old format which doesn't even have proper support for numbers or object keys, that's why formats like JSON5 are being created. I actually thought that `orval` focuses on TypeScript types, not what JSON offers.

> To solve this at the moment you could use the mutator feature to transform your payload automatically and normally everything should work correctly since I am using the type returned by the mutator function.

I think this is a different thing. Yes, there will be a need to create a mutator, since Axios also deserializes dates to `string`s (`JSON.parse()` doesn't have any support for dates). And that is why I suggested this to be an option in orval's configuration, so that by default dates are still typed as strings.
Looking at the current examples, what I want is, in the `pet.ts`, the `Pet` to have a field of type `Date` (if it has such field in the API definition of course).
It will not work out of the box by just using mutator and I believe a change in the library itself is needed. It could be a non-breaking change and it could be turned on via a configuration flag.

**Comment by anymaniax** [comment]
Ok then we could add a property date: boolean in the override section which will put the type Date in the definition and you would do the parse of the payload in your project with the `transformResponse` from axios for example.

**Comment by anymaniax** [comment]
@techquestions I did the implementation and the example in this pull request #107. Can you check if this is what you want?

**Comment by anymaniax** [comment]
Need to be reimplemented since v5. I will do it if you are still interested or someone else?

**Comment by dennisroche** [comment]
@anymaniax I'm interested having `Date` objects for our models. 

How difficult would this be to re-implement on latest? or to have a mutator to use https://github.com/moment/luxon/ `DateTime` objects?

**Comment by melloware** [comment]
+1 for this, this is what `openapi-generator` does it makes then `Date` objects.

**Comment by melloware** [comment]
PR Submitted. Wasn't quite sure how to add unit tests.

**Comment by melloware** [comment]
Thanks for releasing 6.6.0 i just updated my project and it works like a charm!
