### ISSUE TITLE
React-query with customClient throws Invalid hook call.

### ISSUE THREAD

**Issue by yusijs** [anymaniax/orval#1066]
## What are the steps to reproduce this issue?

Call orval with a custom client when generating code for react-query

My config file:
```js
module.exports = {
  roma: {
    // name of your api
    input: {
      target: './roma/openapi.json', // swagger file. can be yaml or json, and can point to an external resource (url)
    },
    output: {
      mode: 'tags-split', // Split the methods by tags.
      target: 'api', // where to output the apis if mode = "single". This prop is mandatory even if not single ¯\_(ツ)_/¯
      schemas: 'model', // Where to output the type definitions
      client: 'react-query', // Generate react-query hooks
      workspace: 'roma/', // Where to output the api files
      mock: false, // Whether to generate msw files for mocking tests etc.
      prettier: true, // Format the output with prettier
      override: {
        useTypeOverInterfaces: true, // Prefer type to interface {}
        mutator: {
          path: './use-client.ts', // Path to the custom httpClient (within the workspace-dir)
          name: 'useFusionClient', // Name of the hook to use
        },
      },
    },
  },
};
```

## What happens?

Within the generated code, it generates this function:
```ts
export const getAllCategories = (signal?: AbortSignal) => {
  return useFusionClient<CategoryDto[]>({
    url: `/api/apps/categories`,
    method: 'get',
    signal,
  });
};
```

This will throw the error `Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons`

## What were you expecting to happen?

Generated code should not use the getAllCategories function, but go directly from `useGetAllCategories` to `useFusionClient`

## Any logs, error output, etc?

…

## Any other comments?

…

## What versions are you using?

**Operating System:** MacOS
**Package Version:** Orval v6.20.0
**Browser Version:** N/A

**Comment by yusijs** [comment]
Ugh nvm, I had cocked up my custom hook.

**Comment by melloware** [comment]
Thanks for posting back!
