### ISSUE TITLE
Cannot find module 'lodash/get'

### ISSUE THREAD

**Issue by mbwestphal** [anymaniax/orval#1076]
## What are the steps to reproduce this issue?

1. Build using PNPM

## What happens?

Build fails

## What were you expecting to happen?

Find module `lodash/get` and build

## Any logs, error output, etc?

```
Error: Cannot find module 'lodash/get'
Require stack:
- /project/node_modules/.pnpm/@orval+core@6.20.0/node_modules/@orval/core/dist/index.js
- /project/node_modules/.pnpm/orval@6.20.0/node_modules/orval/dist/index.js
```

## Any other comments?

`orval`s `package.json` is not listing `lodash` or `lodash.get` as a dependency.

## What versions are you using?

**Operating System:** Debian
**Package Version:** 6.20.0
**Browser Version:** Not applicable

**Comment by melloware** [comment]
Can you provide a reproducer?

**Comment by melloware** [comment]
can you try with 6.21.0. I can't reproduce?

**Comment by kvet** [comment]
I can confirm that the issue exists when just installing the `orval@6.22.1` package using pnpm. The following hacky fix helped:

```js
//.pnpmfile.cjs

module.exports = {
    hooks: {
      readPackage: (pkg) => {
         if (pkg.name === '@orval/core' || pkg.name === 'orval') {
            pkg.dependencies['lodash'] = '*';
         }
      }
   }
}
```

**Comment by melloware** [comment]
A PR is welcome if you know the fix?

**Comment by zereight** [comment]
remove pnp

<img width="1039" alt="스크린샷 2024-02-01 오전 10 49 28" src="https://github.com/anymaniax/orval/assets/42544600/0d1235ef-d64d-4e90-86fa-04b49db4b8c3">

**Comment by gunzip** [comment]
I've the same issue using yarn 4.1.1 pnp and found no workaround yet.
