### ISSUE TITLE
Cannot generate strictly suspense query hooks

### ISSUE THREAD

**Issue by ezequiel** [anymaniax/orval#1098]
## What are the steps to reproduce this issue?

```js
module.exports = {
  api: {
    input: '../docs/swagger.json',
    output: {
      target: 'api.ts',
      mode: 'split',
      client: 'react-query',
      override: {
        query: {
          useQuery: false,
          useInfinite: false,
          useSuspenseQuery: true,
          useSuspenseInfiniteQuery: true,
        },
      },
      workspace: 'src/api',
    },
  },
};
```
## What happens?
No query hooks are generated. Only mutations are generated. There seems to be a bug where `useQuery` must be true, otherwise nothing generates

## What were you expecting to happen?
Hooks containing `useSuspenseQuery`, `useSuspenseInfiniteQuery` are generated (and not `useQuery` or `useInfiniteQuery`, as I don't want usages of those functions in my project)

## What versions are you using?

**Operating System:** Mac OS Ventura
**Package Version:** Latest
**Browser Version:** Chrome latest

**Comment by ezequiel** [comment]
I _think_ we're missing the Suspense variants here: https://github.com/anymaniax/orval/blob/master/packages/query/src/index.ts#L1134-L1137

This condition would also need to be changed if we wish to strictly generate Suspense hooks: https://github.com/anymaniax/orval/blame/master/packages/query/src/index.ts#L1198

**Comment by melloware** [comment]
@georgiev-anton

**Comment by melloware** [comment]
PR's are welcome!
