### ISSUE TITLE
Input filters doesn't filter schemas

### ISSUE THREAD

**Issue by renaudAmsellem** [anymaniax/orval#1099]
Thanks for the lib! It's working perfectly.

## What are the steps to reproduce this issue?

1. Use an OpenAPI spec with multiple tags and specific schemas per path
2. Generate files with orval and filter with one tag

## What happens?

API methods are filtered by the tag
All the schemas are generated

## What were you expecting to happen?

Only the schemas linked with the filtered input paths are generated

## Any other comments?

I created a mini repo to demonstrate this issue: https://github.com/renaudAmsellem/orval-filter-example
It has 2 paths: `pet` and `shelter`. Each with a specific schema.
`orval.config.ts` is configured to filter only `pet`

We can see that only the `pet` methods are generated in the `api` file (Great :) )
We can also see that the `pet` and the `shelter` models are generated

But the shelter model is useless since it is not used in any methods of the `api` file.

## What versions are you using?

**Package Version:** 6.21.0

**Comment by SeanSDixon** [comment]
Hey, I ran into this issue too. Im just checking to see if there has been any progress on this Issue or if there is any estimate of when it may be done? 

Thanks,
Sean

**Comment by melloware** [comment]
@soartec-lab any chance you want to investigate this one?

**Comment by soartec-lab** [comment]
@melloware 
Thank you for inviting me.
But, this response is not a high priority for me, so even if I start investigating, it will take time.
