### ISSUE TITLE
Array schema values aren't marked as readonly 

### ISSUE THREAD

**Issue by ezequiel** [anymaniax/orval#1102]
## What are the steps to reproduce this issue?

```json
{
  "swagger": "2.0",
  "info": {
    "title": "My API",
    "version": "1.0"
  },
  "paths": {},
  "definitions": {
    "models.ThingDescription": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string"
        }
      }
    },
    "models.Thing": {
      "type": "object",
      "properties": {
        "ThingDescriptions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/models.ThingDescription"
          },
          "readOnly": true
        }
      }
    }
  }
}

```

## What happens?

When an `array` schema has `"readOnly": true` set, the field value isn't marked as `readonly`.  e.g. below, field `ThingDescriptions` is correctly marked as `readonly`, but the value `ModelsThingDescription[]` isn't

```ts
export type ModelsThingDescription = {
  text?: string;
};

export type ModelsThing = {
  readonly ThingDescriptions?: ModelsThingDescription[];
};
```

## What were you expecting to happen?
`ModelsThingDescription[]` is marked as `readonly`

```ts
export type ModelsThingDescription = {
  text?: string;
};

export type ModelsThing = {
  readonly ThingDescriptions?: readonly ModelsThingDescription[];
};
```

## What versions are you using?

**Operating System:** Mac OS Ventura
**Package Version:** latest
**Browser Version:** Chrome latest

**Comment by ezequiel** [comment]
My hunch is we just have to check if the schema is `readOnly` here, and prepend `"readonly "`: https://github.com/anymaniax/orval/blob/8bf7cbf48709a695566b969efe2950df1a0a7546/packages/core/src/getters/array.ts#L27-L29

**Comment by melloware** [comment]
want me to assign to you?
