### ISSUE TITLE
OpenAPI 3.1: Generator seems to not support `const` field in schema

### ISSUE THREAD

**Issue by feds01** [anymaniax/orval#1108]
## What are the steps to reproduce this issue?

1. Use the following schema: https://pastebin.com/iaChwzNz
2. Create a new Angular 16 project (albeit this is likely irrelevant to the issue - any `client` kind likely features the problem).
3. Create an Orval config `orval.config.ts`:
```ts
module.exports = {
    events: {
        output: {
            baseUrl: 'http://127.0.0.1:9421',
            client: 'angular',
            mock: false,
            mode: 'split',
            target: 'projects/client/src/client.ts',
        },
        input: 'schema.json',   
   },
};
```
4. Generate Client with Orval

## What happens?

Resultant annotation type is set as `unknown`, e.g. for `BingData` with get the following schema types:
```ts
export interface DingData {
  anything_you_need: unknown;
}

export interface BingData {
  bing: unknown;
}
```

## What were you expecting to happen?

It would be typed as the following:

```ts
export interface DingData {
  anything_you_need: 'anything_you_need';
}

export interface BingData {
  bing: 'bing';
}
```

## Any other comments?

This feature was introduced in OpenAPI schema version [3.1.0](https://www.apimatic.io/blog/2021/09/migrating-to-and-from-openapi-3-1).

This issue occurs in any area that features the `const` field.

## What versions are you using?

**Operating System:** MacOS 14.1.1 (23B81)
**Package Version:** 6.22.1

**Comment by CameronMackenzie99** [comment]
This change is dependent on an upstream change to the openapi3-ts library, issue [here](https://github.com/metadevpro/openapi3-ts/issues/129).

This is to include the `const` keyword in the type definition of the `SchemaObject` type. Then we can add a check in the `getObject` method of the core package for if the item is a const type object and handle accordingly

**Comment by melloware** [comment]
Thanks I marked the ticket "third party" too as its waiting on a 3rd party change.
