### ISSUE TITLE
Missing types from components > requestBodies

### ISSUE THREAD

**Issue by OliverDudgeon** [anymaniax/orval#112]
## What are the steps to reproduce this issue?
1. Run orval 4.2.0 on our [OpenAPI JSON](https://squonk.informaticsmatters.org/data-manager-api/openapi.json) with any basic config
2. View type errors in editor

## What happens?
A few types are not generated in the models: `DatasetUpload`, `Labels`, `DatasetAttach`.
These are all located in the `components > parameters > requestBodies` section of the OpenAPI and then are referenced in paths `$ref: #/components/requestBodies/datasetUpload`

## What were you expecting to happen?
These types to be generated from the schema like other sections of `components`

## Any logs, error output, etc?
None

## Any other comments?
Something about our spec that orval doesn't like, such as dupe key names betweens sections?

## What versions are you using?
**Operating System: Ubuntu 20.04 …
**Package Version: 4.2.0 …
**Browser Version:

**Comment by anymaniax** [comment]
@OliverDudgeon Hello, thanks for reporting this bug. I just published a new alpha version that should solve your problem you can check [5.0.0-alpha.4](https://www.npmjs.com/package/orval/v/5.0.0-alpha.4). I saw that you use multipart with an object, I did an implementation for it but if it's doesn't work for your case let me know what you would have expected. But either way, you can use a [mutator](https://orval.dev/reference/configuration#mutator) with those [operations](https://orval.dev/reference/configuration#operations) to send the data as you want.

**Comment by OliverDudgeon** [comment]
Hi, thanks for the alpha build. It's letting us make progress!

The multipart forms use arrays for "labels". Our API accepts these comma-seperated so

["label1", "label2"] => "label1,label2"

E.g. our Swagger UI generates this curl

```curl
curl -X POST "https://squonk.informaticsmatters.org/data-manager-api/dataset" -H  "accept: application/json" -H  "Authorization: Bearer eyJV0y_QX...3a_Ag7nMtA" -H  "Content-Type: multipart/form-data" -F "as_filename=test" -F "dataset_type=chemical/x-mdl-sdfile" -F "labels=l1,l2" -F "dataset_file=@Mpro-x0387-x0072-3hop-best1-top1000.sdf.gz;type=application/gzip"
```

I.e just a `labels.join(',')` but this of course just our chosen method. Like with query parameters there are several ways for [Objects](https://medium.com/raml-api/objects-in-query-params-173d2712ce5b) and [Array](https://medium.com/raml-api/arrays-in-query-params-33189628fa68).

I would guess Orval should provide a field in the config that would take an object or array and "stringify" it based on the user's API design. Or is that just a missing example/doc for how to use a mutator?

**Comment by anymaniax** [comment]
Hello, Thanks for the feedback. When you use a mutator you receive directly the body data not transformed and then you can use it or transform it how you want. I am hesitating to add an option in the config to modify directly the form data. You would give the default key for the form data (currently like this formData.append('data', THEDATA) or a function to help you generate your form data how you want (example (bodyData) => { your implementation which return a form data })
