### ISSUE TITLE
Different return types depending on status code alone

### ISSUE THREAD

**Issue by 02strich** [anymaniax/orval#1120]
## What are the steps to reproduce this issue?
1. Have a operation that returns multiple return codes for success, e.g. 
```
  /accept/{invite_key}:
    parameters:
      - in: path
        name: invite_key
        required: true
        schema:
          type: string
    post:
      operationId: AcceptInvitation
      responses:
        '201':
          description: Invitation accepted
          content:
            application/json:
              schema:
                type: object
        '204':
          description: Invitation already accepted before
          content:
            application/json:
              schema:
                type: object
```

## What happens?
The generated code cannot distinguish between the two types as it doesn't consider the status code anywhere.

## What were you expecting to happen?
Some way for the code to either return the status code (in addition to the body), or the generated code to handle the difference.

## Any logs, error output, etc?
n/a

## Any other comments?
I don't know whether "I am holding it wrong" or this is a gap - looking for guidance.

## What versions are you using?

**Operating System:** MacOS
**Package Version:** 6.12.1
**Browser Version:** n/a

**Comment by soartec-lab** [comment]
@02strich 

Well, `OpeaAPI` supports the case where there are multiple `20X`. Also, in `orval`
Supports multiple types of successful responses. However, the method of accessing the returned status code differs depending on the client you are using, so please refer to the respective client package you are using.
