### ISSUE TITLE
Invalid imports on Windows

### ISSUE THREAD

**Issue by cvk77** [anymaniax/orval#114]
Node's path.join(...) generates platform-specific path separators, so it's not safe to use in [`generateImports(...)`](https://github.com/anymaniax/orval/blob/6f2c3629b384d04fe984a67e4b91c28a31d797e3/src/core/generators/imports.ts#L36).

Generated imports in Windows:
```
import { ... } from '..\model';
import { customInstance } from '..\mutator\custom-instance';
```

Tested in 5.0.0-alpha.5

**Comment by anymaniax** [comment]
Ok thanks. I will check for a better solution

**Comment by anymaniax** [comment]
Hello, I just published the [5.0.0-alpha.6](https://www.npmjs.com/package/orval/v/5.0.0-alpha.6) which use [upath](https://www.npmjs.com/package/upath) and should solve your problem 😀

**Comment by cvk77** [comment]
Thanks a lot, will check it out asap.

**Comment by cvk77** [comment]
I finally got around to testing the new version. Works fine now, thanks for the quick fix!

**Comment by emidiotorre** [comment]
Hi, we had this issue with the latest version 6.11 and we solved by downgrading it to 6.10. @anymaniax

**Comment by anymaniax** [comment]
same as #725. I am currently on it

**Comment by anymaniax** [comment]
Hello @emidiotorre, can you try if `6.11.1-alpha.1` is working for you
