### ISSUE TITLE
Upgrading `prettier` to `v3` causes an error in `pretty-quick`

### ISSUE THREAD

**Issue by soartec-lab** [anymaniax/orval#1140]
## What are the steps to reproduce this issue?

1. upgrade `prettier` to `v3`
2. execute `git commit` or `yarn format:staged`

## What happens?

raised error by `pretty-quick`

## What were you expecting to happen?

Even `v3` of `prettier` works as before.

## Any logs, error output, etc?

```
$ pretty-quick --staged
🔍  Finding changed files since git revision f67681fb.
/app/node_modules/pretty-quick/dist/isSupportedExtension.js:12
  ..._prettier.resolveConfig.sync(file, {
                             ^

TypeError: _prettier.resolveConfig.sync is not a function
    at /app/node_modules/pretty-quick/dist/isSupportedExtension.js:12:30
    at Array.filter (<anonymous>)
    at _default (/app/node_modules/pretty-quick/dist/index.js:53:157)
    at Object.<anonymous> (/app/node_modules/pretty-quick/bin/pretty-quick.js:17:27)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.10.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky - pre-commit hook exited with code 1 (error)
```

## Any other comments?

When I checked about `pretty-quick`, it appeared that this library was no longer maintained. [Related Issue](https://github.com/azz/pretty-quick/issues/164) has also been raised.

It seems we need to switch to another library. There are two alternative packages:

- [lint-staged](https://github.com/lint-staged/lint-staged)
- [lefthook](https://github.com/evilmartians/lefthook)

I am planning to move to `lint-staged` which can be managed with `package.json` as before.

## What versions are you using?

**Package Version: 6.23.0**

**Comment by melloware** [comment]
@anymaniax would like your thoughts here please?

**Comment by soartec-lab** [comment]
If we were to handle it with `lint-staged`, it would look like this. I am creating a [PR](https://github.com/anymaniax/orval/pull/1141) by `draft` status.

**Comment by anymaniax** [comment]
lint-staged is just to run command based on some glob. It won't solve the problem we have just to stop use pretty-quick and use prettier directly. Or I miss something?

**Comment by soartec-lab** [comment]
@anymaniax 

I think it's good. I just tried to maintain the original behavior.
Then, it seems like it would be a good idea to simply run `prettier`. If there are no problems, I will close the PR I created as a draft.

**Comment by soartec-lab** [comment]
@anymaniax 

I thought about this for a while and changed my mind.

If we simply run `prettier`, it will target all files, and you will spend a lot of time doing complicated things. however, by using `lint-stage`, we can narrow down the target to only the files you are about to commit, which I thought would be a advantage as it would save time.

I would like to make this change if possible. What do you think after hearing my opinion?

**Comment by soartec-lab** [comment]
thank you. I'll handle this.
