### ISSUE TITLE
Generate true Typescript enums

### ISSUE THREAD

**Issue by rnm-sxm** [anymaniax/orval#1153]
Orval does not generate true Typescript enums. Instead it generates const object with a set of readonly keys/values

## What are the steps to reproduce this issue?

1. Use orval to generate a Typecript file using this OpenAPI schema

```yaml
openapi":  "3.0.3"
info:
  version: 0.1
  title: Enum Keyword Test
  description: Generated enums
paths:
  /color1:
    get:
      parameters:
      - in: query
        name: color1
        required: true
        schema:
          $ref: '#/components/schemas/Color1'
      responses:
        '200':
          description: OK
  /color2:
    get:
      parameters:
      - in: query
        name: color2
        required: true
        schema:
          $ref: '#/components/schemas/Color2'
      responses:
        '200':
          description: OK
components:
  schemas:
    Color1:
      type: string
      enum:
        - black
        - white
        - red
        - green
        - blue
    Color2:
      type: number
      enum:
        - 0
        - 10
        - 20
        - 30
        - 40
      x-enumNames:
        - black
        - white
        - red
        - green
        - blue
```

## What happens?
The generated typescript includes these two enums:
```ts
export type Color2 = (typeof Color2)[keyof typeof Color2];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Color2 = {
  black: 0,
  white: 10,
  red: 20,
  green: 30,
  blue: 40,
} as const;

export type Color1 = (typeof Color1)[keyof typeof Color1];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Color1 = {
  black: "black",
  white: "white",
  red: "red",
  green: "green",
  blue: "blue",
} as const;
```

## What were you expecting to happen?
[Typescript Enums](https://www.typescriptlang.org/docs/handbook/enums.html) should be generated:

```ts
export enum Color2 {
  black = 0,
  white = 10,
  red = 20,
  green = 30,
  blue = 40,
};

export enum Color1 {
  black = "black",
  white = "white",
  red = "red",
  green = "green",
  blue = "blue",
};
```

## Any logs, error output, etc?

none.

## Any other comments?

none.

## What versions are you using?

**Operating System:** Xubuntu 22.04
**Package Version:**  "orval": "^6.23.0"
**Browser Version:** N/A

**Comment by melloware** [comment]
This was added in 6.21.0: https://github.com/anymaniax/orval/issues/907

Is it not working for you?

**Comment by melloware** [comment]
PR for documentation update would be great!

**Comment by rnm-sxm** [comment]
There is still a bug related to the way the x-enumNames is used. It ends up generating enums with colons (Color2) instead of equals:

```ts
export enum Color2 {
  black: 0,
  white: 10,
  red: 20,
  green: 30,
  blue: 40,

}
export enum Color1 {
  black= 'black',
  white= 'white',
  red= 'red',
  green= 'green',
  blue= 'blue',
}
```

**Comment by melloware** [comment]
PR welcome

**Comment by melloware** [comment]
Cc @dsthode who made this change.

**Comment by soartec-lab** [comment]
Thank you for sharing this issue. I will also check the PR. looking forward to it 🙌

**Comment by rnm-sxm** [comment]
The fix appears to be a one-liner, but I'm not familiar with this project - I don't know how to build it.

packages/core/src/getters/enum.ts, line 93 should be
```ts
        `  ${keyword.isIdentifierNameES5(name) ? name : `'${name}'`}= ${val},\n`
```

**Comment by melloware** [comment]
@soartec-lab are you submitting this PR or is @rnm-sxm ?

**Comment by soartec-lab** [comment]
No, I haven't started yet. 

@rnm-sxm 

If you don't do it, I can also respond to this next to the other responses.

**Comment by rnm-sxm** [comment]
@soartec-lab Thanks for taking this over.
