### ISSUE TITLE
Bug: Nordic characters are ignored

### ISSUE THREAD

**Issue by orhels** [anymaniax/orval#1156]
## What are the steps to reproduce this issue?

1. Use Orval to generate typescript files with the following schema:
```yaml
openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger ÆrligØnskeÅpen
  license:
    name: MIT
paths:
  /ærligØnskeÅpen:
    get:
      summary: List all ærlig-ønske-åpen
      operationId: listÆrligØnskeÅpen
      responses:
        '200':
          description: A paged array of ærlig-ønske-åpen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ÆrligØnskeåpen'
components:
  schemas:
    ÆrligØnskeåpen:
      type: object
      required:
        - ærlig
        - ønske
        - åpen
      properties:
        ærlig:
          type: string
        ønske:
          type: string
        åpen:
          type: string
```

## What happens?

It generates the file `rligNskePen.ts`:
```typescript
export interface RligNskePen {
  ærlig: string;
  åpen: string;
  ønske: string;
}
```

## What were you expecting to happen?

It should generate the file `ærligØnskeåpen.ts`:
```typescript
export interface ÆrligØnskeåpen {
  ærlig: string;
  åpen: string;
  ønske: string;
}

```
## Any logs, error output, etc?

Nope.

## Any other comments?

I've been testing with different versions of Orval, and the issue starts with 6.18.0.

## What versions are you using?

**Operating System:** MacOs 13.6.3
**Package Version:** 6.23.0 
**Browser Version:** Chrome 119.0.6045.123

**Comment by melloware** [comment]
My gut feeling is this is the ticket that broke it: https://github.com/anymaniax/orval/pull/909

**Comment by orhels** [comment]
I have a PR comming where I belive I've fixed the issues. My testing found that #951 was probably the cause.
