### ISSUE TITLE
Reproducable TypeScript output

### ISSUE THREAD

**Issue by rnm-sxm** [anymaniax/orval#1159]
When I run the typescript generator, I expect the output to be consistent from run to run.

## What are the steps to reproduce this issue?

1. Run npx orval in the attached workspace

## What happens?

Structures and/or other elements may occur in different orders in the output TypeScript file (gen/reproduce.ts)

## What were you expecting to happen?

Every time the generator is run, the output should be identical.

## Any logs, error output, etc?

N/A

## Any other comments?

None

## What versions are you using?

**Operating System:** Xubuntu 22.04
**Package Version:** Oval 6.23.0
**Browser Version:** N/A

[reproduce.tar.gz](https://github.com/anymaniax/orval/files/13954907/reproduce.tar.gz)

**Comment by melloware** [comment]
I know this has been fixed in Other reproducers like React Query i know used to generate random order but now generates the same file every time.  So I am sure the same fix needs to be applied here...
