### ISSUE TITLE
TypeScript: Variable is used before being assigned / Block-scoped variable used before its declaration

### ISSUE THREAD

**Issue by kennyhei** [anymaniax/orval#1183]
## What are the steps to reproduce this issue?

You can either download only the JSON or setup FastAPI project that produces the OpenAPI JSON.
JSON is here: 
[openapi.json](https://github.com/anymaniax/orval/files/14085139/openapi.json)

**Note: You can skip this part if you only want to use the downloaded JSON for orval:**
1. Download example FastAPI project
[fastapi-example.zip](https://github.com/anymaniax/orval/files/14085048/fastapi-example.zip)
2. Unzip project, in terminal go to directory and run following commands:
3. `python3 -m venv venv`
4. `source venv/bin/activate`
5. `pip install -r requirements.txt`
6. `uvicorn main:app --reload`

Now you should be able to access OpenAPI JSON in http://localhost:8000/openapi.json

Run `orval --input http://localhost:8000/openapi.json --output ./api.ts`

OR

Run `orval --input [download_dir_path]/openapi.json --output ./api.ts`

## What happens?

There should be this line of code:
```js
export const ProposalCalculationRowUpdatePartialCostCategory = {...ManualRowCostCategoryEnum,...ProductCostCategoryEnum,} as const;
```
Which has TS errors saying "Block-scoped variable 'ManualRowCostCategoryEnum' used before its declaration." and "Variable 'ManualRowCostCategoryEnum' is used before being assigned.", same for ProductCostCategoryEnum. These are also clear JS errors as const variables cannot be referenced before assignment.

## What were you expecting to happen?

Not have any errors that cause JS code to break (in this case ReferenceError) when running the file.

## Any other comments?

Code is from fairly large project I'm working on so I simplified it as much as possible. The way Pydantic models are named and such seem to affect whether orval knows how to generate valid code so don't be too confused if things are named weirdly in the example project. However, it probably should still work, no matter how the schemas are named?

It seems that Orval 6.7.0 has fixed most (but not all) of these issues as with versions 6.0.0-6.6.0 I got around 117 exact same errors but with >=6.7.0 only 24 (when using the original code of my project). 

## What versions are you using?

**Operating System:** OSX / Mac Sonoma 14.2.1
**Package Version:** 6.25.0
**Typescript Version**: 4.7.4
**Browser Version:** Chrome 120.0.6099.216

**Comment by melloware** [comment]
Thanks to @AffeJonsson fixed for 6.29.0
