### ISSUE TITLE
Node16 or bundler module resolution causes TS2742 error

### ISSUE THREAD

**Issue by david10sing** [anymaniax/orval#1195]
## What are the steps to reproduce this issue?
1. Use orval in a repo where the tsconfig `moduleResolution` is set to `node16` or `bundler`
2. Generate react-query client where there are mutation queries

## What happens?

The following gets reported in IDE and also when running `npx tsc`.

```
The inferred type of 'X' cannot be named without a reference to '../../node_modules/msw/lib/core/handlers/HttpHandler'. This is likely not portable. A type annotation is necessary.

The inferred type of 'X' cannot be named without a reference to '../../node_modules/@tanstack/react-query/build/modern/types'. This is likely not portable. A type annotation is necessary.
```

Declaration files where these errors happen do not get generated.

## What were you expecting to happen?

TS2742 should not happen.

## Any logs, error output, etc?

Please see above

## Any other comments?

Possibly linked to:
- https://github.com/microsoft/TypeScript/issues/42873
- https://github.com/TanStack/query/discussions/6670

- I think if we strictly type the return of the `useMutation` on the following line, it fixes this error. https://github.com/anymaniax/orval/blob/9b28acd87b88dee1b5556c9af7b446b429c92e79/packages/query/src/index.ts#L1451
- Same thing should be done for the mock files.

Strictly typing the returns would be a workaround until this is actually fixed upstream in TypeScript.

I can look into creating a PR for this. Please advise if you would like me to address this.

**Comment by melloware** [comment]
Yes please submit a PR for review!
