### ISSUE TITLE
Possibility of TS2563 error for mock generation

### ISSUE THREAD

**Issue by DevSDK** [anymaniax/orval#1203]
## What are the steps to reproduce this issue?

1. With LARGE & COMPLEX scheme
2. non-splited .msw file can cause TS error

## What happens?

According to the test case in Typescript [1], we have a possibility to meet `TS2563: The containing function or module body is too large for control flow analysis.` if the generated source file has control flow nodes > 10000.

If the scheme is complex,  large, or many (per service?), This issue can be present.

I met this issue when I tried to implement the initial and raw version of #1199 which was adding an assignment statement for every scalar while trying to apply our product's complex scheme. (e,g,
`faker.number() ?? overrideResponse?.['foo']?.['bar']`) 

As a result, `yarn build` raises an error TS2563 with unable to build.

[1] https://github.com/microsoft/TypeScript/blob/6f1ad5ad8bec5671f7e951a3524b62d82ec4be68/tests/baselines/reference/largeControlFlowGraph.errors.txt

## What were you expecting to happen?

No TS2563 error or split the control flow nodes.

## Any other comments?

This case may be rare. However, it is nice to avoid them :)

Following is a workaround try:

Simply adding `@ts-ignore` on top of the generated foo.msw.ts file.

## What versions are you using?

**Operating System:** …
**Package Version:** …
**Browser Version:** …

**Comment by soartec-lab** [comment]
@DevSDK 
Thank you for writing the report.
I recommend tagging and partitioning large schemas appropriately. You can avoid this by setting `mode` to `tags-split`.
We already provide that functionality so use it as a workaround.

**Comment by melloware** [comment]
@DevSDK can you report back after doing `tags-split` so I can close this ticket as workaround if it fixes your issue?

**Comment by soartec-lab** [comment]
@DevSDK 
Would you check this ?

**Comment by soartec-lab** [comment]
@DevSDK 

Of course, I would appreciate it if you would check it next time it happens.

I think that's a good idea. However, this error can occur in all modes due to the way the open API is defined for us. And considering that it is a rare case, I personally do not support supporting each error with documentation. 

We have provided a workaround for this issue and are closing it as we do not plan to make any changes to the source code.

**Comment by soartec-lab** [comment]
We have provided a workaround for this issue and are closing it as we do not plan to make any changes to the source code.
