### ISSUE TITLE
TS2300 Duplicate identifier: duplicated imports when `mock` enabled

### ISSUE THREAD

**Issue by dyatko** [anymaniax/orval#1204]
## What are the steps to reproduce this issue?

1. Set mode: 'tags' and mock: true

## What happens?

The generated file contains duplicated type imports from schemas

## What were you expecting to happen?

No double imports

## What versions are you using?

**Operating System:** MacOS
**Package Version:** 6.24.0

**Comment by soartec-lab** [comment]
There are some other bugs as well, so I'll check here after fixing them.

**Comment by soartec-lab** [comment]
It may be related to #1201 , and #1202

**Comment by soartec-lab** [comment]
@dyatko 
Hi, this issue was bug, so i fixed by #1205 
The next version will have the import working fine, so check it out when it's released.

**Comment by dyatko** [comment]
Nice, thank you very much.
Looking forward!

**Comment by soartec-lab** [comment]
Hi, @dyatko 

Since we released "v6.25.0" this issue has been fixed 👍

**Comment by dyatko** [comment]
@soartec-lab amazing, going to try tomorrow!
