### ISSUE TITLE
Is possible ignore the changes in the line of OpenAPI spec version ?

### ISSUE THREAD

**Issue by MedinaGitHub** [anymaniax/orval#1218]
### Discussed in https://github.com/anymaniax/orval/discussions/1213

<div type='discussions-op-text'>

<sup>Originally posted by **MedinaGitHub** February  9, 2024</sup>
When updating a single value in our model, I notice that hundreds of files are marked as modified, the only modification being the version of the OpenAPI specification. This situation is not only annoying but also complicates code reviews.  Is there any way to pass parameters to specifically ignore changes to that line...?

{
 "output": {
   "ignoreSwaggerVersion": true,

<img width="1317" alt="image" src="https://github.com/anymaniax/orval/assets/16387514/45524ab3-7dde-4390-8677-c092fcc29e72">
</div>

**Comment by MedinaGitHub** [comment]
I found the "header" method and it works for my needs. thanks!

```
  petstore: {
    output: {
      override: {
        header: (info: InfoObject): String[] => [
          `Generated by orval 🍺`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
      },
    },
```

**Comment by melloware** [comment]
Awesome I updated this ticket to "workaround".
