### ISSUE TITLE
Another duplicate export edge case

### ISSUE THREAD

**Issue by pcfreak30** [anymaniax/orval#1220]
## What are the steps to reproduce this issue?

1. Use https://git.lumeweb.com/LumeWeb/portal/src/commit/04948bde2ce9fe33e32d325871a8eec42b70cdc4/api/s5/swagger.yaml
2. Use the following config:
```
import { defineConfig } from "orval";

export default defineConfig({
  s5: {
    input: "./swagger.yaml",
    output: {
      mode: "tags",
      workspace: "./src/generated",
      target: "openapi.ts",
    },
  },
});
```

## What happens?
See the issue https://github.com/anymaniax/orval/issues/432. Duplicate exports between files.

## What were you expecting to happen?
Everything is to be exported to the primary parent cleanly.

## Any logs, error output, etc?

N/A

## Any other comments?

N/A

## What versions are you using?

**Operating System:** Linux Mint 21.1
**Package Version:** 6.24.0
**Browser Version:** N/A

**Comment by AffeJonsson** [comment]
Is this still an issue? Cannot repro on latest

**Comment by pcfreak30** [comment]
I would need to test it, haven't worked on this component specifically in a while.

**Comment by melloware** [comment]
I will close for now assuming 6.28.2 fixes the issue. I will re-open if it does not.
