### ISSUE TITLE
Specify mock property overrides for a specific schema

### ISSUE THREAD

**Issue by zunnzunn** [anymaniax/orval#1221]
## Feature Request

The possibility to [override generated mock data](https://orval.dev/reference/configuration/output#properties) is very useful for adapting the mocks to one's specific business logic. It is possible to specify an override by property name, which will then affect every property of that name, regardless to what schema it belongs. 
An example from the docs:
```ts
email: () => faker.internet.email(), // matches every "email" property, regardless of its path
```
It is possible to specify more specific overrides if the property is nested, ( e.g. `'user.id': () => faker.string.uuid()`) but what if one has e.g. a schema named `Dog` and a schema named `Cat` which both have a `name` property which is not nested (depth of 1)? 
How would one specify an override of the `name` property exclusively for the `Dog` or exclusively for the `Cat` schema?

If this is already possible, adding it to the docs would be much appreciated. Otherwise, it would be a great feature to implement!

**Comment by soartec-lab** [comment]
@zunnzunn 
I can't say that I understand the whole thing, but I looked into it again, as far as I know, there is no way to specify that the `output.override.mock.properties` option overrides only specific types. However, you can use the `overrideResponse` parameter to override the response of the generated mock function since `v6.24.0`.
Is this helpful to you?

```typescript
# generated 
export const getShowPetByIdMock = (overrideResponse?: any) => ({
  id: faker.number.int({min: undefined, max: undefined}),
  name: faker.word.sample(),
  tag: faker.helpers.arrayElement([faker.word.sample(), undefined]), ...overrideResponse
})

# usage
import { getShowPetByIdMock } from 'gen/pets.msw'

const pet = getShowPetByIdMock({name: 'orverride'})
console.log(pet)
// => { id: 7272122785202176, ​name: "orverride", tag: undefined }
```

**Comment by soartec-lab** [comment]
I'll mark this question as complete and close the issue.
