### ISSUE TITLE
React Query: Regression in 6.25.0 caused by #1207

### ISSUE THREAD

**Issue by melloware** [anymaniax/orval#1227]
Regression caused by https://github.com/anymaniax/orval/issues/1207

@soartec-lab this broke React Query in 6.25.0  I now get these TypeScript errors.

```
  Line 26:40:  Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `object` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
```

in 6.24.0 code was this

```js
export interface FilterConstraint {
	/** Filter match mode e.g. equals, notEquals, contains, notContains, gt, gte, lt, lte */
	matchMode?: string;
	/** Value to filter this column by */
	value?: unknown;
}
```

in 6.25.0 its this...

```js
/**
 * Value to filter this column by
 */
export type FilterConstraintValue = {};

export interface FilterConstraint {
	/** Filter match mode e.g. equals, notEquals, contains, notContains, gt, gte, lt, lte */
	matchMode?: string;
	/** Value to filter this column by */
	value?: FilterConstraintValue;
}
```

Which is now broken.

**Comment by soartec-lab** [comment]
@melloware 
Wow, the value of `type` is now `{}` instead of `unknown`. Could you please provide a schema that reproduces the problem?

**Comment by soartec-lab** [comment]
thanks!

**Comment by melloware** [comment]
Just an FYI this is my public project where I use Orval and detected the issue: https://github.com/melloware/quarkus-primereact

**Comment by soartec-lab** [comment]
Thank you. I haven't had time recently, but I think I'll be able to respond next week.
