### ISSUE TITLE
React query  options braking changes starting from v5

### ISSUE THREAD

**Issue by yjose** [anymaniax/orval#124]
This is not an issue 😀  I am just wondering why you opted to update the 2nd argument for query hooks instead of using the 3rd argument for Axios instance config starting from the version 5.
i think the old way is easier  as we use generate hooks the same way we use native react-query hook, please lets me know if I am missing something 🙏

**Comment by anymaniax** [comment]
Depending of the endpoints you can already have multiple arguments (all params, query params, body). The query config is optional and always the last argument. If I don't do this breaking change we will be force to pass undefined to the query config argument to pass an axios config. Same if we do it the other way around. That way I thought that an object where you can pass all options will be a better fit and will also help if we want to add other feature later on.

**Comment by anymaniax** [comment]
If you have other idea or option I am really open to discuss about it

**Comment by yjose** [comment]
Yeah, i get your point, but During my experience with react-query with Axios, I nearly find myself passing Axios config with hooks, and I usually use them globally to Axios instance such headers.
Not sure if its the same for you 
so for me, I would prefer to make my custom query hook identic as a simple react-query hook (same API), and should be ok to pass query configs as undefined in case I want to add Axios config.

**Comment by anymaniax** [comment]
check this issue #115. Personally, I use 90% of the time the global config but that's not the case for everyone. A solution would be to add an option in the orval config for that but I have no idea how to name it 😀

**Comment by anymaniax** [comment]
Something like this? And if you set false we don't add the config globally or per operation.
<img width="480" alt="Screenshot 2021-05-12 at 10 08 10" src="https://user-images.githubusercontent.com/10516382/117941064-05021700-b30a-11eb-839d-72119552b521.png">

**Comment by yjose** [comment]
i think this should work,   and we can make it false by default to prevent breaking  changes 👍 
we still can pass a custom Axios instance when `httpConfig: false` correct?

**Comment by anymaniax** [comment]
sure!

**Comment by yjose** [comment]
Great 
+1 for this approach

**Comment by anymaniax** [comment]
you now have a new option with the `5.3.0`. You can add this option in the override to only have the queryOptions
<img width="874" alt="Screenshot 2021-05-17 at 21 05 07" src="https://user-images.githubusercontent.com/10516382/118542704-aac2e500-b753-11eb-8d62-b5a208d52704.png">
