### ISSUE TITLE
Syntax error generating interface when spec properties is empty 

### ISSUE THREAD

**Issue by yjose** [anymaniax/orval#125]
## What are the steps to reproduce this issue?
1. input Schema with an empty type definition 
example 
```json
{
...
    "PaymentRequestSubmit": {"type": "object", "properties": {}},
...
}
```
2. run oval to generate typing and client  

## What happens?
issue generating typing interface : missed {}
```ts
/*
 * Generated by orval v5.1.3 🍺
 * Do not edit manually.
 * API Documentation
 * OpenAPI spec version: v1
 */

// tslint:disable-next-line:no-empty-interface
export interface PaymentRequestSubmit 
```

## What were you expecting to happen?
```ts
/*
 * Generated by orval v5.1.3 🍺
 * Do not edit manually.
 * API Documentation
 * OpenAPI spec version: v1
 */

// tslint:disable-next-line:no-empty-interface
export interface PaymentRequestSubmit {}
```

## Any other comments?
…

## What versions are you using?
**Operating System:** Mac os 
**Package Version:** 5.1.3

**Comment by anymaniax** [comment]
fixed in `5.1.4` 🎉
