### ISSUE TITLE
allOf with nullable: true does not generate nullable type

### ISSUE THREAD

**Issue by canvural** [anymaniax/orval#1252]
## What are the steps to reproduce this issue?

1. Given I have the following schema
```yaml
foo:
  allOf:
    - $ref: '#/components/schemas/bar.yml'
    - nullable: true
```
2. I expect the generated type for the `foo` key to be `Bar|null`

## What happens?

Generated type is only `Bar`

## What were you expecting to happen?

`Bar|null`

## Any logs, error output, etc?

n/a

## Any other comments?

n/a

## What versions are you using?

**Operating System:** …
**Package Version:** 6.25.0
**Browser Version:** …

**Comment by AffeJonsson** [comment]
The `nullable: true` should not be in the allOf list, but rather as a child to foo:
```yml
foo:
  nullable: true,
  allOf:
    - $ref: '#/components/schemas/bar-yml'
```
Which generates
```ts
export type Foo = Bar | null;
```

**Comment by melloware** [comment]
Thanks @AffeJonsson closing as workaround provided.
