### ISSUE TITLE
`target="es6"` or newer in `tsconfig.json` results in `Your mutator file doesn't have the default exported function`

### ISSUE THREAD

**Issue by younes0** [anymaniax/orval#1254]
## What are the steps to reproduce this issue?

1. … set `target="es6"` or newer  in `tsconfig.json`
2. … setup axios custom instance (mutator) 
3. … launch `orval` command

## What happens?

… get the message `Your mutator file doesn't have the default exported function`

## What were you expecting to happen?

… generate files

## Any other comments?

… if i set `target="es5"` in `tsconfig.json`, it works as expected

--------
```ts
// orval.config.ts
// -------------------------------
module.exports = {
  api: {
    input: {
      target: "http://localhost:4000/api-docs-json",
    },
    output: {
      target: "./api.ts",
      client: "react-query",
      schemas: "./schemas",
      override: {
        mutator: {
          path: "./axios-instance.ts",
        },
      },
    },
  },
};

// axios-instance.ts
// -------------------------------
import Axios from "axios";

import { apiHost } from "@/utils/env.utils";
import { useAuthStore } from "@/stores/auth.store";

const axiosInstance = Axios.create({ baseURL: apiHost });

axiosInstance.interceptors.request.use(
  // @ts-ignore
  async (config) => {
    const { jwtAccessToken } = useAuthStore.getState();

    return {
      ...config,
      headers: {
        ...config.headers,
        Authorization: `Bearer ${jwtAccessToken}`,
      },
    };
  },
  (error) => Promise.reject(error)
);

export default axiosInstance;
```

## What versions are you using?

**Operating System:** … ubuntu
**Package Version:** … latest
**Browser Version:** …

**Comment by melloware** [comment]
I am pretty sure its related to this issue: https://github.com/anymaniax/orval/issues/886

**Comment by melloware** [comment]
@younes0 i would subscribe to that other bug ticket as its the real issue here.
