### ISSUE TITLE
Is it possible to disable mock generation for a specific endpoint?

### ISSUE THREAD

**Issue by dogfootruler-kr** [anymaniax/orval#1258]
Hello,

I am wondering if it is possible to disable the mock generation for a specific endpoint only?

For example I would like that my `/login` endpoint point to my real one but mock the other ones.

Thank you very much!

**Comment by soartec-lab** [comment]
@dogfootruler-kr 

Unfortunately, at the moment, `orval` doesn't have that feature. So for example, a workaround is required, such as separating and controlling the generated functions with the `mode` option.
