### ISSUE TITLE
MSW: Incorrect return value generated for Blob mocks

### ISSUE THREAD

**Issue by Arnagos** [anymaniax/orval#1259]
## What are the steps to reproduce this issue?

1. Generate the MSW mocks for an endpoint that returns a blob, i.e. an image file

## What happens?
Orval generates `faker.word.sample();`, which is not assignable to type Blob

## What were you expecting to happen?
Orval generates proper mock data.

## Any logs, error output, etc?
![image](https://github.com/anymaniax/orval/assets/21961872/5a6902c1-f960-4577-996e-6dd3721d74a4)

![image](https://github.com/anymaniax/orval/assets/21961872/40b09121-1266-4854-9d79-8cf72d7438fc)

## Any other comments?
This did not happen with 6.23

## What versions are you using?
6.25

**Operating System:** Windows 11

**Comment by melloware** [comment]
@rmachado-studocu  want to submit a PR for this one as well?
