### ISSUE TITLE
PUT/DELETE/POST methods without body generates unused code when generating for SWR

### ISSUE THREAD

**Issue by AffeJonsson** [anymaniax/orval#1261]
## What are the steps to reproduce this issue?

1. Add a PUT method without body, e.g. api/profile/acceptTerms
2. Generate hooks for SWR client

## What happens?

Code generated has unused parameters.
```ts
export const getPutProfileAcceptTermsMutationFetcher = () => {
  return (_: string, { arg }: { arg: Arguments }): Promise<void> => {
                   //   ^ here is the unused parameter.
    return putProfileAcceptTerms();
  };
};
```

## What were you expecting to happen?

Unused code should not be generated

## Any other comments?

Here is the code adding this part of the generated code.
https://github.com/anymaniax/orval/blob/9c13f1f00bcffb5ff35febfdff8ed71647779e0f/packages/swr/src/index.ts#L698

## What versions are you using?
**Operating System:** Windows 11
**Package Version:** Orval version 6.25.0

**Comment by melloware** [comment]
PR is welcome?

**Comment by AffeJonsson** [comment]
I'll fix!
