### ISSUE TITLE
Implementing onSuccess in Orval-Generated Query Hooks Similar to Mutations (React-query)

### ISSUE THREAD

**Issue by Michal905** [anymaniax/orval#1264]
## What are the steps to reproduce this issue?

1. Use Orval to generate React Query hooks for API endpoints, creating both queries and mutations.
2. Implement an onSuccess callback within the mutation object in a mutation hook.
3. Try to find a similar way to implement onSuccess within the query object in a query hook

## What happens?

The onSuccess callback is straightforward to implement for mutations but not directly available or clear for queries.

## What were you expecting to happen?

Expected to find a straightforward method to implement onSuccess for queries within the query object, similar to the mutation object in mutations, to ensure consistent post-request handling.

## Any logs, error output, etc?

N/A

## Any other comments?

I'm seeking clarity on whether I've overlooked a feature or documentation that allows for onSuccess handling within the query object for Orval-generated query hooks, similar to mutations.

## What versions are you using?

**Package Version:** 6.23.0

**Comment by somfink** [comment]
I hope someone can help, I have same issue, and idk how to handle with

**Comment by mateuszSwies** [comment]
I have an identical problem, has anyone managed to find a solution?

@anymaniax @melloware

**Comment by melloware** [comment]
Can someone paste here more what you are expecting to be able to do?  Like paste a code snippet?

**Comment by Michal905** [comment]
For mutations, Orval allows us to easily specify onSuccess and onError callbacks, like so:
```
const { mutate, isLoading} = useValidateVerificationCode({
  mutation: {
    onSuccess: (data) => {
      // Logic to execute on successful mutation
    },
    onError: (error) => {
      // Logic to handle error
    },
  },
});
```

This is incredibly useful for handling post-request logic. However, I haven't found a way to achieve the same with queries. Here's an example of what I'm trying to accomplish with a query hook:
```
const {
  data,
  isLoading,
  isError
} = useGetMe({
  query: {
    // Looking to include onSuccess and onError callbacks here, similar to the mutation example above
  },
});
```

Since TanStack Query supports onSuccess and onError for queries, could Orval include this feature for query hooks too? It would make handling actions after queries as easy as with mutations.

**Comment by melloware** [comment]
I think your issue may be similar to this one: https://github.com/anymaniax/orval/issues/1177

**Comment by somfink** [comment]
I'm not sure about that, I want to use generated hook to get data from the backend. 
```ts
const { data, isLoading } = useToGetData(
    { queryParams1: value1, queryParams2: value2 },
    {
      query: {
        queryKey: [value1, value2],
      },
    }
  );
```
I want to execute some action `onSuccess`, or `onError` - for example display modal with success or error message.
In mutation when I want to achieve it - it's simple as a @Michal905 showed, but I've problem with found something similar in hook generated to get data

**Comment by somfink** [comment]
@anymaniax thanks God, you explain it. My colleague at work use v4 version in other project and I was losing my mind couldn't find that. I've believed there is some better way to handle it than `useEffect`, but now I'm wiser with this information, thanks a lot!

**Comment by Michal905** [comment]
Yeah, I missed that. Thank you for the clarification
