### ISSUE TITLE
[v5] Axios generator is broken.

### ISSUE THREAD

**Issue by Eddie-CooRo** [anymaniax/orval#128]
## What are the steps to reproduce this issue?
1. install orval@next
2. create *orval.config.js* with `output.client` set to axios
3. run orval

## What happens?
Orval generates the following broken code:
![image](https://user-images.githubusercontent.com/20463083/118029893-d7ed4d00-b379-11eb-9b3c-cbf67182c990.png)
[ts playground](https://www.typescriptlang.org/play?#code/PQKgsAUABCUOIFMB2CBOBDALggJlARgJ5QACAxqgLY4IBuAzsAPaq3oA2UtArAHQCMvAMwBaJgFdU9KIB4NwF77kGFAAiTKEiaYouAJZbK6JOI7tCvRbAQAPdJQAO7BCPppaOsggtQAojfuOoF1Z3T2hYAHk7ZABBAAUASUCosi40eh0mJAAuKEEABl48i2BIHXsWLXQrDPoAGigAbyho6qZ6ACUEAEdxBHpMAGFMgDMdAHMoAF8oYdQmSigAciqaxYBuUvLULUxCKMbFKAGAC0MxhABVIPoAZUwscXoAJjy82sOTs8vru4f6ACEmDhCO8INNZvMlrxgJQgQh2PR1pBINY7BUoGRMv0oOdML5bA4EDdXCEoABeKAACgAlOSAHxUhqHMinJDnK5pX6YR4AHmUWHQ5Kg4iQAGsNAB3JB0ymHKDCoLxHA5fqoHRs0Hy+Usr4cqRcx6A4E5T5s76c+7cgFAkFyqBMOyYDJIegAfhyLRqnR6fUGI3GmqgtKZ0C1qAQ3NQSCgKzavDR-T5Au0VmwSBw0hF4qYUqgrqOrPZP0tjxeeSgOX59xldvlAANgI80MB+n9gAASBpN1BKyZ1wNajGF836kvW4EDrUOp1YyfUjahyagybzyBAA)

## What were you expecting to happen?
Seemingly, the `<Data = unknown>` part cannot be parsed by typescript. Everything works perfectly fine if you remove the `= unknown` Though.
After searching for a while, It looks like there is really no way for having default value for generic  object literal methods.
Not only the notation we use, but neither of `{ method: <Data = unknown>() => {} }` nor `{ method: function<Data = unknown>() {} }` works.

## Solution
Multiple solutions comes to mind, but before anything, I'm failing to understand why the axios generator, unlike the others, generates the `getExampleService` function in the first place? Maybe it's a legacy thing we can fix while we are upgrading to v5? The problem wouldn't exist if the output was like the react-query one, only without the hooks.

But otherwise, doing the following can solve the issue:
![image](https://user-images.githubusercontent.com/20463083/118030810-03bd0280-b37b-11eb-9357-2c69f68c6f52.png)
[ts playground](https://www.typescriptlang.org/play?#code/PQKgsAUABCUOIFMB2CBOBDALggJlARgJ5QACAxqgLY4IBuAzsAPaq3oA2UtArAHQCMvAMwBaJgFdU9KIB4NwF77kGFAAiTKEiaYouAJZbK6JOI7tCvRbAQAPdJQAO7BCPppaOsggtQAojfuOoF1Z3T2hYAHk7ZABBAAUASUCosi40eh0mJAAuKEEABl48i2BIHXsWLXQrDPoAGigAbyho6qZ6ACUEAEdxBHpMAGFMgDMdAHMoAF8oYdQmSigAciqaxYBuUvLULUxCKMbFKAGAC0MxhABVIPoAZUwscXoAJjy82sOTs8vru4f6ACEmDhCO8INNZvMlrxgJQgQh2PR1pBINY7BUoGRMv0oOdML5bA4EDdXCEoABeKAACgAlOSAHwHaAzcRIMiYDJIDGnJDnK5pX6YR4AHmUWHQ5KgLIA1hoAO5IOmUw5QSVBeI4HL9VA6HmglUqsjc3k-e6CgFAwg5T4877802PQHAvX6ph2dlYgD8ORaNU6PT6gxG42dtIayqgqAQgtQnJWbV4aP6IrF2is2CQOGk0rlnI9RyNtqkAseLzyUByovuivDKoABsBHmhgP0-sAACQNRuodWTWvO-Vcr58ov281OmtQV3upB1cPUjZMyYLw6R6OcsNMg0F4e3UeHSaQJeQIA)

I'm still only somewhat familiar with the codebase, So I don't know how exactly we can split the definition and the export. But I believe the return value can easily be generated just by putting all of the function names together, separated with commas. 

## What versions are you using?
**Package Version:**v5.1.3

**Comment by anymaniax** [comment]
Wow! Nice catch I didn't saw the issue because I don't know why but when you have all options optional for the first function then typescript is happy 😭

**Comment by anymaniax** [comment]
And yes the global function is a legacy

**Comment by anymaniax** [comment]
I fixed the problem in `5.2.0` and added a new client named `axios-functions` which only generate the functions by operations
