### ISSUE TITLE
[Bug] OperationsOptions mock data should support array

### ISSUE THREAD

**Issue by wouterkroes** [anymaniax/orval#1282]
## What are the steps to reproduce this issue?

In `orval.config.ts` I pass in a method, that returns an array,  for a specific operations as mock data

Pseudo code

```ts
import { defineConfig } from 'orval';

type Product = {
  name: string
}

const getMockProducts = (): Product[] => [
  {
    name: 'product A'
  },
  {
    name: 'product B'
  }
]

export default defineConfig({
  Application: {
    output: {
      override: {
        operations: {
          GetContent: {
            mock: {
              data: getMockProducts,
            },
          },
        },
      },
    },
  },
});
```

## What happens?

The TypeScript compiler says `Index signature for type 'string' is missing in type 'Product[]'` in the `orval.config.ts`

## What were you expecting to happen?

No TypeScript compiler errors

## Any logs, error output, etc?

n/a

## Any other comments?

My guess would be to add `array` to [MockProperties](https://github.com/anymaniax/orval/blob/6e521b5cdd7e6a895d8a79c0f23901b3ce28a89c/packages/core/src/types.ts#L253).

If this is the right assumption, i am happily to create a pull request for this

## What versions are you using?

**Operating System:** Windows
**Package Version:** 6.25.0
**Browser Version:** N/A

**Comment by melloware** [comment]
Yes please submit a PR.

**Comment by wouterkroes** [comment]
here is the [PR](https://github.com/anymaniax/orval/pull/1283)
