### ISSUE TITLE
Custom mock function is not working

### ISSUE THREAD

**Issue by yuyueh** [anymaniax/orval#1293]
## What are the steps to reproduce this issue?

1. add mock function to orval.config.js
``` javascript
module.exports = {
    openapi: {
        output: {
            mock: myMockImplement
        },
        ...
    }
}
```

## What happens?

As my understanding, in orval.config.js, the output mock can be set not only with boolean but also with method to achieve custom mock functions. 
https://orval.dev/reference/configuration/output#mock
However, when actual methods are passed in, they cannot be executed, and the default msw program is still generated.
It seems to be caused by a conversion issue at line 99 of the packages/orval/src/utils/options.ts.
https://github.com/anymaniax/orval/blob/v6.26.0/packages/orval/src/utils/options.ts#L99

## What were you expecting to happen?

Custom mock function is working.

## Any logs, error output, etc?

…

## Any other comments?

…

## What versions are you using?

**Operating System:** …
**Package Version:** 6.26.0
**Browser Version:** …

**Comment by melloware** [comment]
@soartec-lab assigning to you look like he addresses the line number in question?

**Comment by soartec-lab** [comment]
> As my understanding, in orval.config.js, the output mock can be set not only with boolean but also with method to achieve custom mock functions.

Yes, As stated in the documentation, `output.mock` accepts `Function` and allows you to specify the mock builder. However, it seems like it hasn't been implemented as you said.

**Comment by soartec-lab** [comment]
@yuyueh 

The implementation is currently incomplete, but I have no plans to start on it at this time.
Is it okay to temporarily delete the entry of Function in the document description and close this issue?

I plan to reopen it when implementing the rest.

**Comment by yuyueh** [comment]
@soartec-lab ok sure, thanks a lot.

**Comment by soartec-lab** [comment]
@yuyueh 
Thank you. This issue will remain open until the document is fixed

**Comment by soartec-lab** [comment]
I looked into this issue a bit. Maybe it's a simple bug. We will consider including modifications to support `Function`
