### ISSUE TITLE
Add support to use Biome in addition to Prettier

### ISSUE THREAD

**Issue by oferitz** [anymaniax/orval#1298]
Hi, first of all, thanks for creating this tool; I really like it. In my new projects, I have moved to using [Biome.js](https://biomejs.dev/) instead of Prettier for both formatting and linting. Would you consider a PR that adds support to use Biome as the formatter?

**Comment by melloware** [comment]
I think if you submit a PR it would be considered. I know @soartec-lab has done a bunch of work recently to fix up Prettier so interested opinion.

**Comment by soartec-lab** [comment]
@oferitz 
It seemed like a really good idea. I'll consider it. You can also create your own PR. I gladly accept it.

**Comment by soartec-lab** [comment]
And I'm interested in this issue, so I've assigned it to me.

**Comment by oferitz** [comment]
@soartec-lab What would be the preferred approach in terms of configuration for this feature?
I had i mind the following options:
1. Side by side
```ts
// orval.config.ts
{
   prettier: boolean,
   biome: boolean
 } 
 ```
 Pros: backward compatible
 Cons: will have to add check that only one of them is used
 
 2. New `formatter` prop but backward compatible
 ```ts
// orval.config.ts
{
   prettier: boolean,
   formatter: 'prettier' | 'biome'
 } 
 ```
  Pros: backward compatible, unified configuration 
  Cons: will have to add check that only one of them is used
  
   2. New `formatter` prop breaking change
 ```ts
// orval.config.ts
{
   formatter: 'prettier' | 'biome'
 } 
 ```
  Pros: unified configuration, more elegant because no need for check
  Cons: breaking change

**Comment by soartec-lab** [comment]
@oferitz 

Thank you for your suggestion. I prefer pattern 1.
Because, it maintains compatibility and it is clear that it follows the format of the `prettier` option that originally existed.
Also, it is not necessarily the case that you can only set either `prettier` or `biome`. I think it's fine for users to do both if they wish.

**Comment by oferitz** [comment]
@soartec-lab 

Thanks for the feedback. I'm fine with pattern 1, but I don't see a use case for using both, as they both serve the same purpose. In most cases, one will simply override the other (depending on the order they appear in the code), which could lead to confusion.

**Comment by soartec-lab** [comment]
I agree with you that there are very few use cases to use both. But the point I'm making here is that there's no real negative impact if both are enabled.

**Comment by mortezakarimi** [comment]
@oferitz you can use following code to use custom formatter

```
    hooks: {
      afterAllFilesWrite: ['prettier --write --ignore-unknown'],
    },
```
for more info view following link https://orval.dev/reference/configuration/hooks#afterallfileswrite

**Comment by oferitz** [comment]
@mortezakarimi Nice! That's a perfect solution, no need for introducing new config. I'm closing this issue

**Comment by soartec-lab** [comment]
@oferitz 
Oh really. I'm sorry for not being able to tell you more.

@mortezakarimi 
Thank you for sharing.

However, I am expecting to add `Biome` as an option, so I will open this issue and assign it to me.

**Comment by oferitz** [comment]
@soartec-lab That's awesome! glad you are doing that, thanks.

**Comment by soartec-lab** [comment]
@oferitz 
 
`orval` will be able to use the `biome` option in the next version by #1321 👍
