### ISSUE TITLE
unable to generate a react-query with enabled condition

### ISSUE THREAD

**Issue by davidsonsns** [anymaniax/orval#130]
it isn't an issue. it's more a question

I tried many ways to generate a code like this:
`{ enabled: !!(version && petId), ...queryConfig },`

how can I configure my `orval.config.js` in order to generate a code like this?

I'm following this doc over here https://orval.dev/guides/react-query#how-use-other-query

**Comment by anymaniax** [comment]
I am not sure to understand you have an example [here](https://github.com/anymaniax/orval/blob/master/samples/react-app-with-react-query/orval.config.js)

**Comment by davidsonsns** [comment]
ohhh! my explanation was definitely confusing.
anyways, I saw that the [discussion tab](https://github.com/anymaniax/orval/discussions) is open. so, I'll move my question there!

thanks!
