### ISSUE TITLE
Zod: Support for OpenApi spec 3.1.0

### ISSUE THREAD

**Issue by marceloverdijk** [anymaniax/orval#1309]
E.g. defining a field like:
```
        breed:
          type: ['string', 'null']
          # type: string
          # nullable: true
```

which is OpenApi 3.1.0 compliant,
will generate :
`"breed": zod.string,null(),`

which does not compile.

In zod terms it should be generated as: `"breed": zod.string().nullable(),` 

which it does when using the OpenApi 3.0.x style as commented out.

**Comment by melloware** [comment]
cc @rmachado-studocu who has done some ZOD nullable work.

**Comment by marceloverdijk** [comment]
That was fast 🤩
