### ISSUE TITLE
Bug: incorrect import path generation

### ISSUE THREAD

**Issue by Boorj** [anymaniax/orval#132]
In `writers/SingleMode.ts` there's a part producing incorrect relative schemas path 
Code here https://github.com/anymaniax/orval/blob/master/src/core/writers/singleMode.ts#L43

```typescript
export const writeSingleMode = (...) {

// (1)
 const { path, dirname } = getFileInfo(
     join(workspace, targetedPath),
    camel(info.title),
  );

// (2)
const schemasPath = relative(dirname || '', output.schemas); // ←—— This line
```

## What are the steps to reproduce this issue?
1. setup output with relative parts:
```js
mode    : 'single',
target  : `../../openapi/orval-build/endpoints/openapi.ts`,
schemas : `../../openapi/orval-build/model`,
```
2. run build

## What happens?
`endpoints/openapi.ts` output file will get incorrect import path:
```
from '..\..\..\..\..\openapi\orval-build\model'
```

## What were you expecting to happen?
but expected to get `from '../model';`

## Any other comments?
So we are getting 2 problems: 
1) inverted slashes (OS separators could be straight or back slashes, but imports must not be backslash).
2) incorrect relative part.

# The solution.
1) Slashes direction could be easily solved by adding `.replace(/\\/g, '/');`
2) When using `relative(dirname || '', output.schemas);`, `dirname` is already absolute path, processed with `path.join` (`(1)`). But `output.schemas` is still dirty input from config file `(2)`. So the result is incorrect.
Fix could look this way:
```js
relative(dirname, join(workspace, output.schemas)).replace(/\\/g, '/');
```

---

### What versions are you using?
**Operating System:** Win10 
**Node** 14

**Comment by Boorj** [comment]
Btw, the same issue with slashes happens in project with relative paths in several places.
For example here: https://github.com/anymaniax/orval/blob/master/src/core/generators/mutator.ts#L13

**Comment by anymaniax** [comment]
Should be fixed with the `5.3.2`. Thanks for the issue 🎉

**Comment by Boorj** [comment]
@anymaniax 
btw, i will not create additional issue, but this line produces incorrect code if `definitions` is undefined

https://github.com/anymaniax/orval/blob/master/src/core/generators/react-query.ts#L82


```ts
// fails
<Data extends unknown ? ${  response.definition  } : Data>

// better
const typing = response.definition 
    ? "<Data extends unknown ? " + response.definition + " : Data>" 
    : '';
```

**Comment by anymaniax** [comment]
Can you do a pull request to fix it please?

**Comment by anymaniax** [comment]
And if response.definition is falsy the value should be Data to have the generic type

**Comment by anymaniax** [comment]
If you don't have time I will do it tomorrow

**Comment by Boorj** [comment]
Sure, PR is on the run) Sorry, timezones lag )
Probably in next versions you can make some functions to do those name extractions consistently.

**Comment by Boorj** [comment]
Done. Also i feel like project heavily needs some refactoring to keep DRY-principle and consistency. 
There's an utility here : https://github.com/anymaniax/orval/blob/master/src/utils/path.ts#L10 which provides safe relative path. I think that could be used consistently in all places. Also, all imports should be unified to correct slash, and it's missing in code, as i see (haven't check, how those utilities work).

**Comment by Boorj** [comment]
btw,
![image](https://user-images.githubusercontent.com/2145313/119254758-6d8ea500-bbe2-11eb-9783-90310342ded3.png)
i'm re-writing some code at my side.

**Comment by anymaniax** [comment]
Be careful, it seems that you are not up to date with master

**Comment by anymaniax** [comment]
But otherwise, it's a good idea

**Comment by anymaniax** [comment]
For the relativeSafe util, it's used everywhere normally in the v5

**Comment by anymaniax** [comment]
And please, if you do some refactoring try to do small pull request. Like that we can easily discuss it.

**Comment by Boorj** [comment]
Sure (about tiny commits). And indeed, version was obsolete, sorry

**Comment by Boorj** [comment]
@anymaniax  Also, Victor, some notes, non related
1. Library generates msw mocks based on faker, and then you can use them in browser  as service worker with interceptor. Also node js could use the same interceptor. Actually, i haven't seen libraries for nodejs+openapi that provide __customizable__ responses. Only based on type. `Orval` has at least regexp generator for customization. And, actually, that could be quite enough. 
How do you find next idea: generate mocks not as `import {rest} from 'msw';`, but to tweak output for use as configuration of `express`/`koa`/`hapi` server? You already have a parser, `express` uses almost the same signature.

2. Why don't you use templating? [this code](https://github.com/ferdikoomen/openapi-typescript-codegen/tree/master/src/templates) looks very neat.

**Comment by anymaniax** [comment]
@Boorj I already thought about it and it could be a really good feature. Maybe open a new issue first this one.

For point 2, this project is base on [restful-react](https://github.com/contiamo/restful-react) and he wasn't using templates. I also already thought about it but it's a big refactor. I maintain this in my free time and don't have a lot of time for this one. I always thought that there were more important changes to do than that one.

**Comment by anymaniax** [comment]
@Boorj  can we close this one?

**Comment by Boorj** [comment]
@anymaniax yeah, sure. `relativeSafe` with 'upath' does the job. Thank you!

**Comment by Boorj** [comment]
Opening again. Encountered error:
https://github.com/anymaniax/orval/blob/master/src/core/generators/api.ts#L17

![image](https://user-images.githubusercontent.com/2145313/119274752-aeff6e80-bc3b-11eb-8b29-92e248c56312.png)

Getting `specKey` with forward slashes, and specs object has key with filename, containing backslashes.

like 
```js
specKey === 'c:/path/foo.json'
specs === { 'c:\path\foo.json\': ...}
```

**Comment by Vylda** [comment]
well, v. 6.11.0 has the same problem

**Comment by anymaniax** [comment]
Hello @Vylda, I am currently on it. it's the same as this one #725

**Comment by anymaniax** [comment]
Hello @Vylda, can you try if `6.11.1-alpha.1` is working for you

**Comment by Vylda** [comment]
Hello @anymaniax ,
I cant run orval correctly:
`npx orval --config orval.config.ts
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
🍻 Start orval v6.11.1-alpha.1 - A swagger client generator for typescript
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "failed to load from C:/www/studentagency/orval.config.ts => TypeError: n is not a function".] {
  code: 'ERR_UNHANDLED_REJECTION'
}`

**Comment by anymaniax** [comment]
check here #725 did an other alpha version to fix that

**Comment by Vylda** [comment]
6.11.1-alpha.2 looks fine, thank you.
