### ISSUE TITLE
NonReadonly type incorrectly includes readonly fields

### ISSUE THREAD

**Issue by 052hide** [anymaniax/orval#1348]
## What are the steps to reproduce this issue?

1. Generate code using the provided OpenAPI schema and `orval.config.ts`.

<details>
<summary>`./sample/openapi.yml'`</summary>

```yml
---
openapi: 3.1.0
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  '/pets':
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '201':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/Pet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/Error'
  '/pets/{petId}':
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/Pet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/Error'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
```

</details>

<details>
<summary>`./orval.config.ts`</summary>

```ts
import { defineConfig } from 'orval'

export default defineConfig({
  api: {
    input: {
      target: './sample/openapi.yml',
    },
    output: {
      target: './sample/generated',
      client: 'react-query',
    },
  },
})
```

</details>

## What happens?

The NonReadonly<T> type incorrectly includes readonly fields as a required fields.

## What were you expecting to happen?

I expected the NonReadonly<T> type to exclude readonly fields, similar to the behavior in version 6.25.0.

## Any logs, error output, etc?

| v6.25.0 | v6.26.0 |
| --- | --- |
| ![image](https://github.com/anymaniax/orval/assets/51122255/a5fc5a3d-b67b-4835-a061-cd2b02900b92) | ![image](https://github.com/anymaniax/orval/assets/51122255/2f7c2f1d-348f-47b1-a054-ee8d5bb0458d) | 

## What versions are you using?

**Package Version:** v6.26.0

**Comment by melloware** [comment]
Similar to https://github.com/anymaniax/orval/issues/828

**Comment by melloware** [comment]
Also related: https://github.com/anymaniax/orval/issues/826

**Comment by tamanugi** [comment]
@melloware @052hide 
I think this bug related to https://github.com/anymaniax/orval/pull/1237.
That PR changed `NonReadonly` behavior.

It seems more appropriate for `NonReadonly` to remove `readonly` keys themselves, rather than just removing the `readonly` modifier.

Properties marked as readonly should not be included in the RequestBody 🤔 

https://swagger.io/docs/specification/data-models/data-types/#:~:text=Read%2DOnly%20and%20Write%2DOnly%20Properties

Thanks.

**Comment by melloware** [comment]
@ezequiel thoughts on this since you did the original fix?
