### ISSUE TITLE
Customize client generators

### ISSUE THREAD

**Issue by Boorj** [anymaniax/orval#135]
## Generators customization

I want to change the behavior of generator. For example, add some JSDoc generation. It will be huge and quite easy boost for whole library, if we do next way.

### 1 Create custom client object
```ts
  [OutputClient.REACT_QUERY]: {
    client: myCustomGeneratorHere, // <---- HERE
    msw: generateMSW,
    header: generateReactQueryHeader,
    dependencies: getReactQueryDependencies,
    footer: generateReactQueryFooter,
    title: generateReactQueryTitle,
  }, //...
```
### 2 Include that in project
Could be done in 2 ways
#### 2A 
tell program, that we want to use `customClientGeneratorFunc` here:
https://github.com/anymaniax/orval/blob/master/src/core/generators/client.ts#L177
```ts
const generator = GENERATOR_CLIENT[outputClient];
const client = generator.client(verbOption, options);
```
Custom client could be passed 
- as `override.client` property
- as `output.client` as function:
```js
  const generator = typeof outputClient === 'function' ? outputClient : GENERATOR_CLIENT[outputClient];
  // this should be done in all spots where GENERATOR_CLIENT is invoked.
```

#### 2B
Make `GENERATOR_CLIENT` a singleton, which could be mutated.

```js
// generators/client.ts
const GENERATOR_CLIENT = {...};

export function addGeneratorClient(key, obj) {
    GENERATOR_CLIENT[key] = obj;
}

// in orval.config.js 
import { addGeneratorClient } from 'orval';
addGeneratorClient('custom-query', {
  client : foo(){},
 // ...
});

export default {
   output: { client: 'custom-query' }
}
```

Of course that could be realized with class and private properties, anyway - idea was modifying global object with own generators.

## steps are
1. make this tiny code change
2. adopt change typings for new changes
3. update documentation

---

## Profit
Users can change main functions with their own just in few operations. It would be easy to change just one generator (i. e. `client`) and the rest ones (`msw`, `title`)  could be imported as is.

**Comment by Boorj** [comment]
Encountered a new issue. 
Goal is rewrite client generator. Previous versions allowed to change only some methods, but import utilities 
![image](https://user-images.githubusercontent.com/2145313/119304164-109df800-bc91-11eb-84d2-d818950b97d0.png)

And now library is distributed as a bundle and no options to import those deps. 
Only manually cloning them into your source.
So if i provide custom adopter (using that running with `ts-node`), ts-node runtime of course can't import anything with correct names in scope.
![image](https://user-images.githubusercontent.com/2145313/119304704-d8e38000-bc91-11eb-8dc3-932039b3659e.png)

**Comment by Boorj** [comment]
If generators will be provided as high-level adopters (in comparison with openapi-codegens), it could five a good flexibility.
For example, you can pass verb options to adopter, configure writer how to dump all data to files and voila - users can easily use templating to generate their own code snippets. I haven't seen a tool like this in openapi repos, so slightly modifying orval pipeline could make this library unique.
Here's a simple [video](https://www.youtube.com/watch?v=S8kmHtQeflo), where guy is showing simple example of manually creating express server with few dependencies to provide some mock data. This setup could be used, for example, to add adopter for nodejs express stub/mock server generator.

**Comment by anymaniax** [comment]
Hello @Boorj, it's a good idea to have multiple types of mock generator like with an express server because MSW is limited if you have a big API. You can maybe create an issue to add that to the project. But you already have packages which does that for example [prism](https://github.com/stoplightio/prism)
