### ISSUE TITLE
Run prettier on generated code.

### ISSUE THREAD

**Issue by Boorj** [anymaniax/orval#136]
Prettier is already imported. I see no disadvantages to use it for generated code. That will correct all ugly linebreaks produced

1. add `src/utils/formatter.ts`
```ts
import Prettier from 'prettier';
export function prettifyTypescript(data){
    return Prettier.format(data, {
        parser: 'typescript',
        "useTabs": false,
        "tabWidth": 4,
        "singleQuote": true,
        "semi": true,
        "printWidth": 100,
        "trailingComma": "all",
        "proseWrap": "never"
    });
}
```

2. apply `prettifyTypescript` in all writers before writing TS-code.

**Comment by anymaniax** [comment]
Prettier is use as dev dependency at the moment. That's a new feature that can be added but should be config in the orval config file. Also could be good to try to find a prettier config in the project and not only apply a custom config.

**Comment by Boorj** [comment]
Have some concerns about using hardcoded config instead of flexible user config. But as a default option - definitly. 

p.s. @anymaniax, btw have you checked https://openapi.tools ? Orval deserves to be in the list.

**Comment by anymaniax** [comment]
@Boorj I didn't know about https://openapi.tools could be interesting to add Orval there

**Comment by anymaniax** [comment]
@Boorj We should only use the hardcoded config when we cannot find the user config in its own project.

**Comment by melloware** [comment]
I am having trouble with this feature.  I have Orval and Prettier in my `devDependencies`

```json
        "orval": "^6.5.3",
        "prettier": "^2.5.1",
```

When I run `npm run codegen` i get this output..

⚠️  authorization - Prettier not found
🎉 authorization - Your OpenAPI spec has been converted into ready to use orval!

**Comment by anymaniax** [comment]
Probably because with [this](https://github.com/anymaniax/orval/blob/master/src/core/writers/specs.ts#L139) code it's only using the global installed prettier

**Comment by melloware** [comment]
hmmm i dont have prettier installed globally.

**Comment by anymaniax** [comment]
yep, it's a bug need to find a better solution for this

**Comment by c0m1t** [comment]
You can probably run prettier on `pre-commit` hook. Also, I made a pull request #459 which you can run a script (prettier, lint, etc...) when client is generated by `orval`.

**Comment by melloware** [comment]
This is easy too..

```JS

"scripts": {
		"format": "prettier --write \"{src,__tests__}/**/*.{ts,tsx}\"",
		"codegen": "orval && npm run format",
		"start": "react-app-rewired start"

```

**Comment by melloware** [comment]
@nimo23 this should be removed from the docs this has NEVER worked and the workarounds ARE the solution.  A PR removing this from the docs would be great!

**Comment by melloware** [comment]
@nimo23 its not gonna be fixed see the comment above it only works with Global Prettier.

> Probably because with [this](https://github.com/anymaniax/orval/blob/master/src/core/writers/specs.ts#L139) code it's only using the global installed prettier

So all the "workarounds" are actually the correct solution.

**Comment by melloware** [comment]
i think the doc should state "this only works with globally installed Prettier"
