### ISSUE TITLE
Zod: unstable/breaking variable names for validation lengths

### ISSUE THREAD

**Issue by Georgegriff** [anymaniax/orval#1363]
## What are the steps to reproduce this issue?

Have a schema which validation for mins and maxes, see that integers are added at the end of names

<img width="558" alt="image" src="https://github.com/anymaniax/orval/assets/9056958/66f7f4ad-67c4-4a29-b1b7-e83ed9a99e9a">

## What happens?

The values are already unique enough I would have thought we don't need these numbers appended to the end of the variables, it means it is quite annoying to consume these variables in the code because every time a new min/max is added to an api the variables change out from under you.

…

## What were you expecting to happen?

It is useful to use these variables for example a character counter on a field, it's nice if the backend defines these.

Stable variable names like the rest of the library

If they can't be stable for the whole file, at least stable for a given schema would be nice so if you add a new endpoint it doesn't change every other variable

…

## Any logs, error output, etc?

…

## Any other comments?

…

## What versions are you using?

**Operating System:** …
**Package Version:** …
**Browser Version:** …

**Comment by melloware** [comment]
@Georgegriff that was introduced because of this issue: https://github.com/anymaniax/orval/issues/1027

A PR to fix both your current scenario but not break #1027 would be great!

**Comment by Georgegriff** [comment]
I'll see what I can do, it might be tricky to fix without a breaking change if it results it people's Zod variables being renamed 🤔 an option wouldn't feel right. I'll explore it anyway and see what's possible

**Comment by melloware** [comment]
Maybe somehow you can detect whether its a matrix of values and add the numbers if not don't add the number?  I think I was just lazy and started at +1 etc to fix that issue.

**Comment by Georgegriff** [comment]
So i just did some digging, cloned the repo and was about to start then realised @anymaniax fixed my exact issue in https://github.com/anymaniax/orval/pull/1330 🥳 

I confirmed it by running the `yarn run generate:zod` and comparing the version i'm using:

6.27.1
<img width="591" alt="image" src="https://github.com/anymaniax/orval/assets/9056958/3b3a6f63-8606-4a09-901a-0533ba5c499b">
vs master
<img width="569" alt="image" src="https://github.com/anymaniax/orval/assets/9056958/501b060f-a5bb-4948-bb6c-d81260c3a726">


When do you expect this might be released? 

I note that @anymaniax mentioned this is a breaking change, i do tend to agree... however the original fix that introduced the unstable variable names was introduced in a 6.x minor version too and that too technical broke variable names, so maybe it doesn't matter.

**Comment by melloware** [comment]
Soon.. I will close this for now I marked it for 6.28.0

**Comment by Georgegriff** [comment]
Turns out i can't read git history.. it's already out in 6.28.2.

Just wanted to say thanks for this project, its great! Got my team out of apollo/graphql hell and back to shipping features, thanks to you and all the maintainers

**Comment by melloware** [comment]
Nice!
