### ISSUE TITLE
Type Issue: RegEx is not accepted in `defineConfig.[name].input.filters.tags`

### ISSUE THREAD

**Issue by vitalikda** [anymaniax/orval#1364]
I might be wrong here, due to Docs does not cover this. But looks like `filters.tags` excepts RegEx 
Have been added here: https://github.com/anymaniax/orval/pull/835

## What are the steps to reproduce this issue?

1. Add RegEx in `defienConfig.[name].input.filters.tags` 

## What happens?

Typescript shows error that only `string[]` is allowed 
Regex filter works 

## What were you expecting to happen?

No type error 

## Any logs, error output, etc?

Looks like defienConfig uses `InputOptions`: https://github.com/anymaniax/orval/blob/master/packages/core/src/types.ts#L200
But type was updated only in `NormalizedInputOptions`: https://github.com/anymaniax/orval/blob/master/packages/core/src/types.ts#L156

## What versions are you using?

**Package Version:** `orval@6.28.2`

**Comment by melloware** [comment]
Thanks to @AffeJonsson fixed for 6.29.0!
