### ISSUE TITLE
Zod: only generates 200 response bodies

### ISSUE THREAD

**Issue by Priddles** [anymaniax/orval#1380]
## What are the steps to reproduce this issue?

1. Use an input target with a path that has multiple responses.
<details>
<summary>Example</summary>

```yaml
paths:
  /foo:
    get:
      responses:
        "200":
          $ref: "#/components/responses/Success"
        "202":
          $ref: "#/components/responses/SuccessAsync"
        "400":
          $ref: "#/components/responses/Error"
```

</details>

2. Generate using Zod client.

## What happens?

Only one Zod schema for the 200 response body is generated.

## What were you expecting to happen?

Zod schemas for all possible responses to be generated.

## Any logs, error output, etc?

None.

## Any other comments?

Appears to be [hard-coded](https://github.com/anymaniax/orval/blob/master/packages/zod/src/index.ts#L646):
```ts
const response = spec?.[verb]?.responses?.['200'] as
```

## What versions are you using?

**Operating System:** MacOS 14.4.1
**Package Version:** 6.28.2
**Browser Version:** N/A

**Comment by melloware** [comment]
Similar to this issue: https://github.com/anymaniax/orval/issues/1280

**Comment by melloware** [comment]
Isn't this https://orval.dev/reference/configuration/output#generateeachhttpstatus

The setting to generate for each HTTP status?

**Comment by Priddles** [comment]
@melloware That is a config option for the mocks, and it does not affect zod generation.

**Comment by melloware** [comment]
Reopened i thought it did it for mocks and zod.  I see now its just mocks.

**Comment by melloware** [comment]
You are right the code is only doing 200

```js
const response = spec?.[verb]?.responses?.['200'] as
    | ResponseObject
    | ReferenceObject;
```

**Comment by melloware** [comment]
@Priddles is it just a matter of looping over the responses array and generating for each?

**Comment by Priddles** [comment]
> @Priddles is it just a matter of looping over the responses array and generating for each?

Yes, I'd say so.

Some level of deduplication would be good, but definitiely a nice-to-have.

**Comment by TommoLeedsy** [comment]
@melloware I have a fix for this locally and will put a PR in tomorrow.

**Comment by melloware** [comment]
Ok assigned the ticket to you.

**Comment by Priddles** [comment]
@melloware @TommoLeedsy Thanks for the quick turnaround!

I saw it got released so I tried it out, but having some issues. Wasn't sure whether to open a new issue or not so putting it here.

I have a minimal reproducible example [here](https://github.com/Priddles/orval-playground).

The issues are:
1. It seems to be reading the config from the [wrong object](https://github.com/Priddles/orval-playground/blob/main/orval.config.ts#L27).
2. It generates a lot of MSW and Faker related code that has nothing to do with Zod.

**Comment by melloware** [comment]
I would open a new ticket.

**Comment by TommoLeedsy** [comment]
@Priddles Sorry yeah that's my mistake, I didn't realise I needed to add a new config option and just used an existing one instead. I have now added `generateEachHttpStatus` to the `zod` options. This should sort it. I can put a PR in today?

**Comment by melloware** [comment]
Yes @TommoLeedsy PR would be great.

**Comment by Priddles** [comment]
@melloware Do you know when the fix might be released?

**Comment by melloware** [comment]
Let me find out

**Comment by Priddles** [comment]
Working in latest release. Thanks! 🎉
