### ISSUE TITLE
Zod: type string format date should be "YYYY-MM-DD"

### ISSUE THREAD

**Issue by RyoNkmr** [anymaniax/orval#1402]
refs. #971

## What are the steps to reproduce this issue?

1. Create a body field with type string and format date
2. generate schema using zod
3. generated date field as `zod.date()`

## What happens?

format date (`type: "string", format: "date"`) is [defined as "YYYY-MM-DD" formatted string in OpenAPI v3 spec](https://spec.openapis.org/registry/format/date)
in zod, `zod.string().date()` means that, but client generated `zod.date()`

## What were you expecting to happen?

`zod.string().date()` should be generated instead of `zod.date()`

# Any other comments?
respect to #971, `zod.date()` should be generated for **both `format: "date"` and `format: "date-time`** when`output.override.useDates` is true.

**Comment by melloware** [comment]
@RyoNkmr you are correct. Have you looked at the code and how difficult or easy it would be to change?

**Comment by TommoLeedsy** [comment]
@melloware I'm happy to have a go at fixing this issue.

**Comment by melloware** [comment]
Assignde to you @TommoLeedsy

**Comment by RyoNkmr** [comment]
@melloware sorry for late reply. I've already fixed locally but I've take a long time to run tests...
thank you @TommoLeedsy.

**Comment by TommoLeedsy** [comment]
@RyoNkmr Damn, Ive just finished the fix and was just about to PR it

**Comment by melloware** [comment]
@TommoLeedsy feel free to post your PR so @RyoNkmr can also review.  "Many eyes make all bugs shallow" - Torvalds

**Comment by TommoLeedsy** [comment]
@melloware and @RyoNkmr The PR for this fix in in, feel free to review and test.
