### ISSUE TITLE
how to use react query with fetch API instead of axios

### ISSUE THREAD

**Issue by borisyordanov** [anymaniax/orval#1418]
## What are the steps to reproduce this issue?

1. Generate a new client using output
```
     output: {
       client: 'react-query',
     },
```

## What happens?
The generated client uses `axios` as a dependency. 

![image](https://github.com/anymaniax/orval/assets/12392666/d73d8ea1-c221-4904-a616-5709120aaa47)

## What were you expecting to happen?

Requiring react-query as a dependency is valid but it's unclear why other packages are installed when not specified. I'd rather the native fetch API is used to keep bundle size smaller.

## Any logs, error output, etc?

…

## Any other comments?

Am I meant to create [a custom client](https://orval.dev/guides/custom-client) if I don't want axios to be used?

## What versions are you using?

**Operating System:** …
**Package Version:** 6.29.1
**Browser Version:** …

**Comment by melloware** [comment]
See: https://github.com/anymaniax/orval/pull/1353  @soartec-lab is working on this exact feature

**Comment by soartec-lab** [comment]
Yes, we plan to support it at a later.

> support fetch as http fetcher in the query client.

https://github.com/anymaniax/orval/issues/1387

**Comment by soartec-lab** [comment]
@borisyordanov 

This issue will be closed as it will be summarized in #1387. Thank you for making this :+1
