### ISSUE TITLE
React Query keys no longer exported?

### ISSUE THREAD

**Issue by melloware** [anymaniax/orval#1438]
### Discussed in https://github.com/anymaniax/orval/discussions/1436

<div type='discussions-op-text'>

<sup>Originally posted by **tlqvst** June  5, 2024</sup>
After updating from 6.24.0 to 6.29.1, all react query keys in the generated code are no longer exported. I couldn't find antything about this in the documentation, is there a way to enable this again? Or am I just misunderstanding how to handle query invalidations now? I often find myself needing the generated query keys.</div>

### Reproducer

Made a codesandbox
https://codesandbox.io/p/devbox/xy6ffl

Check the `getListPetsQueryKey` function in `pets.ts`, then remove the `override` section in `orval.config.cjs`, notice that `getListPetsQueryKey` is now being exported.

**Comment by melloware** [comment]
cc @tlqvst @mironbalcerzak

**Comment by anymaniax** [comment]
Should be fixed with the last one

**Comment by tlqvst** [comment]
It is indeed fixed in 6.30.2. Thanks!
