### ISSUE TITLE
File extension not applied to schemas generated files

### ISSUE THREAD

**Issue by MrLepage** [anymaniax/orval#1462]
## What are the steps to reproduce this issue?

Add a file extension like `fileExtension: '.gen.ts'` to the `output`.

## What happens?

The defined `fileExtension` is not applied to the schemas generated files.

## What were you expecting to happen?

I would expect the schemas generated files to have the defined `fileExtension`

## Any other comments?

Any reason why the `fileExtension` is not applied to schemas generated files?

I have defined an eslint glob pattern to ignore generated files '**/*.gen.*' that cannot be applied to generated schemas files.

**Comment by melloware** [comment]
This is a "good first issue" to investigate and fix.

**Comment by DanielVenable** [comment]
I could try to work on this. Can you assign me?

**Comment by melloware** [comment]
assigned to @DanielVenable

**Comment by DanielVenable** [comment]
I am not able to reproduce this bug. I tried adding `fileExtension: '.gen.ts'` to `output` and it worked fine.

**Comment by MrLepage** [comment]
In which mode?

**Comment by DanielVenable** [comment]
I see the bug now. I will work on fixing it.

**Comment by DanielVenable** [comment]
should the fileExtension be applied to index.ts?

**Comment by MrLepage** [comment]
I'd like to say yes, it's still a file, so it should have the file extension defined.
