### ISSUE TITLE
Use unknown instead of any for additional properties type

### ISSUE THREAD

**Issue by jmorel** [anymaniax/orval#1464]
## What are the steps to reproduce this issue?

Create an openapi spec with an object that has additionalProperties set to true:

```
EmptyObjectWithAdditionalProperties:
  type: object
  additionalProperties: true
```

## What happens?

The generated type will be 

```
export interface EmptyObjectWithAdditionalProperties {
    [key: string]: any;
}
```

## What were you expecting to happen?

I would have liked to have `unkown` instead of `any`:

```
export interface EmptyObjectWithAdditionalProperties {
    [key: string]: unknown;
}
```

Having `any` disables all type checks on these values, and since `any` propagates it can hide errors pretty far in the codebase that could have been caught otherwise. 

Having `unknown` forces the developer to handle all possible type cases. If they decide to then cast the values as `any` it's then their choice but by default they'll have a strictly typed codebase.

## Any logs, error output, etc?

…

## Any other comments?

We could make this configurable of course, but if not I have a small PR ready replacing the hardcoded `[key: string]: any` with `[key: string]: unknown`.

## What versions are you using?

**Operating System:** …
**Package Version:** v6.30.2
**Browser Version:** …

**Comment by ezequiel** [comment]
Totally agree with this change. `any` is too dangerous.

I think this is the correct file: https://github.com/anymaniax/orval/blob/master/packages/core/src/getters/object.ts

Simply replace all instances of `[key: string]: any` with `[key: string]: unknown`

**Comment by melloware** [comment]
PR is welcome.

**Comment by jmorel** [comment]
I opened https://github.com/anymaniax/orval/pull/1466

**Comment by jordan-rigo** [comment]
Is it configurable? Is there anyway I can override this in a mutator?
I dont like it that I have to cast the type

**Comment by ezequiel** [comment]
> Is it configurable? Is there anyway I can override this in a mutator? I dont like it that I have to cast the type

Not configurable. Asserting is a superior alternative because `any` will mask potential errors. 

Previously doing something like this was fine: `object.a.b.c`, but this was dangerous because none of those properties are typechecked given `object.a` was type `any`.

You must narrow the type or assert it. I usually prefer to go with what's simplest given the situation

Further reading: 
 - https://mariusschulz.com/blog/the-unknown-type-in-typescript#narrowing-the-unknown-type
 - https://mariusschulz.com/blog/the-unknown-type-in-typescript#using-type-assertions-with-unknown

**Comment by jordan-rigo** [comment]
Is it possible to override the input or write  a output.override.transformer for example? 
I'd like to narrow the unknown type at a higher level. Basically during the model creation, so the correct types are cast and not unkown.

@ezequiel
