### ISSUE TITLE
[v5] react-query mutator config type is not working

### ISSUE THREAD

**Issue by Eddie-CooRo** [anymaniax/orval#150]
## What are the steps to reproduce this issue?
1. Pass a custom mutator and build the project
2. Try to pass `request` config to any `useQuery` or `useMutation` calls.

## What happens?
The request config type is `Record<string, any>`

## What were you expecting to happen?
It should be the type that the fetcher accepts as its second parameter.

## Any logs, error output, etc?
[Code sandbox](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzEAXMALEMBc8AUYA9gHaICWA5rlMQJ4A08IAHijFAMInlXwDObMsQoBKanQDcAWABQslLQAOCAMrgSwAAqwoAW1RYAPABUmrEMWB98AOjuwKfcbRHwAvAD54NWl7fxTFhQLK3xZeHgiUkpnenDvGEdcIWQYeE04mVdPbzp4gH50s2DLawBXYgBrYkIAd2IC+AAldRhgQwEYIQpGHw943E0B+GIQADcsaTlphWV4AEF3eDUorR19YJhDWZBCRCRUDCwPKYigA)

## Any other comments?
[The axios generator](https://github.com/anymaniax/orval/blob/4acd3bc2de568766b1e945e38cc31ca1c28d1558/src/core/generators/axios.ts) doesn't have the `extends unknown` part. As everything in typescript extends unknown, [this part](https://github.com/anymaniax/orval/blob/4acd3bc2de568766b1e945e38cc31ca1c28d1558/src/core/generators/react-query.ts#L395) seems to be the cause of the issue in the `react-query` generator. AFAIK, removing it should be safe.

## What versions are you using?
**Package Version:** 5.3.2

**Comment by anymaniax** [comment]
Oh ok I see. I will test the pull request tomorrow

**Comment by anymaniax** [comment]
thanks! Merged 🎉
