### ISSUE TITLE
Range error when using nested $ref in schema.json

### ISSUE THREAD

**Issue by htc36** [anymaniax/orval#1500]
## What are the steps to reproduce this issue?

1. Use this  [schema.json](https://github.com/user-attachments/files/16085539/schema.json) with orval
2. Make sure ` "mock": true` is set in orval.config

## What happens?

` RangeError: Maximum call stack size exceeded`

This schema works fine up until version `6.21.0` so something has happened[ in there](https://github.com/anymaniax/orval/compare/v6.20.0...v6.21.0) to break it: 

Something to do with not handling the recursion properly and causing call stack error,

## What were you expecting to happen?

Generate as normal 

## Any logs, error output, etc?

Start orval v6.30.0 - A swagger client generator for typescript
🛑 test - RangeError: Maximum call stack size exceeded
    at Object.isReference (@orval/core/dist/index.js:43526:16)
    at Object.get [as isReference] (@orval/core/dist/index.js:22:45)
    at getMockObject (@orval/mock/dist/index.js:111:23)
    at getMockScalar (@orval/mock/dist/index.js:428:14)
    at resolveMockValue (@orval/mock/dist/index.js:497:21)
    at getMockScalar (@orval/mock/dist/index.js:344:11)
    at resolveMockValue (@orval/mock/dist/index.js:538:18)
    at @orval/mock/dist/index.js:172:29
    at Array.map (<anonymous>)
    at getMockObject (@orval/mock/dist/index.js:164:8)

## What versions are you using?

**Operating System:** Ubuntu 20.04.2
**Package Version:** 6.30.0

**Comment by MatthijsRademaker** [comment]
To add on this issue. What I've encountered is that the schema definition also influences the possible outcome.
For example, there is a circular reference within the schema "pet". Running orval against this spec.yml will result in the error described above.

```yaml
openapi: 3.0.0
info:
  title: Petstore API
  version: 1.0.0
paths:
  /pets:
    get:
      summary: List all pets
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'
components:
  schemas:
    pet:
      type: object
      properties:
        pet:
          $ref: '#/components/schemas/pet'
```

However, when you uppercase the schema object definition to "Pet" it will work fine:
```yaml
openapi: 3.0.0
info:
  title: Petstore API
  version: 1.0.0
paths:
  /pets:
    get:
      summary: List all pets
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet' # Note the uppercase
components:
  schemas:
    Pet: # Note the uppercase
      type: object
      properties:
        pet:
          $ref: '#/components/schemas/Pet' # Note the uppercase
``` 

I don't know if this is the only reason this is caused but hopefully it helps with finding the solution :)

**Comment by GMusk** [comment]
Thanks @MatthijsRademaker, that was really helpful in finding the issue!
