### ISSUE TITLE
Content-Type header with application/json should be assumed if there is a request body

### ISSUE THREAD

**Issue by RobbyUitbeijerse** [anymaniax/orval#1525]
Hello!

It feels very logical to us for a default `Content-Type': 'application/json'` header to be assumed if there are any `requestBodyParams`. Reasoning being that currently, in the fetch template, the body is provided through `JSON.stringify()`, but not all services accept the payload if you don't pass the header. I do realize these can simply be passed through options (either per request/global), but the default seems sensible.

Let me know how you feel about it, happy to provide a PR.

**Comment by melloware** [comment]
This seems reasonable to me. Please submit a PR

**Comment by soartec-lab** [comment]
@RobbyUitbeijerse 

The `fetch` client doesn't yet support cases other than `application/json`, such as `multipart/form-data` and `application/x-www-form-urlencoded` so i'll do this by following response.

https://github.com/anymaniax/orval/issues/1387#issuecomment-2241267130

I plan to add a header to the fetch client options when `content-type` is specifyed in `OpenAPI` so, i 'll fix this issue as well 👍
