### ISSUE TITLE
[issue] - same operationId won't generate outputs

### ISSUE THREAD

**Issue by davidsonsns** [anymaniax/orval#156]
## What are the steps to reproduce this issue?
1. create an input target that has operations with the same id
2. run your generate normally

ie.: 
1. add this code below into the `samples/react-app-with-react-query/petstore.yaml`
```
  /dogs:
    get:
      summary: List all dogs
      operationId: listPets 👈  it will cause the issue
      tags:
        - dogs
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

```
2. run orval
3. you won't see `dogs` outputs

## What happens?
Just noticed it, cause I have a huge `swagger.json` file that has many similar `operationId`. ie.: `getAll`, `getById`, ...

When the input target has operations with the same `operationId` being repeated many times, the output won't have all operations.

## What were you expecting to happen?
Generate all operations, even those with the same Id. 

## Any logs, error output, etc?
…

## Any other comments?
sent the pr: https://github.com/anymaniax/orval/pull/157
Which worked fine for me. But, noticed that it won't work for the modes `single` and `split`. Any thoughts?

## What versions are you using?
**Operating System:** macOS Big Sur 11.2.3
**Package Version:** 5.4.4
**Browser Version:** Google Chrome 91.0.4472.77

**Comment by anymaniax** [comment]
If you check [here](https://swagger.io/docs/specification/paths-and-operations/) normally the `operationId`should be a uniq string

**Comment by davidsonsns** [comment]
thanks for sharing it @anymaniax . didn't know that.
could be a good idea to provide a way to customize it with orval? wdyt?

btw i gonna keep my fork version in order to take advantage of orval on my project.

thanks for the lib bro!

**Comment by anymaniax** [comment]
You can override the operation with the config `operationName`but you will still have a problem with the generation. I will to fix that

**Comment by anymaniax** [comment]
I let you know when it's done

**Comment by davidsonsns** [comment]
> You can override the operation with the config `operationName` but you will still have a problem with the generation.

is it documented?

btw thanks for an answer so fast 😅

**Comment by anymaniax** [comment]
Sure you can check [here](https://orval.dev/reference/configuration/output#operationname)
