### ISSUE TITLE
required propety of schema ignored in models?

### ISSUE THREAD

**Issue by OliverDudgeon** [anymaniax/orval#161]
When I generate my orval from [my open API spec](https://squonk.informaticsmatters.org/data-manager-api/openapi.json), all the properties of the models are optional `?:`. This happens even when I use an input `transformer` to add the [required](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#schemaObject) property to the values of the schemas. 

Do I misunderstand this or is this a design decision? For me, the optional values are excessive.

## What are the steps to reproduce this issue?
1. Use the spec linked above with a minimal orval config

## What happens?
Check the models. E.g. 

```ts
export interface DatasetDetail {
  dataset_id?: string;
  editors?: string[];
  file_name?: string;
  format_extra_variables?: string;
  message?: string;
  owner?: string;
  projects?: string[];
  published?: string;
  source_ref?: string;
  type?: string;
}
```

All models are like this.

## What were you expecting to happen?
I'd prefer the types be required to avoid optional chaining where is isn't needed.

## Any logs, error output, etc?
None

## Any other comments?
This seems intentional so if I'm wanting something not advisable then why is that?

## What versions are you using?
**Operating System:** Ubuntu 20.04
**Package Version:** Orval 5.4.4
**Browser Version:** Firefox 88

**Comment by anymaniax** [comment]
Hello @OliverDudgeon, you need to put your property to required if you don't want them optional. If you used a transformer to automatically add required can I have the code to see what is the problem? But normally, if you adding required like [here](https://github.com/anymaniax/orval/blob/master/samples/react-app-with-react-query/petstore.yaml#L105) should solve your problem.

**Comment by OliverDudgeon** [comment]
Yeah I was transforming wrong. I was just setting `required` to `true` inside each property instead of an array of keys. The example helped a lot. 

Cheers!

**Comment by amirrezaDev1378** [comment]
Hi, I faced this issue recently and wrote this transformer for it:

```ts
transformer: (spec) => {
	if (!spec.components?.schemas) return spec;
	Object.keys(spec.components?.schemas).forEach((path) => {
		if (spec.components?.schemas?.[path] && "properties" in spec.components?.schemas?.[path]) {
			const model = spec.components?.schemas?.[path] as SchemaObject;
			if (!model.required) model.required = [];
			const properties = spec.components?.schemas?.[path]?.properties as SchemaObject["properties"];
			if (properties) {
				Object.keys(properties).forEach((key) => {
					const property = properties[key] as SchemaObject & { nullable?: boolean };
					if (property && !property.nullable) {
						model.required?.push(key);
					}
				});
			}
			// @ts-ignore open api 30 and 31 issues
			spec.components.schemas[path] = model;
		}
	});
	return spec;
},
```

You can use it if you like.
