### ISSUE TITLE
react-app and other example apps don't get data 

### ISSUE THREAD

**Issue by JPVan** [anymaniax/orval#173]
## What are the steps to reproduce this issue?
1. Go to ./samples/react-app
2. yarn
3. yarn start

## What happens?

The local server starts and a page loads with the Orval logo and "loading..." 

Loading never changes to a list of names, even with refreshing the page. 

## What were you expecting to happen?

I expected a list of names to show up under the Orval logo. 

## Any logs, error output, etc?

**Some minor compile time warnings that are pretty easy fixes, but even with those fixed the page doesn't ever show a list of names:** 

Compiled with warnings.
src/App.tsx
  Line 19:6:  React Hook useEffect has missing dependencies: 'dispatch' and 'listPets'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  Line 12:3:  'Pets' is defined but never used  @typescript-eslint/no-unused-vars
  Line 13:3:  'Pet' is defined but never used   @typescript-eslint/no-unused-vars

**Also, this in the browser console:** 

[HMR] Waiting for update signal from WDS...
index.js:156 [MSW] Mocking enabled.
mockServiceWorker.js:172 [MSW] Request handler function for "GET http://localhost:3000/v1/pets" has thrown the following exception:

TypeError: Cannot read property 'number' of undefined
(see more detailed error stack trace in the mocked response body)

This exception has been gracefully handled as a 500 response, however, it's strongly recommended to resolve this error.
If you wish to mock an error response, please refer to this guide: https://mswjs.io/docs/recipes/mocking-error-responses  
index.js:480 GET http://localhost:3000/v1/pets 500
createError.js:16 Uncaught (in promise) Error: Request failed with status code 500
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:62)

## Any other comments?

I have similar results with the other examples. The Svelte-query example is the only one I could find that works at least part of the time. 

I'd be happy to fix these and make a pull request if you point me in the right direction. Thanks! 

I think the example apps could use a short readme as well; maybe I could take a stab at that also. It would be nice to include details like the suggested way to switch between the mocked API and the real one. 

## What versions are you using?
**Operating System:** macOS 11.4
**Package Version:** 5.4.9
**Browser Version:** Chrome 91.0.4472.114 (Official Build) (x86_64)

**Comment by anymaniax** [comment]
fixed
