### ISSUE TITLE
The `customInstance` mutator example doesn't have second argument

### ISSUE THREAD

**Issue by fr3fou** [anymaniax/orval#176]
## What are the steps to reproduce this issue?
1. Generate react-query queries

## What happens?

The `customInstance` example provided in the documentation doesn't have a second argument, even though the queries generated do pass the argument onto it. Also the docs say that only angular clients get provided a second arg, this doesn't seem to be the case :thinking:

```ts
export const me = <TData = WebMeResponse>(
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<TData>(
    {
      url: `/me`,
      method: "get",
    },
    // eslint-disable-next-line
    // @ts-ignore
    options // <-- here
  )
```

![image](https://user-images.githubusercontent.com/1344906/123696668-a6b2d880-d864-11eb-9339-b079a8fe4720.png)

## What were you expecting to happen?
The `customInstance` example to have a second argument

## What versions are you using?
**Operating System:** macOS 11.4
**Package Version:** 5.4.9

**Comment by anymaniax** [comment]
it's currently a hack if you want to add a second argument to your mutator. It's my plan to improve this

**Comment by anymaniax** [comment]
Impoved with the `6.0.0`. You can try it now with `orval@next`

**Comment by anymaniax** [comment]
I close the issue leave me a comment if you have any problem
