### ISSUE TITLE
Remove axios import while using custom axios instance

### ISSUE THREAD

**Issue by danbalarin** [anymaniax/orval#177]
## What are the steps to reproduce this issue?
1. Have set output mutator
```js
module.exports = {
  api: {
    output: {
      mode: 'split',
      target: '../src/api/api.ts',
      override: {
        mutator: {
          path: '../src/axiosInstance.ts',
          name: 'axiosInstance',
        },
      },
    },
  },
};

```
2. Generate
3. Observe that generated file contains import of custom axios instance (correct) but also unused import of axios itself

## What happens?
There is unused axios import

## What were you expecting to happen?
Not to have unused axios import

### Head of generated file
```js
/*
 * Generated by orval v5.4.11 🍺
 * Do not edit manually.
 * REDACTED
 * Documentation for REDACTED
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'; // Unused import
import {
  useQuery,
  useMutation,
  UseQueryOptions,
  UseMutationOptions,
} from 'react-query';
import type {
  ProductLabel,
  FormResponseProductLabel,
  ProductLabelModelBody,
  ProductPart,
  FormResponseProductPart,
  ProductPartModelCreate,
  ProductPartModelUpdate,
  Product,
  GetProductsByVisibleUsingGETParams,
  FormResponseProduct,
  ProductModel,
} from './api.schemas';
import { axiosInstance } from '../axiosInstance';
```

## What versions are you using?
**Operating System:** macOS Big Sur 11.4 (20F71)
**Package Version:** 5.11.4

**Comment by anymaniax** [comment]
Should fix it if you rename your mutator and remove axios in the name. I need improve this

**Comment by melloware** [comment]
I just tested this with 6.6.1 and this does not happen so this ticket can be closed.
