### ISSUE TITLE
Allow directly passing an openapi spec JSON object instead of a filepath

### ISSUE THREAD

**Issue by rattrayalex** [anymaniax/orval#179]
Demo of what I'm trying to do is [in this gist](https://gist.github.com/rattrayalex/69f152a8736ada9b17821bc317b5b62b#file-generate-client-ts), but basically:

```ts
const oas = await app.swagger(); // json object
await orval({
  input: { document: oas },
  output: './myfile.ts',
});
```

This is useful with tools like `fastify-swagger` which can [return](https://github.com/fastify/fastify-swagger#swagger-function-options) the json document of a spec. 

Writing to and reading from disk slows things down in this scenario.

**Comment by anymaniax** [comment]
Really good idea and easy to do. I will do that this week

**Comment by anymaniax** [comment]
Added with the `6.0.0`. You can try it now with `orval@next`

**Comment by anymaniax** [comment]
I close the issue leave me a comment if you have any problem

**Comment by rattrayalex** [comment]
You bet, I'll try to try it soon!
