### ISSUE TITLE
Unconventional naming for referenced yml files in models

### ISSUE THREAD

**Issue by ayghon** [anymaniax/orval#183]
## What are the steps to reproduce this issue?
1. in you openapi yml file have references to other yml files for common schemas
2. run orval
3. a folder is created with a long name

## What happens?
the name of the folder containing the common models is too long: `ttps:--github.com-[org_name]-[repo_name]-blob-[branch_name]-api-doc-yaml-component-common`
(I replaced the actual name by `[text]`)

## What were you expecting to happen?
they should have a generic name `common` if no metadata is usable as a folder name

## Any logs, error output, etc?
N/A

## Any other comments?
N/A

## What versions are you using?
**Operating System:** macOs Big Sur v11.3.1
**Package Version:** v5.4.13
**Browser Version:** …

**Comment by anymaniax** [comment]
should be fixed in `5.4.14`
