### ISSUE TITLE
Same ref of query params creates multiple object

### ISSUE THREAD

**Issue by lisagherschon** [anymaniax/orval#188]
## What are the steps to reproduce this issue?
1. Create 2 endpoints
2. Add a query param "lang" as an object that contains an enum with EN - FR
3. Add this query param as ref into your 2 endpoints

## What happens?
After using orval, for each endpoint, Orval generates his own "params" file with the same object inside. It generates twice the same enum.

## What were you expecting to happen?
Only generate once the Language enum and refers it in the params file

## Any logs, error output, etc?
No error, just a bug.

## Any other comments?
/ 

## What versions are you using?
**Package Version:** v5.4.7

**Comment by anymaniax** [comment]
Added with the `6.0.0`. You can try it now with `orval@next`

**Comment by anymaniax** [comment]
I close the issue leave me a comment if you have any problem
