### ISSUE TITLE
[Support] Add suffix to generated models

### ISSUE THREAD

**Issue by jogelin** [anymaniax/orval#192]
In `openapi generator`, there is a possibility to add a suffix to generated models. For example, if I have a `Pet` shema in my yaml, it will generate a `PetDto` in typescript. 

This is really useful when we don't want to mix the `Dto` models exposed by the APIs with the frontend domain model.

This is not a bug but a validation of my implementation.

If I understood well, transformers could be used for that right?

`aff-suffix.js`
```javascript
const addSuffixToComponents = (inputSchema, suffix) => ({
  ...inputSchema,
  components: {
    ...inputSchema.components,
    schemas: Object.entries(inputSchema?.components?.schemas ?? {}).reduce(
      (acc, [schemaName, schemaSpec]) => ({
        ...acc,
        [`${schemaName}${suffix}`]: schemaSpec,
      }),
      {}
    ),
  },
});

const addSuffixToRefs = (obj, suffix) => {
  if (Array.isArray(obj)) {
    return obj.map((value) => addSuffixToRefs(value, suffix));
  } else if (typeof obj === 'object') {
    return Object.entries(obj).reduce(
      (acc, [key, value]) => ({
        ...acc,
        [key]: key === '$ref' ? `${value}${suffix}` : addSuffixToRefs(value, suffix),
      }),
      {}
    );
  }

  return obj;
};
```

Is it the way you would do it? If yes, you I can close the ticket, at least this ticket could be used as documentation ;)

**Comment by anymaniax** [comment]
At the moment, the transformer is the way to do it but add a suffix is a good idea I will add the feature in the next version

**Comment by anymaniax** [comment]
Added with the `6.0.0`. You can try it now with `orval@next`

**Comment by anymaniax** [comment]
I close the issue leave me a comment if you have any problem
