### ISSUE TITLE
Angular services should generated with the providedIn root scope 

### ISSUE THREAD

**Issue by jogelin** [anymaniax/orval#193]
In the current version, Angular services are generated without any scope:

![image](https://user-images.githubusercontent.com/954509/130211951-e92161d9-38d3-4ceb-9045-48daa656c96c.png)

This is forcing users to declare it in the root module the `providers` property.

Since Angular 6, the recommended way is to only declare services as a [singleton using providedIn](https://angular.io/guide/providers):

```javascript
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class UserService {
}
```

Would it be possible to generate services with this configuration by default? Or proposing a configuration to add it?

In my case, I have 25 API services and I don't want to add all of them in each related module :)

**Comment by anymaniax** [comment]
I will add it in the next version and it will be activated by default

**Comment by anymaniax** [comment]
I already did the development on the next will be in version 6. I will try to create a beta version soon

**Comment by anymaniax** [comment]
Added with the `6.0.0`. You can try it now with `orval@next`

**Comment by anymaniax** [comment]
I close the issue leave me a comment if you have any problem
