### ISSUE TITLE
Having a single index.ts entry point both for services and models

### ISSUE THREAD

**Issue by jogelin** [anymaniax/orval#194]
## For Now
Today, only the models are grouped into a single `index.ts`. In my case, I am creating a new `index.ts` at the root which is grouping models and services. 

## Expected
When using typescript path mapping, it is useful to have a single `index.ts` that could contain all generated code (schemas + services)

We could specify something like `import { PetsService, PetDto } from @orga/api-pet` per example.

## Problem
I understand that the current configuration is specifying 2 different paths for schemas and services (alias target). So it will be difficult to know where the `index.ts` should be generated.

It should be related to the mode selected.

**What do you think?**

**Comment by anymaniax** [comment]
You are not the first person which asks for I could easily add an index.ts for the services. I just need to check the better way to do it for each [mode](https://orval.dev/reference/configuration/output#mode)

**Comment by jogelin** [comment]
Correct, a mode oriented solution is better than what I proposed ;)

**Comment by anymaniax** [comment]
Added with the `6.0.0`. You can try it now with `orval@next`

**Comment by anymaniax** [comment]
I close the issue leave me a comment if you have any problem

**Comment by ClementLevesque** [comment]
@anymaniax thanks a lot for this library, I just discovered it and I already love it, nice job!

I don't manage to generate a single file pour model despite the version 6.0.0. Here is my config :

```javascript
export default defineConfig({
  ecom: {
    output: {
      mode: 'single',
      schemas: 'src/queries/models',
      client: 'react-query',
      mock: false,
      target: 'src/queries/api/types.ts',
      override: {
        mutator: {
          path: './src/common/services/fetchApi/client.ts',
          name: 'fetchClient',
        },
      },
    },
    input: {
      target: 'src/queries/schema.json',
    },
  },
});
```

it generated me one file per type in the models directory as I would expect a single file for all types. Exactly as for the types generated for custom hooks.

Is this an expected behavior or an additional feature ?

Thanks

**Comment by anymaniax** [comment]
Hi @ClementLevesque, you can just remove the schemas property for that and you will have one file with everything in it
