### ISSUE TITLE
Spaces (or other characters) in parameter names results in TypeScript Syntax Error

### ISSUE THREAD

**Issue by rattrayalex** [anymaniax/orval#200]
## What are the steps to reproduce this issue?

Have a schema with a parameter type like this, with a space in the name:
```json
{ "paths": { "/foo": { "get": {
  "parameters": [
      {
        "name": "My weird parameter name",
        "in": "query",
        "schema": { "type": "array", "items": {"type": "object'} }
      }
  ]
} } } } 
```

## What happens?
```ts
export type GetFooParams = { My weird parameter name?: GetFooMyWeirdParameterNameItem[] };
```

## What were you expecting to happen?
The object key needs to be quoted:
```ts
export type GetFooParams = { 'My weird parameter name'?: GetFooMyWeirdParameterNameItem[] };
```

## Any logs, error output, etc?
n/a

## Any other comments?

I acknowledge this should be rare for a parameter name, but the general case is that any character that can't be printed as an object key should be quoted (such as a dash).

One fairly simple way to accomplish this would be to quote all object keys everywhere, and run `prettier` over orval's output (which would remove unnecessary quotes, as well as generally being nicer).

## What versions are you using?
**Operating System:** …
**Package Version:** …
**Browser Version:** …

**Comment by anymaniax** [comment]
Fixed with `5.5.7`
