### ISSUE TITLE
Generated formData code skipped all falsey values for non-required properties

### ISSUE THREAD

**Issue by OliverDudgeon** [anymaniax/orval#202]
## What are the steps to reproduce this issue?
1. [For this openapi](https://squonk.informaticsmatters.org/data-manager-api/openapi.yaml)
2. Generated code for any formData with non-required fields only check the value is falsey but this should check for undefined only. 

## What happens?
- Requests made are missing any values like `0` or `false`

## What were you expecting to happen?
 - These values should be sent

## Any logs, error output, etc?
-

## Any other comments?
I've created a PR with a fix #203

**Comment by anymaniax** [comment]
Thanks for the pull request 🎉

**Comment by anymaniax** [comment]
Fixed with `5.5.8`

**Comment by OliverDudgeon** [comment]
I made a mistake sorry #204 204 should be correct now
