### ISSUE TITLE
TypeError: (m || []) is not iterable

### ISSUE THREAD

**Issue by sladg** [anymaniax/orval#207]
## What are the steps to reproduce this issue?
1. I download Openapi JSON schema.
2. I start orval on this schema.

## What happens?
I get `TypeError: (m || []) is not iterable` without any details.

## What were you expecting to happen?
I expect to either get a nicely generated schema or additional info about the error so I can check the validity of the schema.

## Any logs, error output, etc?
Openapi doc: https://www.codepile.net/pile/eRvQ8Nma

## What versions are you using?
**Operating System:** node 12
**Package Version:** Orval 5.5.10

**Comment by anymaniax** [comment]
Hello @sladg, the specification is not complete on codepile

**Comment by sladg** [comment]
> Hello @sladg, the specification is not complete on codepile

My bad! Did not expect codepile to have a limit on # of lines.

Sending as attachment
[docs.zip](https://github.com/anymaniax/orval/files/7163501/docs.zip)

**Comment by anymaniax** [comment]
You have a problem in your specification 
<img width="968" alt="Screenshot 2021-09-14 at 19 13 03" src="https://user-images.githubusercontent.com/10516382/133303277-cd586b1f-1e03-40e3-8b69-7ed114acb3d1.png">

I will check to improve the default validation to give a better error thanks

**Comment by anymaniax** [comment]
You should receive a feedback with the version `6.0.1`
