### ISSUE TITLE
Error with webpack aliases

### ISSUE THREAD

**Issue by MatthijsRademaker** [anymaniax/orval#216]
## What are the steps to reproduce this issue?
1. Go to the following repo: https://github.com/MatthijsRademaker/Orval-Webpack-alias-issue
2. Run orval on the test folder

## What happens?
Orval cannot find the module that is imported using an alias

## Any logs, error output, etc?
Error: Cannot find module '@test/test'

## Any other comments?
Orval was compatible with aliases in version 5.4.13

## What versions are you using?
**Package Version:** 6.1.1

**Comment by MatthijsRademaker** [comment]
Yes that would be fine

**Comment by anymaniax** [comment]
You can test it with the version `6.3.0` to have it you can just do `npm install orval@next`
