### ISSUE TITLE
localhost:PORT isn't recognized as a valid url

### ISSUE THREAD

**Issue by davidsonsns** [anymaniax/orval#219]
## What are the steps to reproduce this issue?
1. swagger spec being delivered at `http://localhost:6001/swagger/v1/swagger.json`
2. adds the target like below
3. try to run orval

```
...
input: {
      target: 'http://localhost:6001/swagger/v1/swagger.json',
...
```

## What happens?
[validator.js](https://github.com/validatorjs/validator.js) doesn't recognize `localhost:${PORT}` as a valid URL and ORVAL concatenates it with the current path and throws the exception below:

```
ResolverError: Error opening file "/Users/myusername/myprojectfolder/http:/localhost:6001/swagger/v1/swagger.json"
ENOENT: no such file or directory, open '/Users/myusername/myprojectfolder/http:/localhost:6001/swagger/v1/swagger.json'
error Command failed with exit code 1.
```

## What were you expecting to happen?
recognize `localhost` as a valid URL

## Any other comments?
found a couple of PR opened on validator.js repository regarding this behavior: https://github.com/validatorjs/validator.js/issues?q=isurl+localhost
so, my guess is that we could improve it [`if (isString(path) && !isUrl(path)) { `](https://github.com/anymaniax/orval/blob/master/src/utils/options.ts#L196) to `if (isString(path) && !isUrl(path, { require_tld: false })) {`

## What versions are you using?
**Operating System:** macOS Big Sur Version 11.6
**Package Version:** `^6.1.1`
**Browser Version:** …

**Comment by anymaniax** [comment]
@davidsonsns nice investigation. Do you open a pull request for that changes?

**Comment by davidsonsns** [comment]
@anymaniax I was opening rn 😅

**Comment by sdindu** [comment]
> @anymaniax I was opening rn 😅 plz let me know ur thots

I am still getting this error today   api - Error: ENOENT: no such file or directory, open 'C:\Users\xxx\source\repos\ABC\Sample\src\ABC.Sample.ClientApp\https:\localhost:7108\swagger\v1\swagger.json'

**Comment by melloware** [comment]
I have updated this again and I think it fixes all scenarios: https://github.com/anymaniax/orval/pull/1032

**Comment by Choco-milk-for-u** [comment]
+1 still have this error

**Comment by FranjoMindek** [comment]
This appeared for me on a new project, tried versions ~7, ~7.1, ~7.2, ~7.3, and latest (^7.4.1).

Both cases are treated as filepath:
```
target: "http://localhost:5175/openapi/v1.json"
target: "https://localhost:7079/openapi/v1.json"
```

**Comment by melloware** [comment]
We have an integration test it probably needs to be updated?

```js
describe('assertion testing', () => {
  it('check for valid URLs', () => {
    expect(isUrl('http://my-docker-service/docs.json')).toBeTruthy();
    expect(isUrl('https://www.example.com')).toBeTruthy();
    expect(isUrl('http://localhost:8080/docs/spec.yaml')).toBeTruthy();
    expect(isUrl('http://localhost/test.json')).toBeTruthy();
    expect(isUrl('http://localhost:6001/swagger/v1/swagger.json')).toBeTruthy();
    expect(isUrl('D:/a/test.txt')).toBeFalsy();
    expect(isUrl('./file.txt')).toBeFalsy();
  });
});
```

**Comment by mavduck** [comment]
this is also broken for me, anybody found a workaround?

**Comment by FranjoMindek** [comment]
I generate json from my specification on server build time. Then I point my orval to the local file. If this works for you depends on your project structure and needs.

**Comment by Guillaume2206** [comment]
I just came across this issue. Have you found any solution yet ?

`...
input: {
      target: 'https://localhost:7250/swagger/v1/swagger.json',
    },
...`


`
🛑 my-incredible-project - Error: ENOENT: no such file or directory, open 'C:\path\to\my\repo\My-Incredible-Project-Airsoft\my-incredible-project.client\https:\localhost:7250\swagger\v1\swagger.json'
`

**Comment by melloware** [comment]
@Guillaume2206 for now maybe run a `curl` command to download `https://localhost:7250/swagger/v1/swagger.json` before Orval runs?

**Comment by Guillaume2206** [comment]
I found a post on stackoverflow that solved my problem.

I'm working with a .Net 9 API, I added an extension method to my middleware. It's called during the compilation to download the file from the Swagger source.

https://stackoverflow.com/a/77170880/11399733
```
using Microsoft.OpenApi.Extensions;
using Swashbuckle.AspNetCore.Swagger;

public static class SwaggerExtensions
{
    public static void SaveSwaggerJson(this IServiceProvider provider)
    {
        ISwaggerProvider sw = provider.GetRequiredService<ISwaggerProvider>();
        OpenApiDocument doc = sw.GetSwagger("v1", null, "/");
        string swaggerFile = doc.SerializeAsJson(Microsoft.OpenApi.OpenApiSpecVersion.OpenApi3_0);
        File.WriteAllText("swaggerfile.json", swaggerFile);
    }
}
```

Then I changed the target in the input to use the downloaded file.

```
input: {
      target: '../My-Incredible-Project.Server/swaggerfile.json',
    },
```

It works fine now :)

**Comment by melloware** [comment]
Excellent thanks for posting back!

**Comment by mavduck** [comment]
Here was my solution:
.NET 9 project using native Microsoft.AspNetCore.OpenApi package for openapi generation on build

Then followed instructions [here ](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?view=aspnetcore-9.0&tabs=visual-studio%2Cvisual-studio-code#modifying-the-output-directory-of-the-generated-open-api-file) to set location of generated openapi.json file

Then I call the orval command on project build as well

My api project file:
```
<PropertyGroup>
        <OpenApiDocumentsDirectory>.</OpenApiDocumentsDirectory>
        <OpenApiGenerateDocumentsOptions>--file-name openapi</OpenApiGenerateDocumentsOptions>
</PropertyGroup>
<Target Name="GenerateOpenAPI-TS" AfterTargets="Build">
	<Exec Command="npx orval --config orval.config.ts" WorkingDirectory="../{project}.client" />
</Target>
```

My orval.config.ts in {project}.client
```
input: {
    target: '../{project}.server/openapi.json'
},
```

**Comment by Guillaume2206** [comment]
I tried you solution but unfortunetly it's not working for me. I'm already using Swagger and it looks like both assemblies on a same project is not a great idea. The OpenAPI documentation is visible in /openapi/v1.json, same as Swagger. I updated my csproj to generate the file but the generation feature seems not working when SwagerGen is also declared in the builder container...

**Comment by mavduck** [comment]
I can't say I've tried to use them together, but I've read that Swashbuckle is [being removed in .NET 9](https://github.com/dotnet/aspnetcore/issues/54599), I replaced it in favor of native support when I upgraded.

**Comment by Guillaume2206** [comment]
I wasn't aware of that. It change the view I had on my project. So I only kept SwaggerUi and I mapped the OpenAPI documentation on it. I'm always struggling to have the openapi.json file generated... I'm going to search why or find a workaround.

Thx for this information !

**Comment by Guillaume2206** [comment]
To someone trying to use SwaggerUI mapped on OpenAPI documentation. Be careful to **only install SwaggerUI** (Swashbuckle.AspNetCore.SwaggerUI) and not the entire Swashbuckle.AspNetCore assembly as Swashbuckle.AspNetCore.SwaggerGen contain in it will block Microsoft.Extensions.ApiDescription.Server from generating OpenAPI file !

Thx @mavduck for your help, everything is working now
