### ISSUE TITLE
Introduce a constraint to response type or remove generic option for react-query

### ISSUE THREAD

**Issue by Krisztiaan** [anymaniax/orval#222]
We've ran into an issue where passing a callback to `onSuccess` changed the expected data type for a certain query, making Typescript ignore an incompatibility error (the actual data returned by the query had a different format than the other query where we tried to `setQueryData`, and it turned some values to `undefined`.

Our fix involved creating a patch where instead of just doing
```jsx
<TData = AsyncReturnType<typeof ${t},${d}>
```
we're now doing
```
<TData extends AsyncReturnType<typeof ${t},${d}> = AsyncReturnType<typeof ${t},${d}>
```

See:
https://github.com/anymaniax/orval/blob/b42fd8237fc47f1d75ef2d653b6e0b1db4bcbd3b/src/core/generators/query.ts#L327

**Comment by anymaniax** [comment]
Hello @Krisztiaan, which version did you use because I fixed some types issues in one of the last version

**Comment by Krisztiaan** [comment]
This won't be resolved, because the generics will change based on the actual generated query usage. Without constraints, it can change to anything. Tbh, it probably does not make much sense to have generics for this anyways, since the response type is not going to change.
