### ISSUE TITLE
Ability to use a ClientProvider for orval, rather than the global 'axios' scope, or mutators

### ISSUE THREAD

**Issue by arlyon** [anymaniax/orval#233]
Hi!

I am using next-auth to handle authorization which I have configured to provide a token that can be used to make authenticated requests. This token is provided via a hook, so I set the authorization headers for the global axios instance like so:

```typescript
import axios from "axios";
import { useSession } from "next-auth/react";
import React, { FC, useEffect, useMemo } from "react";
import { QueryClient, QueryClientProvider } from "react-query";

export const Providers: FC = ({ children }) => {
  const session = useSession();
  const token = session.data?.apiToken;

  const queryClient = useMemo(() => new QueryClient(), []);

  useEffect(() => {
    axios.defaults.headers = token ? { Authorization: `Bearer ${token}` } : {};
  }, [token]);

  return (
    <QueryClientProvider client={queryClient}>
      {children}
    </QueryClientProvider>
  );
};
```

However, it would be nice to be able to use an axios instance and dynamically provide it to `orval` via a provider, rather than updating the global instance. A mutator wouldn't work here as it relies on dynamic state from the react tree. Thoughts?

**Comment by arlyon** [comment]
Yes, essentially, it would be nice to be able to get access to dynamic react state when specifying a custom client whether that be via a provider or otherwise.

**Comment by anymaniax** [comment]
Something like [this](https://gist.github.com/anymaniax/e0f39a6732d41348b3398b66f201172e) would be ok? I didn't found any other good solution. I would check if the mutator start with `use` and return a function to generate it that way directly with the client `react-query`

**Comment by anymaniax** [comment]
You can test it with the version `6.3.0` to have it you can just do `npm install orval@next`
