### ISSUE TITLE
react-query data generic type "any"

### ISSUE THREAD

**Issue by gunnartorfis** [anymaniax/orval#241]
## What are the steps to reproduce this issue?
1. Generate orval client using react-query as client
2. I'm using single mode

## What happens?
data property from wrapped useQuery is always "any". 

## What were you expecting to happen?
It should be of type specified in the generic. 
…

## Any logs, error output, etc?
<img width="345" alt="Screenshot 2021-10-29 at 13 26 40" src="https://user-images.githubusercontent.com/5333875/139443287-458b79c7-2bbf-41bf-a9ae-d985b0b42452.png">

<img width="972" alt="Screenshot 2021-10-29 at 13 26 57" src="https://user-images.githubusercontent.com/5333875/139443321-163e7eed-e8ce-4fac-b847-8d50bd2e125f.png">

## Any other comments?
Might be because of some "| undefined" definitions.

## What versions are you using?
**Operating System: macOS Big Sur** …
**Package Version: orval/6.2.3 darwin-x64 node-v16.13.0 ** …
**Browser Version: Using React Native ** …

**Comment by makotot** [comment]
I had the same problem, and installing npm modules such as axios, faker or msw solved it.
I thought that if you check the generated schema files and find npm modules that are imported but not installed, you might be able to solve the problem in a same way.
I'm not sure if these npm modules are dependent libraries of orval or if they are only needed when using react-query.

**Comment by gunnartorfis** [comment]
That was super helpful. I got it working in the end.
I'm publishing this as an NPM package that was causing me some headaches since I'm new to the publishing part (defining types, main, etc).

**Comment by anymaniax** [comment]
Top! @makotot thanks for the help here
