### ISSUE TITLE
Specs where urls end with slashes are not generated appropriately

### ISSUE THREAD

**Issue by kelvinndmo** [anymaniax/orval#246]
## What are the steps to reproduce this issue?
1. Use a url with appending slash/schema.
```
i.e api/v1/users/me/
```

## What happens?
2. The generated  files and queries will not have the slash appended to the end

## What were you expecting to happen?
Generating with the ending slashes, 

## What versions are you using?
**Operating System:**MacOs
**Package Version:** 6.2.4

**Comment by anymaniax** [comment]
will be fixed with the next version

**Comment by anymaniax** [comment]
Should be fixed with `6.4.0` can you test when you have time, please?

**Comment by kelvinndmo** [comment]
This now works Thanks @anymaniax
