### ISSUE TITLE
Delete body not generated in 

### ISSUE THREAD

**Issue by RichardLindhout** [anymaniax/orval#254]
## What happens?
The generator does not send the data from the param in the delete function to the body

```tsx
export const deleteCartArticleById = (
  id: number,
  productDeleteDto: ProductDeleteDto
) => {
  return queryApi<CartDto>({ url: `/cart/article/${id}`, method: "delete" });
};
```

## What were you expecting to happen?
```tsx
export const deleteCartArticleById = (
  id: number,
  productDeleteDto: ProductDeleteDto
) => {
  return queryApi<CartDto>({ url: `/cart/article/${id}`, method: "delete", data: productDeleteDto });
};
```

## Any logs, error output, etc?
No

## Any other comments?
…

## What versions are you using?
**Operating System:** OSX
**Package Version:** Latest
**Browser Version:* Not relevant

**Comment by anymaniax** [comment]
Hello @RichardLindhout, I think using a body with a delete method is not recommended and that's why it's not there. But there is no real rule of that other there. I will check to add it then 😀

**Comment by anymaniax** [comment]
Should be fixed with `6.4.0` can you test when you have time, please?

**Comment by anymaniax** [comment]
Closing this issue since it's normally fixed. Don't hesitate if you have any problem

**Comment by RichardLindhout** [comment]
Thank you!
