### ISSUE TITLE
Generated mocks are using wildcard

### ISSUE THREAD

**Issue by lefeverd** [anymaniax/orval#256]
## What are the steps to reproduce this issue?
1. Generate client code with `mock: true`

## What happens?
The generated mocks are using wildcards, such as `rest.get('*/categories', ...)`, for instance :

```
**
 * Generated by orval v6.2.3 🍺
 * Do not edit manually.
 * SimpleBookmarks API
 * SimpleBookmarks backend API
 * OpenAPI spec version: 0.1
 */
import {
  rest
} from 'msw'
import faker from 'faker'
import type {
  Category
} from '.././model'

(...)

export const getCategoriesMSW = () => [
rest.get('*/categories', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),

(...)
```

In my application, I want to have a page /categories, but msw intercepts the request and I get an error :

```
Uncaught SyntaxError: unexpected token: ':'
```

I guess because it returns the mocked JSON.

## What were you expecting to happen?
Not sure, maybe being able to define a base URL for the mocks ?

## What versions are you using?
**Operating System:** Linux 5.14.16-301.fc35.x86_64
**Package Version:** orval v6.2.3
**Browser Version:** Firefox 94.0 (64-bit)

**Comment by anymaniax** [comment]
Hello @lefeverd, you can already define a base url like [this](https://orval.dev/reference/configuration/output#baseurl)

**Comment by lefeverd** [comment]
Thank you @anymaniax, it was right in front of me !
Sorry for the issue, thanks for the good work.
