### ISSUE TITLE
How to override react-query Error generic?

### ISSUE THREAD

**Issue by OliverDudgeon** [anymaniax/orval#258]
## What are the steps to reproduce this issue?
1. Use [my openapi.yaml](https://squonk.informaticsmatters.org/data-manager-api/openapi.yaml)
2. On a `react-query` client with a custom instance using `axios` (e.g. the one used in the docs).

## What happens?
The generated hooks have these generic types `<TData = AsyncReturnType<typeof downloadDataset>, TError = Error>` where `Error` is the interface generated by Orval.

However since we're using Axios the Error type is actually `AxiosError<Error>`. Is there currently anyway to override this?

## What versions are you using?
**Operating System:** Ubuntu 20.04
**Package Version:** 6.3.0

**Comment by OliverDudgeon** [comment]
My suggestion here would be to optionally expect a generic type export `ErrorType` from the `custom-instance` that is a generic type. 

```ts
export type ErrorType = AxiosError
```

If this is specified, Orval can then use this with the OpenAPI defined `Error` as the type parameter.

**Comment by anymaniax** [comment]
Hi @OliverDudgeon, interesting idea I need to check a bit more how I can add something like that

**Comment by anymaniax** [comment]
Hi @OliverDudgeon, It's a bug the AxiosError should be used as a return type. Will try to fix that for the next version.

**Comment by anymaniax** [comment]
I also added the new feature 🎉. Thanks for the idea

**Comment by anymaniax** [comment]
Should be fixed with `6.4.0` can you test when you have time, please?

**Comment by OliverDudgeon** [comment]
Seems to work correctly, thanks!! I Will reopen if I run into any issues.

**Comment by OliverDudgeon** [comment]
@anymaniax why is the error type a Union of the ErrorType, void and undefined?

**Comment by anymaniax** [comment]
@OliverDudgeon depend of your specification normally. Do you have an example?

**Comment by OliverDudgeon** [comment]
> @OliverDudgeon depend of your specification normally. Do you have an example?

The one provided at the start of this issue should work
