### ISSUE TITLE
service code is not generated when paths are $refs

### ISSUE THREAD

**Issue by Talor-A** [anymaniax/orval#261]
## What are the steps to reproduce this issue?
1. set the value of a `path` to `$ref`
2. run generate command
3. models are generated but hooks and services are not.

## What happens?
orval generate command finishes successfully. however the generated files only contain models, no mocks, services, hooks, etc.

## What were you expecting to happen?
all code should be generated.

## Any logs, error output, etc?
File A (petstore.yaml):
```yaml
openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    $ref: "services/pets.yaml#/paths/~1pets"
  /pets/{petId}:
    $ref: "services/pets.yaml#/paths/~1pets-petId"
```

File B (services/pets.yaml):
```yaml
openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - 'name'
                - 'tag'
              properties:
                name:
                  type: string
                tag:
                  type: string
      responses:
        '200':
          description: Created Pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pets-petId:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
        - name: testId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        '@id':
          type: string
          format: iri-reference
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
        email:
          type: string
          format: email
        callingCode:
          type: string
          enum: ['+33', '+420', '+33'] # intentional duplicated value
        country:
          type: string
          enum: ["People's Republic of China", 'Uruguay']
    Pets:
      type: array
      items:
        $ref: '#/components/schemas/Pet'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

## Any other comments?
I discovered this while implementing #260 , turns out there were two similar issues related to refs that I uncovered in my schema.

## What versions are you using?
**Operating System**: MacOS Big Sur 11.6.1
**Package Version**: 6.3.0 (latest at time of writing)
**Browser Version**: n/a

**Comment by anymaniax** [comment]
Will be fix in the next version

**Comment by anymaniax** [comment]
Should be fixed with `6.4.0` can you test when you have time, please?

**Comment by anymaniax** [comment]
Closing this issue since it's normally fixed. Don't hesitate if you have any problem

**Comment by ravikiranr26** [comment]
@anymaniax Hello, seems like it's started not to generate when we have $ref and containing file is Enum.

Version: 
orval v6.10.3 
node: 16.14.2
openapi: "3.0.0"

schema.yaml:
openapi: "3.0.0"
servers:
  - url: http://localhost/api/rest
info:
  version: 1.11
  title: API
paths:
  /data/acc/search:
    $ref: "paths/acc-search.yaml"
components:
  schemas:
    ApiAccount:
      $ref: "schemas/api-account.yaml"
    ApiAccountEntityEnum:
      $ref: "schemas/enums/api-account-entity-enum.yaml"

acc-search.yaml:
post:
  summary: accounts
  operationId: sAccounts
  responses:
    "200":
      description: Ok
      content:
        application/json:
          schema:
            $ref: "../schema.yaml#/components/schemas/ApiAccount"

api-account.yaml:
properties:
  id:
    type: string
  entity:
    $ref: "enums/api-account-entity-enum.yaml"

api-account-entity-enum.yaml:
type: string
enum:
  - XC
  - OK

orval.config.js: 
module.exports = {
    api: {
        input: {
            target: 'openapi/schema.yaml',
        },
        output: {
            mode: 'split',
            target: './libs/msx/orval-data/generated/api/DefaultApi.ts',
            schemas: './libs/msx/orval-data/generated/model',
            mock: false,
            client: 'react-query',
            override: {
                mutator: {
                  path: 'libs/msx/orval-data/mutator/custom-client.ts',
                  name: 'useCustomClient',
                },
                query: {
                    useQuery: true,
                    useInfinite: true,
                    useInfiniteQueryParam: 'limit',
                },
            }
        }
    }
};


Start orval v6.10.3 - A swagger client generator for typescript
🛑  msxapi - Oups... 🍻. An Error occurred while writing schema apiAccountEntityEnum => TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

**Comment by anymaniax** [comment]
Hello @ravikiranr26 can you try with `6.11.0-alpha.7`

**Comment by ravikiranr26** [comment]
> 6.11.0-alpha.7

@anymaniax Hello, works great with the version. Thanks a lot. Just have a another query, as new to react-query, 

Can i know how to use the generated hook, useListPetsHook  to fetch, couldnt get the example.

https://github.com/anymaniax/orval/blob/c594bac4b2c8045dfb766833dc10ef5e554b7424/samples/react-query/hook-mutator/endpoints.ts

**Comment by anymaniax** [comment]
You need to use `useListPets` instead. `useListPetsHook` is used to be able to pass a custom client or a custom instance of axios to be able to easily add a token for example
