### ISSUE TITLE
Built model including empty interface has tslint comment not compliant with eslint linter

### ISSUE THREAD

**Issue by splacentino** [anymaniax/orval#265]
## What are the steps to reproduce this issue?
1. `yarn add -D eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser orval`
2. Register eslint plugins from above
3. Create orval config
4. Generate models from api with **with empty model**
5. Check using `eslint` linter

## What happens?

Generated interface has `tslint` comment to bypass issue.

`// tslint:disable-next-line:no-empty-interface`

## What were you expecting to happen?

I am expecting comment to be compliant with `eslint`

`// eslint-disable-next-line @typescript-eslint/no-empty-interface`

## Any other comments?
Working on a PR to let user specify `eslint` in `output` or in general parameter.

## What versions are you using?
**Operating System:** Darwin
**Package Version:** 6.2.0

**Comment by anymaniax** [comment]
Hello @splacentino, Thanks for reporting the issue. Could you do a pull request to fix it the code to change is [here](https://github.com/anymaniax/orval/blob/63e6e21031e3d57ae5916ac2c9f42afe73506d44/src/core/generators/interface.ts#L37)

**Comment by splacentino** [comment]
> Hello @splacentino, Thanks for reporting the issue. Could you do a pull request to fix it the code to change is [here](https://github.com/anymaniax/orval/blob/63e6e21031e3d57ae5916ac2c9f42afe73506d44/src/core/generators/interface.ts#L37)

#266

**Comment by anymaniax** [comment]
Will be included in the next release
