### ISSUE TITLE
Add ability to use single request parameter

### ISSUE THREAD

**Issue by yekver** [anymaniax/orval#281]
Right now all api calls are generated like functions with N parameters. It will be cool to implement an ability to use single request parameter (object) for all request functions, so I end up with code like this:
`myApiCall({ param1, param2 })` instead of `myApiCall(param1, param2)`

This modification becomes very useful in case you have some optional parameters in the middle of function declaration like this: `myApiCall(param1, , , , param5)` -> `myApiCall({param1, param5 })`. Right now this case is impossible because orval combines two approaches and end up with something like this: `myApiCall(param1, param5, {...optional params})` which is quite inconsistent from my point of view.

**Comment by Marcel-G** [comment]
`useNamedParameters` option has been added: https://github.com/anymaniax/orval/pull/914
