### ISSUE TITLE
Get rid of TData generic in query function declaration

### ISSUE THREAD

**Issue by yekver** [anymaniax/orval#283]
Right now every query function has a possibility to have on overwritten return type by using a `TData` generic. There is the [responsible code](https://github.com/anymaniax/orval/blob/bb205cb7505fdcda5ccc206ad508842b73722c00/src/core/generators/axios.ts#L86-L97). This generic looks strange because query functions will always return the same data. Also there is another problem with this approach: typescript unable to calculate queries return type dynamically because there is no guarantee that they wasn't overwritten.

I think it should look like this:
```javascript
return `const ${operationName} = (\n ${toObjectString(props, 'implementation')}\n ${
      isRequestOptions && isMutatorHasSecondArg
        ? `options?: SecondParameter<typeof ${mutator.name}>`
        : ''
    }) => {${bodyForm}
      return ${mutator.name}<${response.definition.success || 'unknown'}>(
      ${mutatorConfig},
      ${requestOptions});
    }
  `;
```

**Comment by anymaniax** [comment]
The TData is there to keep a part of the useQuery flexibility. The `TQueryFnData` which is the type return by the promise is not overridable.

**Comment by yekver** [comment]
Yeah, but we are talking about the axios generator, not about the react-query generator. In my project `react-query` is also used but we have a special typescript helpers overlay for it on top of the axios query functions. And to make this work right there should be a possiblity for the typescript to infer the return type for the query function. Using generics with a default value we are loosing this option because there is no guarantee that generic wouldn't be redefined.

**Comment by anymaniax** [comment]
Hey @yekver, for the Axios generator I agree that it doesn't make sense
