### ISSUE TITLE
No endpoints generated

### ISSUE THREAD

**Issue by lisagherschon** [anymaniax/orval#294]
## What happens?
When using orval with a yaml file the models are generated but not the endpoints.

## What were you expecting to happen?
Orval should generate models & endpoints

## Any logs, error output, etc?
[here](https://gist.github.com/lisagherschon/2771ad41db7e1bfa04129652ede955ce) you can find the yaml

## What versions are you using?
**Operating System:** macOS Monterey 12.0.1
**Package Version:** 6.5.1
**Browser Version:** Chrome 96.0.4664.110

**Comment by anymaniax** [comment]
hi @lisagherschon, there is a problem in your orval config the mode is not correct should be `tags-split`. I will add a warning for that case.
