### ISSUE TITLE
Not generating interface correctly when using anyOf

### ISSUE THREAD

**Issue by vitorcamachoo** [anymaniax/orval#299]
## What are the steps to reproduce this issue?
Given the following schema using `openapi: 3.0.3`:
<img width="606" alt="Screenshot 2022-01-20 at 10 03 55" src="https://user-images.githubusercontent.com/20595956/150317359-a5fb8670-7ddd-4dde-9e2d-3cda1f87fd22.png">

## What happens?
It does not generate correctly the interface:
<img width="749" alt="Screenshot 2022-01-20 at 10 04 51" src="https://user-images.githubusercontent.com/20595956/150317398-55c844de-53f7-44d4-bfa7-a0b8c25f3360.png">

## What were you expecting to happen?
It should generate the type correcty

## Any logs, error output, etc?
N/A

## Any other comments?
N/A

## What versions are you using?
**Operating System:** macOS Monterey
**Package Version:** 6.5.1
**Browser Version:** N/A

**Comment by anymaniax** [comment]
also found a solution for this one and did a pull request
