### ISSUE TITLE
Not generating correctly when using allOf with nullable

### ISSUE THREAD

**Issue by vitorcamachoo** [anymaniax/orval#300]
## What are the steps to reproduce this issue?
Given the following schema for `IssueVisibilityStatus` using `openapi: 3.0.3`:
<img width="227" alt="Screenshot 2022-01-20 at 10 07 33" src="https://user-images.githubusercontent.com/20595956/150318020-9caddfd0-b469-41ae-ba80-486f1f146db2.png">
<img width="439" alt="Screenshot 2022-01-20 at 10 07 45" src="https://user-images.githubusercontent.com/20595956/150318042-3ee08bed-89ad-425a-be40-0e11c4087a22.png">

## What happens?
It is creating a mal formatted variable like the following image:
<img width="799" alt="Screenshot 2022-01-20 at 10 11 14" src="https://user-images.githubusercontent.com/20595956/150318458-97857c5b-4018-476b-b99e-1cb9fba64f84.png">

## What were you expecting to happen?
I was expecting something like this without the creation of a new variable since we are only generating types.
<img width="836" alt="Screenshot 2022-01-20 at 10 10 48" src="https://user-images.githubusercontent.com/20595956/150318407-c731fe38-b8d6-428f-991e-b85a507ccfe7.png">

## Any logs, error output, etc?
N/A

## Any other comments?
N/A

## What versions are you using?
**Operating System:** macOS Monterey
**Package Version:** 6.5.1
**Browser Version:** N/A

**Comment by vitorcamachoo** [comment]
Anyone?

**Comment by anymaniax** [comment]
I will take a look this weekend

**Comment by anymaniax** [comment]
Just did a pull request for it
