### ISSUE TITLE
Replace faker.js with stable @faker-js/faker

### ISSUE THREAD

**Issue by konstantinkreft** [anymaniax/orval#303]
With the turmoil around [faker.js](https://github.com/marak/Faker.js/) it should be replaced by its stable fork [faker-js/faker](https://github.com/faker-js/faker)

Would be happy to help!

**Comment by konstantinkreft** [comment]
But I think this should wait until there is an proper v6.x release.

**Comment by melloware** [comment]
Agreed

**Comment by jogelin** [comment]
FYI https://github.com/ngneat/falso full tree shakable

**Comment by anymaniax** [comment]
faker 6 is released

**Comment by melloware** [comment]
@konstantinkreft did you want to tackle this one?

**Comment by konstantinkreft** [comment]
Yeah sure, I can tackle this one :)
