### ISSUE TITLE
Operation "delete" is not generating valid Typescript

### ISSUE THREAD

**Issue by melloware** [anymaniax/orval#305]
## What are the steps to reproduce this issue?

**Orval:** ^6.5.3
**Type:** react-query

I have a method called `delete` and its not generating correctly.

**OpenApiV3.json**
```javascript
"/authorization/{authorizationId}": {
      "delete": {
        "tags": [
          "Authorization"
        ],
        "summary": "Revoke authorization by ID",
        "operationId": "delete_1",
        "parameters": [
          {
            "name": "authorizationId",
            "in": "path",
            "description": "Id of Authorization to revoke",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "203": {
            "description": "Revoked authorization"
          },
          "403": {
            "description": "User not authorized to revoke"
          },
          "404": {
            "description": "Authorization not found or previously revoked"
          }
        },
        "security": [
          {
            "bearer-key": []
          }
        ]
      }
    },
```

This is generating errors because delete is a reserved word for JSON.

![image](https://user-images.githubusercontent.com/4399574/152051569-583280e9-ce73-4508-8d80-9515754373c3.png)

**Orval Config:**
```javascript
module.exports = {
   authorization: {
     output: {
       mode: 'split',
       target: 'src/query/endpoints/AuthorizationApi.ts',
      schemas: 'src/query/model',
       client: 'react-query',
       mock: false,
     },
     input: {
       target: './authorization-openapi.json',
     },
   },
 };
```

**Comment by melloware** [comment]
Just a note that `openapi-generator` somehow generates this as `_delete` like it knows reserved words somehow.

**Comment by melloware** [comment]
Maybe just blank generating all these internal private methods as `_something` is the way to go?

**Comment by melloware** [comment]
Here is my OpenAPI JSON to demo the issue:
[melloware-openapi.zip](https://github.com/anymaniax/orval/files/8003446/melloware-openapi.zip)

**Comment by anymaniax** [comment]
Do you prefer to have an auto prefix or an error telling you that you use a reserved word? And in that case that advise you to use the `operationName` config

**Comment by anymaniax** [comment]
it's fixed with this but I am not a big fan of prefxing with a `_`
<img width="796" alt="Screen Shot 2022-02-09 at 12 11 43" src="https://user-images.githubusercontent.com/10516382/153186984-3f22678a-0359-4153-aab5-9121a9446677.png">

**Comment by melloware** [comment]
The reason I prefer that fix is because sometimes you can't control what an API is doing like this one I am generating I am not allowed to change the actual enpoint.

**Comment by anymaniax** [comment]
You can do the pull request if you want since you found the issue 😀

**Comment by melloware** [comment]
PR https://github.com/anymaniax/orval/pull/314

I used the word `overriddenOperationName` instead of `overrided`.  But thanks for the suggested fix!
