### ISSUE TITLE
Orval crashes with raw JavaScript error

### ISSUE THREAD

**Issue by SoftMemes** [anymaniax/orval#323]
## What are the steps to reproduce this issue?
I've been able to successfully run Orval on another openapi 2.0 spec, but using it with one generated from services at my company, the tool crashes, and I'm afraid that I've been unable to isolate the specific error. Othertools such as the openapi cli (https://github.com/OpenAPITools/openapi-generator-cli) do correctly process the file.

## What happens?
The tool crashes with the following output:

```
🛑  services - TypeError: Cannot read properties of undefined (reading 'paths')
```

While debugging with Chrome, the exception is down to the following (minified) line:

```
var Oo = async({output: e, context: t})=>P(Object.entries(t.specs[t.specKey].paths), async(r,[n,o])=>{
```

I have not yet run this against the Orval source code, but I can see that t.spects does contain a key for the full path of my input file, whereas t.specKey is the filename of the input file, without the path.

## What were you expecting to happen?
Code to be generated successfully from the input spec.

## Any logs, error output, etc?
See above.

## Any other comments?
This tool looks very promising, keep up the good work!

## What versions are you using?
**Operating System:** Ubuntu 20.04.1 LTS 
**Package Version:** 6.6.0
**Browser Version:** N/A

**Comment by SoftMemes** [comment]
FWIW, I figured this out:

- If "target" in the config file is set to a plain filename in the local directory, the above happens
- If target is a reference to a file in a directory (foo/spec.json) or even using ./ to reference the file (./spec.json), then things work

**Comment by melloware** [comment]
Can you try 6.6.1 which was just released to see if its still an issue?

**Comment by SoftMemes** [comment]
Same issue in 6.6.2 I'm afraid, ./foo.json works, without the ./ it does not.

**Comment by anymaniax** [comment]
Will Check right now

**Comment by anymaniax** [comment]
Normally fixed with `6.6.3`

**Comment by melloware** [comment]
@SoftMemes Have you had a chance to test this with 6.6.3 or 6.6.4 so we can close it?

**Comment by SoftMemes** [comment]
@melloware can confirm, working 6.6.4, thanks!

**Comment by melloware** [comment]
Awesome! Safe to close the ticket
