### ISSUE TITLE
Orval generates output not accepted by TypeScript for Openapi input generated by gRPC

### ISSUE THREAD

**Issue by SoftMemes** [anymaniax/orval#328]
## What are the steps to reproduce this issue?
1. Generate an openapi spec from REST annotated gRPC services using https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-openapiv2
2. Run Orval on the generated output, targeting react-query
3. Build the output with typescript

## What happens?

The OpenAPI (2.0) spec contains a definition of an "Any" type with one known property `@type` as well as other optional properties:

```
    "Any": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string",
          "description": "..."
        }
      },
      "additionalProperties": {},
      "description": "..."
    },
```

This produces the following TypeScript model (comment stripped)

```
export interface Any {

  '@type'?: string;
} & {[key: string]: unknown}
```

This in turn is not accepted by the TypeScript compiler: 

```
src/model/any.ts:121:3 - error TS1109: Expression expected.

121 } & {[key: string]: unknown}
```

## What were you expecting to happen?
Valid TypeScript to be produced, e.g. the openapi cli tool generates this output instead:

```
export interface Any {
    [key: string]: object | any;

    '@type'?: string;
}
```

## What versions are you using?
**Operating System:** Ubuntu 20
**Package Version:** 6.6.2
**Browser Version:** N/A

**Comment by anymaniax** [comment]
Normally fixed with `6.6.3`
