### ISSUE TITLE
Bug: multiple exports with the same name

### ISSUE THREAD

**Issue by yekver** [anymaniax/orval#335]
I my *.yaml file I have a structure like this:
```
openapi 3.0.3
info: ...
tags: ...
paths: ...
components:
  schemas: 
    MyAnotherType:
      type: object
      description: Some text
      properties:
        details:
          type: array
          description: Some text
          items:
            $ref: '#/components/schemas/MyType'
    MyType:
      type: string
      description: Some text
      example: Some more text
```

this causes duplicated `export type MyType = string` in generated `*.schema.ts` file

**Comment by anymaniax** [comment]
I don't have the problem with version `6.7.0` can you check if it's also fixed for you?

**Comment by anymaniax** [comment]
Weird I tried with your specification and the split mode with the react query client. Do you have more information that can help me reproduce it?

**Comment by yekver** [comment]
Yeah. Sorry for the incorrect issue description. I've figured out that problem can be reproduced this way:
1. Create `1.yaml` file with the some structure
2. Duplicate this file with another name, lets say `2.yaml`
3. Go to the `1.yaml` and add some reference to the type from `2.yaml` (`$ref: './2.yaml#/components/schemas/MyType'`)

**Comment by yekver** [comment]
@anymaniax Are there any change to get this bug fixed?

This is very annoying one because I have to manually delete all this duplicated declarations after each generate call :(

**Comment by anymaniax** [comment]
Sorry didn't have time to check yet. Probably this weekend will have the time to do it

**Comment by anymaniax** [comment]
ok, I see the problem now but how do you think we can solve that? Create another file for the second schema with all the models?

**Comment by yekver** [comment]
Looks like this is a naming clash problem.
Creating a separate file for second schema is a great idea, but it wouldn't resolve the problem because names (or even whole types will remain the same) and exact problem will take place during import declaration from schema_2 to schema_1.

From my prospective two things can help to resolve this case:
1. Ignore duplicated type declarations
2. Rename types with duplicated names

**Comment by anymaniax** [comment]
We don't know if the duplicate type are different or would need to compare them. And otherwise using another file + alias import should solve the problem no?

**Comment by yekver** [comment]
> We don't know if the duplicate type are different or would need to compare them.

You are right, comparing absolutely to know whether type is duplicated or not. Otherwise some types will be the same but name.

> And otherwise using another file + alias import should solve the problem no?

Yeah it will, but how to deal with case when all the generated schemas must be merged into a single file?

**Comment by melloware** [comment]
I don't see any easy way to resolve this so closing the ticket. Can reopen if PR is provided.

**Comment by dawsonbooth** [comment]
We're running into this as well, and it seems like the only way forward is to change how our spec is produced from the backend, which is less than ideal 😕

**Comment by dawsonbooth** [comment]
I believe this is the offending line:

https://github.com/anymaniax/orval/blob/89368eacca8225820ab1195052ffe858b7074507/packages/core/src/getters/array.ts#L23

The "Item" text here should be configurable IMO

**Comment by dawsonbooth** [comment]
Already getting familiar with the codebase :)

I'll see if I can find time to put something up soon, but anyone who's contributed before feel free to beat me to it!
