### ISSUE TITLE
Method for adding eslint-disable to generated code

### ISSUE THREAD

**Issue by oscartbeaumont** [anymaniax/orval#346]
Current I am trying to add `/* eslint-disable */` to the top of the code generated by Orval to suppress errors in my code editor. I see in the orval config you can provide a function to the `header` field to modify the header of the generated file. This issue with this is that eslint isn't picking up the disabled instruction due to other text also being in the comment. I need the other text in the comment to warn people not to modify the generated file. 

Does a feature already exist to do this or to directly modify the generated code prior to it being saved to the file?

Thanks for this awesome project!

**Comment by oscartbeaumont** [comment]
Eg. something like `modifyCode: (code: string) => string;` in the config file would be perfect for my usecase.

**Comment by anymaniax** [comment]
Hello @oscartbeaumont, I will check in the array if you add the line eslint-disable and handle it differently. Like the following code. And also I will add a way to pass directly a string like that you can inject whatever you want. is it ok for you?

```ts
/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Petstore API
 * Petstore API
 * OpenAPI spec version: 1.0.0
 */
```

for this code 

```ts
header: ({ title, description, version }) => [
   `Generated by orval 🍺`,
   `Do not edit manually.`,
    ...(title ? [title] : []),
    ...(description ? [description] : []),
    ...(version ? [`OpenAPI spec version: ${version}`] : []),
    'eslint-disable',
]
```

**Comment by oscartbeaumont** [comment]
That sounds like a great solution.

**Comment by anymaniax** [comment]
Will be in the next release

**Comment by anymaniax** [comment]
Fixed with `6.7.0`

**Comment by lvindotexe** [comment]
hey, could you provide an example on how to do this, i cant find one in the documentation

**Comment by melloware** [comment]
@lvindotexe Its in the docs here: https://orval.dev/reference/configuration/output#header

in your Orval config simply add the following:

```js
header: (info: InfoObject): String[] => { return "/* eslint-disable */ \r\n" },
```

or like this if you want to keep the current header and add ES Lint

```js
module.exports = {
   petstore: {
     output: {
       override: {
         header: (info: InfoObject): String[] => [
           `Generated by orval 🍺`,
           `Do not edit manually.`,
           ...(info.title ? [info.title] : []),
           ...(info.description ? [info.description] : []),
           ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
           'eslint-disable',
         ],
       },
     },
   },
 };
```
