### ISSUE TITLE
Bug: Broken query result type generator in 6.7.0

### ISSUE THREAD

**Issue by yekver** [anymaniax/orval#348]
My config output looks like this:
```javascript
{
  workspace: 'src/api',
  client: 'axios',
  mode: 'split-tags',
  override: {
    title: (title) => `${title}Api`, // This line is ignored by the query result type generator
    mutator: myMutator
  }
}
```

Generated result looks like this:
```javascript
export const petsApi = () => {
  const someMethod = () => {}
}

export type SomeMethodResult = NonNullable<AsyncReturnType<ReturnType<typeof pets>['someMethod']>>
```

As you can see there is an error in `ReturnType<typeof pets>` because there is no variable `pets` exists. Instead `petsApi` should be used.

P.S. Also it seems like there is no need to duplicate the `NonNullable<AsyncReturnType<ReturnType<typeof pets>['someMethod']>>` every time because the only thing is changing is the name of the method and it can be passed as a generic

**Comment by anymaniax** [comment]
Fixed will be in the next release
