### ISSUE TITLE
Bug: oneOf/anyOf/... break enum options' values generation

### ISSUE THREAD

**Issue by o-alexandrov** [anymaniax/orval#365]
## What are the steps to reproduce this issue?
1. Define an OpenAPI property schema

```ts
{
  exampleEnum: {
    oneOf: [
      { type: 'string', enum: [ "0", "1" ] },
      { type: 'string', enum: [ "" ] }
    ]
  }
}
```

2. Run `orval`
3. Confirm broken generated values below (value appear in the `*.schemas.ts` files)

```ts
export const ExampleEnum = {  NUMBER_0: '0' as ExampleEnum,
  NUMBER_1: '1' as ExampleEnum,
,  NUMBER_: '' as ExampleEnum,
};
```

## What happens?

Idk what happens internally with `orval`.
However, in the generated result:
- there's an extra comma `,` between `oneOf` options.

## What were you expecting to happen?
Valid values being generated in this case w/o an extra comma.

## What versions are you using?
**Operating System:** `MacOS 12.3`
**Package Version:** `6.7.1`

**Comment by anymaniax** [comment]
Should be fixed in the next version

**Comment by o-alexandrov** [comment]
Fixed
