### ISSUE TITLE
MSW: Unstable mock generated for object with unspecified property name

### ISSUE THREAD

**Issue by yekver** [anymaniax/orval#368]
In case object has unspecified (dynamic) property names like `export type PetSomeField = {[key: string]: string[]};` mock generator function creates unique property name on every api generation call. This causes useless changes in generated files.

mock generator function:
```javascript
export const getCreatePetsMock = () => ({someField: faker.helpers.randomize([{
  'cl2fwufng0000ky8xa7qhg7u0': [...Array(faker.datatype.number({min: 1, max: 10}))].map(() => (faker.random.word()))
}, undefined])})
```

```yaml
openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    post:
      summary: Create a pet
      operationId: createPets
      responses:
        '200':
          description: Created Pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      properties:
        someField:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
```

**Comment by anymaniax** [comment]
Hello @yekver, what would be a good solution for you? Always the same static object?

**Comment by yekver** [comment]
> Hello @yekver, what would be a good solution for you? Always the same static object?

Yeah I think that in this case generator should return stable object.

**Comment by arlyon** [comment]
Maybe a solution here is to seed the cuid generator with the operationId + path into the return type

**Comment by melloware** [comment]
CUID was removed https://github.com/anymaniax/orval/issues/974 and now MSW/Faker is reliable on every run.
