### ISSUE TITLE
More customizable axios options.

### ISSUE THREAD

**Issue by arthurfiorette** [anymaniax/orval#370]
Add some options to update the `AxiosRequestConfig` and `AxiosResponse` types.

Like:

```ts
{
  output: {
    axiosRequestType: 'CustomAxiosType',
    axiosResponseType: 'CustomAxiosResponse'
  }
}
```

This should be very simple and fast to do. 

Thanks!

**Comment by anymaniax** [comment]
Hello @arthurfiorette, why do you need that?

**Comment by arthurfiorette** [comment]
Lol, seems that I forgot about this issue and opened another one :)

#381
