### ISSUE TITLE
feature request: RTK Query

### ISSUE THREAD

**Issue by pxlprfct** [anymaniax/orval#373]
Hi there!

Is there any appetitite for Orval to support [RTK Query](https://redux-toolkit.js.org/rtk-query/overview)? I think it's a _fairly_ popular library - but I also realise that any new functionality is _another_ thing to support. 

I might be able to PR it if I can work out the codebase... but don't want to start anything if the 'want' isn't there for it.

Thanks so much,
Ollie

**Comment by anymaniax** [comment]
Hello, can be cool to have a client rtk-query indeed. You can try to do it if you want and I am there if you need help 🙂

**Comment by zoubingwu** [comment]
Why reinvent wheel when RTKQ provides its own tool for code generation? See https://redux-toolkit.js.org/rtk-query/usage/code-generation

**Comment by pxlprfct** [comment]
https://github.com/anymaniax/orval/issues/373#issuecomment-1118287591 using the existing RTK codegen probablty makes the most sense overall 👍
