### ISSUE TITLE
Support for AsyncReturnType generic also returning an observable?

### ISSUE THREAD

**Issue by maartencardinaels** [anymaniax/orval#376]
Since we upgraded to the latest version, we noticed that a `AsyncReturnType` has been added to the generated files which is defined as follows:

`type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (...args: any) => Promise<infer R> ? R : any;`

assuming you always work with promises.

Would it be an option to provide also support for observables in this type?

**Comment by anymaniax** [comment]
Hi @maartencardinaels, we are currently changing to use the awaited type. I will check if we can do compatibility to observable at the same time.

**Comment by anymaniax** [comment]
I will use [this](https://github.com/ReactiveX/rxjs/blob/master/src/internal/types.ts#L210) which handles both cases and come from rxjs. Is it ok for you?

**Comment by anymaniax** [comment]
Hello @maartencardinaels, just to be sure you need the type inside the observable or the observable directly?

**Comment by maartencardinaels** [comment]
@anymaniax, thanks a lot for looking into this!

The issue we now have is that the generated code - in our situation is that for instance:

```
export const retrieveInformation = () => {
 // returns an observable
}

export type RetrieveInformationResult = NonNullable<AsyncReturnType<typeof retrieveInformation>>
```
is not compatible with the fact that for `AsyncReturnType<T>`, T is always assuming that a promise is returned. So if the return type of T could also be an `observable<any>` besides a `promise<any>`, that would be nice.

**Comment by anymaniax** [comment]
ok will be fix in the next version normally 🎉
