### ISSUE TITLE
[bug] Duplicated type Awaited and AwaitedInput inside of the root index.js file.

### ISSUE THREAD

**Issue by stijnvanhulle** [anymaniax/orval#399]
![image](https://user-images.githubusercontent.com/5904681/169037546-8adbe0c1-3b89-4605-9f9d-a0f3fbbee405.png)

```javascript

export type AwaitedInput<T> = PromiseLike<T> | T
export type Awaited<O> = O extends AwaitedInput<infer T> ? T : never
```

The following 2 types are exported by every controller, meaning that when importing them in an index.js file it will cause Typescript issues. Those 2 types used in a controller should not be exported.

Thanks
Stijn

**Comment by anymaniax** [comment]
Will do a fix release for that tonight sorry

**Comment by stijnvanhulle** [comment]
Thanks @anymaniax 💯
