### ISSUE TITLE
Generating json object for Blob[] returns empty object

### ISSUE THREAD

**Issue by OsidAbu-alrub** [anymaniax/orval#402]
## What are the steps to reproduce this issue?
1. Have an endpoint that expects an array of Blobs/Files
2. Generate call function using orval

## What happens?
You will see something like the following:
```javascript
if(body.pictures !== undefined){
  formData.append(
    "pictures",
    JSON.stringify(body.pictures) // typeof pictures is Blob/File => https://developer.mozilla.org/en-US/docs/Web/API/Blob
  )
}
```
Instead of `JSON.stringify(body.pictures)` returning an array of binary values, it returns an an empty object
<br/>
This happens because `Blob`/`File` objects are not considered json objects, thus the confusion. 
…

## What were you expecting to happen?
The expected result is to send the blobs to the endpoint as binary values

## Fix
Generate the following code instead of the one above (for files):
```javascript
if(body.pictures !== undefined){
  body.pictures.forEach(picture => formData.append("pictures",picture))
}
```
…
## What versions are you using?

**Operating System: Windows** …
**Package Version: 16.13.0** …
**Browser Version: Chrome - 101.0.4951.67** …

**Comment by anymaniax** [comment]
Released with 6.9.0
