### ISSUE TITLE
Customizing error type (TError) in SWR integration

### ISSUE THREAD

**Issue by movahedan** [anymaniax/orval#420]
I'm using orval with SWR, and it's working fine, but the error type is always `unknown` unless I provide them at the usage level each time I want to use an API call. It's a good idea to type the error somehow in the `customInstance` or in `orval.config.js`. Is it possible?

**Comment by anymaniax** [comment]
Hey @movahedan, you can export an ErrorType type in the mutator which should do the job. You have an example [here](https://github.com/anymaniax/orval/blob/master/samples/react-query/custom-client/src/api/mutator/custom-client.ts)

**Comment by vitorcamachoo** [comment]
@anymaniax customInstance is only receiving one generic argument, which is the response. Is there any way to adapt customInstance to support two generic arguments and leave orval do the rest? Like:
```tsx
export const getUsers = (options?: SecondParameter<typeof customInstance>) => {
  return customInstance<Users, UsersError>({ url: `/api/users`, method: 'get' }, options);
};
```

**Comment by movahedan** [comment]
> Hey @movahedan, you can export an ErrorType type in the mutator which should do the job. You have an example [here](https://github.com/anymaniax/orval/blob/master/samples/react-query/custom-client/src/api/mutator/custom-client.ts)

Yes, that's exactly what I did previously in my project. Seems a bit tricky though. I agree with @vitorcamachoo, that would be even nicer.

**Comment by soartec-lab** [comment]
@movahedan 

Hi, have all your questions about this issue been resolved? Is there anything I can do to help?

**Comment by soartec-lab** [comment]
@melloware 

Hi, I will watch this issue, so could you assign it to me?
Or, since it seems like the question has already been resolved, you may want to close it.

**Comment by melloware** [comment]
I will close it for now as it seems like it was answered.
