### ISSUE TITLE
Ignore certain MIME types

### ISSUE THREAD

**Issue by arlyon** [anymaniax/orval#421]
## What were you expecting to happen?

I have an api that publishes multiple MIME types, namely `application/json+hal` and `text/uri-list`. I would love to be able to configure orval to ignore a subset of those, as the text/uri-list types are causing all my hooks to be `T | string` which is a pain to deal with.

## What versions are you using?

**Operating System:** Fedora 36
**Package Version:**  6.8.1
**Browser Version:** FF 100

**Comment by anymaniax** [comment]
Released with 6.9.0. You can check [here](https://orval.dev/reference/configuration/output#contenttype)
