### ISSUE TITLE
Discriminated unions with identifiers

### ISSUE THREAD

**Issue by BaDo2001** [anymaniax/orval#423]
I would like to know whether its possible to generate TypeScript union types which include identifiers to be able to easily distinguish between subtypes. For example if I have a swagger file like this:

```
components: {
  schemas: {
    Shape: {
      required: [
        "$type"
      ],
      type: "object",
      properties: {
        $type: {
          type": "string"
      },
      discriminator: {
        propertyName: "$type",
        mapping: {
          Rectangle: "#/components/schemas/Rectangle",
          Circle: "#/components/schemas/Circle"
        }
      }
    },
    Rectangle: {
      type: "object",
      allOf: [
        {
          "$ref": "#/components/schemas/Shape"
        }
      ],
      ...
    },
    Circle: {
      type: "object",
      allOf: [
        {
          "$ref": "#/components/schemas/Shape"
        }
      ],
      ...
    }
  }
}
```

And I have a union type of the subtypes like this:
```
type ShapeInput = Rectangle | Circle;
```
It would be nice if the subtypes included a field like these:
```
interface Rectangle {
    type: 'Rectangle';
   ....
}

interface Circle {
    type: 'Circle';
    ....
}
```

Is it possible to achieve this currently?

**Comment by anymaniax** [comment]
Hey @BaDo2001, currently it's not possible but if you have the time to do an implementation for it. It would be cool

**Comment by BaDo2001** [comment]
Hey  @anymaniax! I'll take a look into it.

**Comment by BaDo2001** [comment]
@anymaniax I can see 2 distinct ways to make this work and have proper TypeScript type discrimination:

1. The base type would need to omit the discriminator field and the subtypes should describe their own fields each with correct string literal.

This seems like a breaking change because it would essentially omit a field that should be present based on the API schema, but it would seem the most natural based on the project that I am currently working on.

2. We introduce a new field to the subtypes like this:

'''
interface Rectangle {
    _discriminator: 'Rectangle';
   ....
}

interface Circle {
    _discriminator: 'Circle';
    ....
}
'''

This keeps the current behaviour however it contradicts the API schema in my opinion, because it should be the `type` field that discriminates in the example above.

This also proposes the problem of what if there is a property named `_discrimator` on the object but one problem at a time I guess.

Which one of these seems more promising and user friendly to you? Do you see a 3rd of doing this?
