### ISSUE TITLE
Customize SWR Options

### ISSUE THREAD

**Issue by ryanplauche-altana** [anymaniax/orval#443]
Hi, I'm using the `swr` generator, and I noticed the option to pass a `SWRConfiguration` into the generated hooks. I was wondering if it's possible to generate a custom default set of `swrOptions`, ie modifying the fallback in this code `const {swr: swrOptions} = options ?? {}`. For now I can pass in our custom swr config into each hook, but I would love if we could automate including that config if possible!

**Comment by anymaniax** [comment]
Released with 6.9.0
