### ISSUE TITLE
Should I install orval locally to be able to import defaultConfig?

### ISSUE THREAD

**Issue by erfanansari** [anymaniax/orval#471]
## What are the steps to reproduce this issue?

Just use orval.config.ts

## What happens?

If you've installed orval globally, you can't import defaultConfig

## What were you expecting to happen?

That the docs would mention that orval should be installed locally as a dev dependency

**Comment by anymaniax** [comment]
Are you talking about the defineConfig function? If yes, this function is just to have the typescript type easily but orval work without it

**Comment by erfanansari** [comment]
Yes, I noticed that, I would just suggest that you may wanna add a local installation section to the docs for those who wanna use the defineConfig function.
