### ISSUE TITLE
Property 'arrayElement' does not exist on type 'Random'.

### ISSUE THREAD

**Issue by AO19** [anymaniax/orval#472]
## What are the steps to reproduce this issue?

1. Run Orval with a schema with Array or Enum Elements in an Array. `days?: Array<DaysEnum>;`

## What happens?

Orval generates mocks with `faker.random.arrayElement()`. But arrayElement does not exist on random, it is now on helpers.

## What were you expecting to happen?

Orval should generate mocks with `faker.helpers.arrayElement()`.

## Any other comments?

Probably just a breaking change with FakerJS?

## What versions are you using?

**Operating System:** macOS Monterey 12.4
**Package Version:** 6.8.1
**Browser Version:** Chrome 103.0.5060.114

**Comment by AO19** [comment]
> @AO19 I would like to work on this issue, Could you assign this to me?

I can not assign you to this issue, I think @anymaniax has to do it.

**Comment by anymaniax** [comment]
Hello, it's because of the new version of faker. It's already done and will be in the next release

**Comment by AO19** [comment]
Alright, thank you for your response.
