### ISSUE TITLE
Sort Schema barrel file

### ISSUE THREAD

**Issue by SamKirkland** [anymaniax/orval#483]
First of all thanks a bunch for this library. Really awesome and amazing work, it's my go-to for projects now.

## What are the steps to reproduce this issue?

1. Clone orval@6.8.1
2. Open `samples/react-query/basic`
3. run `npm install`
4. run `orval --config ./orval.config.ts`
5. Look at the output of `samples/react-query/basic/src/api/model/index.ts`
5. Delete the file (or a single line)
6. re-run `orval --config ./orval.config.ts`
7. Note how the file contents is not stable, the contents can be in any order

## What happens?
The contents of the schema barrel files (model/index.ts in this example) are not stable - they do not produce the same results if you clear the output and re-run.

## What were you expecting to happen?
I expect the outputs of all files to be stable. If I clear the output and run orval I should get the same result as long as the input did not change.

## Any other comments?
Root cause is due to the append logic within `writeSchemas` ([see source](https://github.com/anymaniax/orval/blob/9440969d21e1351ce9ff3706f89587f0df767a8d/src/core/writers/schemas.ts#L73))

Wondering your thoughts on the following proposed solution:
Refactor `writeSchemas` to do the following:
1. Build the entire contents of the schemas list in memory (no IO required). The lines would be sorted by name.
2. Do a single IO write to to overwrite the entire contents of the file (instead of a loop of promises)

This should also result in better performance.

The current solution (promise.all) would be difficult to solve because the promises can resolve in any order.

## What versions are you using?

**Operating System:** Windows 10
**Package Version:** 6.8.1

**Comment by Jeremie-Chauvel** [comment]
Hi, seems I have exactly the same issue, a simple reproduction setup: https://github.com/Jeremie-Chauvel/orval-index-sort-issue

As a basic workaround, I use the shell `sort` command post Orval type generation for now.
