### ISSUE TITLE
Feature request: Readonly types

### ISSUE THREAD

**Issue by zzau13** [anymaniax/orval#490]
Feature request: Add option in orval config file for generate Readonly wrapped types.

Thanks!

**Comment by anymaniax** [comment]
What do you mean? Can you add an example?

**Comment by botika** [comment]
The model types should remain like: 
```typescript
type EntityOrDto = Readonly<{ foo: string }>;
```
For functional programming. I have also implemented it in the fork,https://github.com/botika/forval . Also, could put an option, `readonly: boolean`  in the config file.

**Comment by anymaniax** [comment]
The readonly if you add on the specification it should be added automatically. But you want another property in the config to automatically add the Readonly type on every model generated right?

**Comment by botika** [comment]
From https://swagger.io/specification/ :
> Relevant only for Schema "properties" definitions. Declares the property as "read only". This means that it MAY be sent as part of a response but SHOULD NOT be sent as part of the request. If the property is marked as readOnly being true and is in the required list, the required will take effect on the response only. A property MUST NOT be marked as both readOnly and writeOnly being true. Default value is false.

Is not the same. I want the type to be immutable to follow the functional paradigm.

**Comment by anymaniax** [comment]
ok, so what do you exactly want for property read-only in the orval config? Just the Readonly<Your Model> or more?

**Comment by botika** [comment]
I can do the PR. You want?

**Comment by anymaniax** [comment]
If you have time sure

**Comment by melloware** [comment]
This was fixed with #616
