### ISSUE TITLE
Feature Request: support react-query v4

### ISSUE THREAD

**Issue by mainfraame** [anymaniax/orval#497]
react-query recently released an update to v4. Orvel will need to be modified to adjust for the differences in v3 and v4. Here is the [guide](https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4) to do that.

**Comment by anymaniax** [comment]
If I am not wrong it just replacing the import will be in the next release in the coming days

**Comment by maciej-skyfi** [comment]
I'm not quite sure it's going to be that straightforward (even though I hope it will), i had some issues with types when i upgraded to v4, mainly with `UseQueryOptions`.

**Comment by anymaniax** [comment]
Just did the update by just changing the npm package and everything seems to work fine. @maciej-skyfi do you have more info on the issue?

**Comment by anymaniax** [comment]
I did the update like this I didn't find any issue just by changing the package. We do a release asap

**Comment by anymaniax** [comment]
Released with 6.9.1 don't hesitate if you have any trouble

**Comment by missing1984** [comment]
upgrading import from 'react-query' to `@tenstack/react-query` seems to be a breaking change?

**Comment by melloware** [comment]
I would remain on 6.9.0 until you are ready for query 4.  It doesn't seem worth supporting both and query 4 comes with automatic update tools to fix your code for you

**Comment by anymaniax** [comment]
It’s controlled with your package.json. If you still have the old package installed and not the new one it’s take the old version

**Comment by melloware** [comment]
Ran this today and works like a charm all updated to React Query 4 in about 5 minutes!

**Comment by maapteh** [comment]
🛑  frontend - Oups... 🍻. Client not found: @tanstack/react-query

They rebranded react-query into new package name as well :(

**Comment by reichhartd** [comment]
@anymaniax I think this issue can be closed
