### ISSUE TITLE
Svelte-Query only produces the query Object, still must subscribe for the results

### ISSUE THREAD

**Issue by Arzemn** [anymaniax/orval#499]
## What are the steps to reproduce this issue?

1. openapi.yaml
2. orval create svelte-query files
3. import Svelte-Query hook
 const query = useGeneratedSvelteQueryHook()

query will only have the function query.subscribe() and I must run the subscribe to actually execute the hook.

what are the steps to autosubscribe so its more similar to react-query where the hook will execute once created?

query.subscribe(value=>value)

value has the expected svelte-query object with value.isSuccess, value.data etc..

**Comment by anymaniax** [comment]
Hello @Arzemn, can you provide an example?

**Comment by melloware** [comment]
No response from OP in over a year.  Closing.
