### ISSUE TITLE
feature request: add comments to generated file

### ISSUE THREAD

**Issue by maapteh** [anymaniax/orval#514]
I would like to be able to add comment to the generated file, example:

```
/* eslint-disable no-duplicate-imports */
```

I can add them in ignore lists but handling from the generated file itself would be nicer.

**Comment by anymaniax** [comment]
Hi @maapteh, you can already probably do that with [this](https://orval.dev/reference/configuration/output#header)

**Comment by maapteh** [comment]
I clicked all options, but apparently not enough :) thanks!
