### ISSUE TITLE
bug?: react-query implementation when POST is used it always transforms into `useMutation` while for some cases its a `useQuery` for us!

### ISSUE THREAD

**Issue by maapteh** [anymaniax/orval#515]
Hi, i noticed when my endpoint is POST the tooling generates a `useMutation` implementation, while for us it's really a `useQuery`. 

Since we can't dictate how the api's should be setup (POST has been chosen as a security measurement for this particular case), I was wondering if there is a way to tell the tooling which implementation to use for specific endpoints/methods?

**Comment by anymaniax** [comment]
Hey @maapteh it's not possible for now. I would it to add an options for it

**Comment by reichhartd** [comment]
I think you can also use override to create a `useQuery` for a specific `operationId` (in this case `FindUsers`).
We have a similar case and solve it like this:

```ts
import { defineConfig } from 'orval';

import openApiSpec from './apiSpecs/swagger.json';

export default defineConfig({
    [openApiSpec.info.title]: {
        output: {
            clean: true,
            client: 'react-query',
            headers: true,
            mode: 'tags-split',
            override: {
                operations: {
                    FindUsers: {
                        query: {
                            useQuery: true,
                        },
                    },
                },
            },
            target: 'src/services/generated/api.ts',
            tsconfig: 'tsconfig.json',
        },
        input: {
            target: 'apiSpecs/swagger.json',
        },
    },
});
```

**Comment by anymaniax** [comment]
Thanks, @reichhartd. Completely forgot that I did that 😅

**Comment by landtee** [comment]
sorry if I poke everyone watching this thread but I wonder if there is a way to generate both useQuery, useMutation with custom name as right now overriding with both useMutation and useQuery are true give out hook with same name

**Comment by melloware** [comment]
@landtee i suggest opening a Discussion in the Discussion area and provide your example config and what its generating and what you would like it to generate.
