### ISSUE TITLE
Was anybody able to set this up with Nextjs and React-query?

### ISSUE THREAD

**Issue by la55u** [anymaniax/orval#520]
## What are the steps to reproduce this issue?

I'm trying to achive the following setup with Orval, but I'm unable to do so. (I only want to use client side fetching, no need for SSR for now)

- Nextjs
- React-query
- Suspense
- Mocks

1. clone this repo: https://github.com/la55u/orval-demo
2. run `npm run dev` and open your browser
3. the error should appear

## What happens?
It loads the query (loading text isn't shown) and then it errors out:
```
Error: Text content does not match server-rendered HTML.
See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

## What were you expecting to happen?
To first see `Loading...` text and then to show the JSON response body.

## What versions are you using?

Using orval v6.9.2

Can you help? Thank you

**Comment by anymaniax** [comment]
Hello @la55u, never did that setup with nextjs and suspense. I don't find any example with this setup on the react query website either. [Here](https://tanstack.com/query/v4/docs/examples/react/suspense?from=reactQueryV3&original=https://react-query-v3.tanstack.com/examples/suspense) you have the example directly with react
