### ISSUE TITLE
Reusing mock definitions across multiple services

### ISSUE THREAD

**Issue by SoftMemes** [anymaniax/orval#556]
This is a feature request more than a bug, unless this is already possible in which case I would love to know how!

I'm tweaking the generated mocks via the orval config file. This works great for the most part, but I have some common patterns/helpers that I would love to be able to reuse effectively, e.g. a faker definition for various types that are used across the application.

Is there a way to include these in an external file and reuse them across definitions? I tried simply using imports in the orval config file, but as the imports do not carry over into the generated files, it's not possible to use the generated code.

**Comment by anymaniax** [comment]
Hello @SoftMemes, can you provide a little repo with an example?
