### ISSUE TITLE
PageParams not passed to queryFn on generated useInfiniteQuery

### ISSUE THREAD

**Issue by ClementLevesque** [anymaniax/orval#557]
Thanks a lot for your library and all the job you've done! I really love it 😍 !

## What are the steps to reproduce this issue?

I use Orval 6.8.1 and react-query 3.39.2.

1. Set the config to generate react-query infinite-query :

```javascript
output: {
      ...
      client: 'react-query',
      override: {
        query: {
          useQuery: true,
          useInfinite: true,
        },
     },
     ...
}
```
3. Generate hooks for a schema with api routes with parameters
4. Use react-query v3

## What happens?

I simplified some data in order to focus on the issue I notice :

```typescript
export const fetchData = (
    params?: Params,
 signal?: AbortSignal
) => {
      return myCustomFetch<Type200>(
      {url: `/api/myroute`, method: 'get', signal,
        params,
    },
      );
    }

export const useListOrdersWithProductsInfinite = (params?: Params, options?: { query?:TypeRQ, }) => {
  const {query: queryOptions} = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getQueryKey(params);

  // The problem is here :
  // only `signal` prop is retrieved as an argument and `params` is retrieved from the hook's first argument
  // From the [react query docs](https://react-query-v3.tanstack.com/reference/useInfiniteQuery) params should generally be calculated by the `getNextPageParam` function via the `options` prop
  
  const queryFn: QueryFunction = ({ signal }) => fetchData(params, signal);

  // I think it should be : 
  //  const queryFn: QueryFunction = ({ signal, pageParam }) => fetchData(pageParam, signal);

  const query = useInfiniteQuery(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}
```

## What were you expecting to happen?

Return value from `getNextPageParam` should be passed as a prop to the queryFn.

## Any logs, error output, etc?

N/A

## Any other comments?

I did not check the react-query V4 API so I don't know if there is a problem in V4.

## What versions are you using?

**Operating System:** …
**Package Version:** …
**Browser Version:** …

**Comment by k1ns3** [comment]
Hello, the problem has not been solved yet?

**Comment by anymaniax** [comment]
You need to also pass `useInfiniteQueryParam` to the config

**Comment by ClementLevesque** [comment]
@anymaniax thanks for your help, it adds the parameter ! However, I may have missed something as now I have a typescript error indicating that the params props passed to the fetch function has now an unexpected extra param 

![Capture d’écran 2023-02-24 à 15 06 54](https://user-images.githubusercontent.com/24827952/221198559-1185c975-82a5-46d9-8cca-929371a5eb7b.png)

Do I need to do something additionnaly ? 🙏

**Comment by anymaniax** [comment]
@ClementLevesque you don't have nextId defined in your query params apparently
