### ISSUE TITLE
Feature: Support TanStack Query v4 - @tanstack/react-query

### ISSUE THREAD

**Issue by torleifhalseth** [anymaniax/orval#577]
Feature request: I would love to use orval together with the latest react-query.

**Comment by anymaniax** [comment]
Hello @torleifhalseth, it's already supported. You just need to have the new package installed in your package.json

**Comment by melloware** [comment]
@torleifhalseth I have been using Tanstack 4 in production with Orval for a month now!  Works great.

**Comment by torleifhalseth** [comment]
Awesome! Thanks for the quick response. I was trying to define the client in our Orval configuration and defining `@tanstack/react-query` as the client gives a not assignable error in Typescript. I guess I can just install the new version and keep the client as "react-query"?

**Comment by melloware** [comment]
Yep that is all I did was update my React Query dependencies in package.json and then regenerate and Orval sees you are using the new ones and generates for v4.
