### ISSUE TITLE
Sort MSW handlers by default

### ISSUE THREAD

**Issue by la55u** [anymaniax/orval#606]
## What are the steps to reproduce this issue?

This is a rather unfortunate behavior of MSW: https://github.com/mswjs/msw/issues/814

When there are two handlers specified like this:
```js
rest.get(`${API_URL}/blog-categories/:id`, resolver) // first one with path parameter
rest.get(`${API_URL}/blog-categories/count`, resolver) // second one with static path
```
Then a request to `/blog-categories/count` will return the response defined in `/blog-categories/:id` because that one is matched first.
Since orval generates the mock definitions in an order that is incompatible with the "desired" behaviour, the mock will always return the wrong response.

## What were you expecting to happen?

I expect it to resolve the correct mock handler. 
A quick fix to this problem could be to sort the mock definitions:
Any handler that has path parameter should be after all the handlers with static paths. This way the above scenario would never apply.

Thank you! 

## What versions are you using?

**Package Version:** 6.10.2

**Comment by melloware** [comment]
@Will-Mann-16 fixed this in 6.20.0 which upgrades to MSW 2.0 which looks like it contains that MSW fix
