### ISSUE TITLE
Enum types with symbol in their name break because of the pre-sanitization step

### ISSUE THREAD

**Issue by marcotoniut** [anymaniax/orval#608]
## What are the steps to reproduce this issue?

1. Run generation script of an enum with symbols as it's values (eg. ['+', '-', '*', '/'])

## What happens?

The end result is a broken object:
```ts
export const OperatorDTO = {
  '': '+',
  '-': '-',
  '': '*',
  '': '/',
} as const;
```

## What were you expecting to happen?

The correct names for the object (since it's just a string, it should probably be considered valid as a key)
```
export const OperatorDTO = {
  '+': '+',
  '-': '-',
  '*': '*',
  '/': '/',
} as const;
```

## Any logs, error output, etc?

This results in compilation errors, after generation

## What versions are you using?

**Package Version:** v6.9.6

**Comment by anymaniax** [comment]
will be fixed in the next release

**Comment by anymaniax** [comment]
hey @marcotoniut should be fixed with the last release

**Comment by marcotoniut** [comment]
Yep, already upgraded and removed our "overrides". Thank you, @anymaniax. Although, from looking at the implementation, one thing I should mention is that the problem would still persist for strings bigger than one character that start with a symbol.

It's not a problem for us, but somebody might face this very issue eventually.

**Comment by anymaniax** [comment]
#638
