### ISSUE TITLE
Deprecated flag does not propagate out to final function

### ISSUE THREAD

**Issue by arlyon** [anymaniax/orval#609]
## What are the steps to reproduce this issue?

1. Create an openapi spec with a deprecated api method
2. Observe that the deprecated flag is applied to the `useMyResourceHook`
3. Observe that it is _not_ applied to `useMyResource`, meaning the deprecation is 'hidden'

I have considered using `useDeprecatedOperations` however I don't want to have to drop deprecated hooks immediately.

## What versions are you using?

**Operating System:** fedora 36
**Package Version:** 6.10.2
**Browser Version:** firefox 102

**Comment by anymaniax** [comment]
Hello @arlyon, can you provide an example of specification/code to ease the implementation and follow-up?

**Comment by arlyon** [comment]
Absolutely. I have a repo here: https://github.com/arlyon/orval-deprecate/

I would expect that because of this

https://github.com/arlyon/orval-deprecate/blob/71cb526ec8619b54534b7600c8ff3bf22373deb2/petstore.ts#L137-L141

That this hook would have the deprecated flag propagated to it

https://github.com/arlyon/orval-deprecate/blob/71cb526ec8619b54534b7600c8ff3bf22373deb2/petstore.ts#L163

**Comment by jrozbicki** [comment]
I second that, using hook like `useMyResource` doesn't show that it's deprecated. Maybe we could copy comments also to `useMyResource`?

**Comment by AlexanderKositsyn** [comment]
Same issue. Please fix this.

**Comment by AlexanderKositsyn** [comment]
@anymaniax Did you see an example from @arlyon ?

**Comment by anymaniax** [comment]
@AlexanderKositsyn has not yet had the time to check this issue. Should be difficult to had I think.

**Comment by AlexanderKositsyn** [comment]
@anymaniax 
Add deprecated flag to 
https://github.com/arlyon/orval-deprecate/blob/71cb526ec8619b54534b7600c8ff3bf22373deb2/petstore.ts#L363 
because this getQueryKey is used to invalidate queries and often used in code bases. But now when api method doesnt deprecated it is not highlited.

**Comment by melloware** [comment]
Closing looks like this was fixed a while ago.
