### ISSUE TITLE
Input target authentication

### ISSUE THREAD

**Issue by Southclaws** [anymaniax/orval#618]
Just a minor request for a feature, maybe it's already possible, not sure.

Basically, we host our specification on a URL behind a bearer token auth, so access requires `Authorization: Bearer ...` in the headers. Now I'm pretty sure I can just make this endpoint require HTTP basic auth instead and make my orval config:

```js
 module.exports = {
   petstore: {
     input: {
       target: 'https://username:password@staging-api.example.com/openapi.json'
     },
   },
 };
```

But it would be neat if we could specify some authentication options for remote targets.

The reason for this is just to reduce coupling for our team so they don't need to keep a copy of the backend repo updated, they can just point their codegen tooling at the latest current live version of our spec.

**Comment by yassineaddi** [comment]
You could use [parserOptions](https://orval.dev/reference/configuration/input#parseroptions) with the built-in `http` resolver to set your `Authorization` header:

```js
input: {
  target: 'https://staging-api.example.com/openapi.json',
  parserOptions: {
    resolve: {
      http: {
        headers: {
          Authorization: 'Bearer token',
        }
      },
    },
  },
}
```

**Comment by Southclaws** [comment]
Perfect, thanks!
