### ISSUE TITLE
Problem with schema referencing itself

### ISSUE THREAD

**Issue by ruiaraujo012** [anymaniax/orval#625]
## What are the steps to reproduce this issue?

1. A schema like this:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/16304685/197173797-f4a852e4-a045-4f5b-8771-d1f37ddc8654.png">

## What happens?
Generates this model:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/16304685/197173898-3ec3eeb1-6261-4f56-8624-d325272bbc6b.png">

## What were you expecting to happen?
Remove that import: 
<img width="747" alt="image" src="https://user-images.githubusercontent.com/16304685/197174282-5e0a0f42-501f-472e-a5f2-df6c39bff556.png">

## Any logs, error output, etc?
On build:
```bash
src/api/generated/cue/models/atividadeEconomicaDto.ts:10:15 - error TS2440: Import declaration conflicts with local declaration of 'AtividadeEconomicaDto'.

10 import type { AtividadeEconomicaDto } from './atividadeEconomicaDto';
                 ~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/api/generated/cue/models/atividadeEconomicaDto.ts:10
```

## What versions are you using?

**Operating System:** macOS Monterey 12.6
**Package Version:** v6.10.2

**Comment by anymaniax** [comment]
Will be in the next release

**Comment by ruiaraujo012** [comment]
> Will be in the next release

Thank you ;)

**Comment by anymaniax** [comment]
hey @ruiaraujo012  should be fixed with the last release

**Comment by ruiaraujo012** [comment]
thank you @anymaniax ;)
