### ISSUE TITLE
Redux Tool kit Query aka RTK Query support

### ISSUE THREAD

**Issue by SpaghettiC0des** [anymaniax/orval#634]
Hi! Is there a plan to support RTK Query in the future?

**Comment by anymaniax** [comment]
Hello @karlmarxlopez, they have a generator too so It's not planned for the moment. You can find it [here](https://redux-toolkit.js.org/rtk-query/usage/code-generation)

**Comment by karlmarxlopez** [comment]
> Hello @karlmarxlopez, they have a generator too so It's not planned for the moment. You can find it [here](https://redux-toolkit.js.org/rtk-query/usage/code-generation)

Yes, they have and I'm currently using it but it feels incomplete and lack's the configurability of Orval. Like splitting the type defs into a separate file.

**Comment by karlmarxlopez** [comment]
@anymaniax, I think it might be good if there's a documentation section for customizing or creating your own template?

**Comment by anymaniax** [comment]
@karlmarxlopez it's in the roadmap of the next major release to redo the doc and split completely the core to be able to create plugins easily. Right now it's possible but the API is not really good

**Comment by anymaniax** [comment]
Hello @karlmarxlopez, you can now check the new architecture and create your own client with the extracted core. The current version is `@orval/core@6.11.0-alpha.4`. If you do so I would be happy to add a section about your client in orval doc


You can now do something like this.

```ts
import query from '@orval/query';
import { defineConfig } from 'orval';

export default defineConfig({
  petstore: {
    output: {
       client: query() // query({type: 'svelte-query'}) for another query client,
     }
  }
});
```

so you could do exactly the same with your own client

**Comment by melloware** [comment]
No response from OP. Closing will reopen if PR is submitted.
