### ISSUE TITLE
index.ts for schemas not merged like in 6.9.6 and earlier

### ISSUE THREAD

**Issue by geekus** [anymaniax/orval#637]
## What are the steps to reproduce this issue?

1. Add two or more spec files to orval.config.js
2. Set schemas dir to the same dir for all specs, let's say `schemas`
3. Run orval.generate()

## What happens?
From 6.10.0 it seems like `schemas/index.ts` contains re-exports from the last spec only. For 6.9.6 and earlier it contained schema exports for all specs.

## What were you expecting to happen?
Behavior from 6.9.6 as described above.

## Any logs, error output, etc?
Nothing unusual.

## Any other comments?
Thanks for a great lib!

## What versions are you using?

**Operating System:** macOS 12.3.1
**Package Version:** Tested both 6.10.0 and 6.9.6 to compare behavior
**Browser Version:** N/A

**Comment by anymaniax** [comment]
should be fixed in the next release

**Comment by geekus** [comment]
Great, thanks!

**Comment by anymaniax** [comment]
hey @geekus should be fixed with the last release

**Comment by geekus** [comment]
Yes, just updated and tested. Looks good! Thanks again. 🚀
