### ISSUE TITLE
Dashes cause syntax errors

### ISSUE THREAD

**Issue by jfenske89** [anymaniax/orval#65]
## What are the steps to reproduce this issue?
1. Generate based on a Swagger document with a parameter name such as "name-like". Example:

```
          {
            "name": "name-like",
            "in": "query",
            "description": "name-like",
            "required": false,
            "type": "string"
          }
```

## What happens?
Code is generated with syntax errors. Example:

`export type getAllThingsUsingGETParams = { name-like?: string; page-number?: number; page-size?: number };`

## What were you expecting to happen?
The code to generate without syntax errors, by removing the dashes, replacing them with underscores, or using camelCase. Example:

`export type getAllThingsUsingGETParams = { name_like?: string; page_number?: number; page_size?: number };`

## Any logs, error output, etc?
N/A

## Any other comments?
N/A

## What versions are you using?
**Operating System:** MacOS
**Package Version:** 2.0.4
**Browser Version:** N/A

**Comment by anymaniax** [comment]
is it ok for you I had a single quote because if we replace by underscore or camelCase we don't follow your spec anymore

**Comment by jfenske89** [comment]
If that resolves the errors, then it sounds good to me. Thanks for looking into this.

**Comment by anymaniax** [comment]
should be fixed in the last release.
