### ISSUE TITLE
TypeScript error: Null values should not be allowed in FormData

### ISSUE THREAD

**Issue by mathiaswold** [anymaniax/orval#652]
Hi, thank you for this great package! I have an issue:

## What are the steps to reproduce this issue?

1. Run orval against an api with a mulitpart/form-data endpoint that contains fields with null types

## What happens?
TypeScript error:

`FormData.append(key, value)` only supports values of type Blob or string ([MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append))

![SCR-20221110-w0o](https://user-images.githubusercontent.com/45951843/201216211-9e684b7b-af06-4442-9361-56e278db9d3d.png)

Here is the `userWithGroupsRequest` type for reference:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/45951843/201218544-a66e5692-2865-4f31-8f4c-f00d2918b7a6.png">

## What were you expecting to happen?
The generated code should also check for null values in the if statements (add `&& <fieldName> !== null`)

## Any logs, error output, etc?

See image above

## Any other comments?

I'm guessing this should be added here: https://github.com/anymaniax/orval/blob/be4cf44dc08a9801112c12ffe7f24356d51ee76e/src/core/generators/formData.ts#L66-L71

## What versions are you using?
**Package Version:** 6.10.3

**Comment by anymaniax** [comment]
Will be fixed in the next release

**Comment by jalvaydev** [comment]
still experiencing this issue
