### ISSUE TITLE
React-query custom client example is wrong

### ISSUE THREAD

**Issue by la55u** [anymaniax/orval#654]
## The problem
I tried to solve the authentication problem (passing `Authorization` header in the app) when I noticed the following in the examples.
The custom-client [example](https://github.com/anymaniax/orval/blob/master/samples/react-query/custom-client/src/api/mutator/custom-client.ts) defines a `customClient` to use in queries, however the [auth.context.tsx file](https://github.com/anymaniax/orval/blob/master/samples/react-query/custom-client/src/auth.context.tsx#L8) imports a non existing `axios` instance.

## What were you expecting to happen?
This example should show how to use the custom client instead of `axios`.

## What versions are you using?

**Package Version:** 6.10.3.

_Thank you for your work!_

**Comment by anymaniax** [comment]
@la55u did an update thanks
