### ISSUE TITLE
TypeScript compilerOption target is not used

### ISSUE THREAD

**Issue by wouterkroes** [anymaniax/orval#671]
## What are the steps to reproduce this issue?

n/a

## What happens?

I noticed my tsconfig.json target is not read by Orval.

I created a pull request to add it: https://github.com/anymaniax/orval/pull/670

## What were you expecting to happen?

n/a

## Any logs, error output, etc?

n/a

## Any other comments?

n/a

## What versions are you using?

n/a

**Comment by anymaniax** [comment]
Which version do you use?

**Comment by wouterkroes** [comment]
"orval": "6.9.6"

**Comment by anymaniax** [comment]
can you try with `6.11.0-alpha.6` if you still have the problem?

**Comment by wouterkroes** [comment]
Sadly, I still have the issue with that version

```
� Start orval v6.11.0-alpha.6 - A swagger client generator for typescript
(node:12904) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
▲ [WARNING] "import.meta" is not available in the configured target environment ("es2015") and will be empty [empty-import-meta]

    src/helpers/orval/mutator/custom-instance.ts:17:11:
      17 │   baseUrl: import.meta.env.VITE_API_BASE_URL
```

Is it maybe because my tsconfig.json uses references? It is a [create-vue](https://github.com/vuejs/create-vue)/Vite project:

```
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.config.json"
    },
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.vitest.json"
    }
  ]
}
```

**Comment by anymaniax** [comment]
ok now I see

**Comment by wouterkroes** [comment]
Hmm, gave it a try with a simpler tsconfig.json

```
{
  "compilerOptions": {
    "module": "ESNext",
    "target": "ESNext"
  }
}
```


but sadly the same error. So the references it not the issue, i guess (?)

**Comment by anymaniax** [comment]
no no it's the way the file is compile you are right

**Comment by anymaniax** [comment]
Normally you don't have any side effects right?

**Comment by wouterkroes** [comment]
What exactly do you with side effects? In what context?

**Comment by anymaniax** [comment]
The code is well generated no? Without any issue? You just have the warning

**Comment by wouterkroes** [comment]
Yes, the code is well generated. It is not a blocking issue/bug

**Comment by anymaniax** [comment]
Will check and probably merge. Just afraid that it can cause some problems in some case

**Comment by anymaniax** [comment]
it's not exactly the same since it's the build setup for esbuild that you modify here

**Comment by wouterkroes** [comment]
@anymaniax could you have give a status update?

**Comment by anymaniax** [comment]
Hello @wouterkroes, sorry I didn't have the time to check yet. I thought it wasn't urgent since it's only a warning.

**Comment by arthurfiorette** [comment]
@anymaniax anything new? bug continues up to latest version (6.11.1)

**Comment by binghuis** [comment]
When will this issue be fixed? The issue still exists.（6.12.1）

**Comment by tortilaman** [comment]
Not sure if this is useful, but I am encountering the same issue:

```
🍻 Start orval v6.14.1 - A swagger client generator for typescript
flumeHealth: Cleaning output folder
▲ [WARNING] "import.meta" is not available in the configured target environment ("es2015") and will be empty [empty-import-meta]

    src/axiosClient.ts:4:11:
      4 │   baseURL: import.meta.env.VITE_API_URL,
        ╵            ~~~~~~~~~~~
```

I'm building my app with Vite. I can provide additional details if it's helpful.

**Comment by usersina** [comment]
Same issue here with Vite & React.

```bash
🍻 Start orval v6.15.0 - A swagger client generator for typescript
evo: Cleaning output folder
▲ [WARNING] "import.meta" is not available in the configured target environment ("es2015") and will be empty [empty-import-meta]

    src/api/mutator/custom-instance.ts:4:11:
      4 │   baseURL: import.meta.env.VITE_SERVICE_URL,
        ╵            ~~~~~~~~~~~

🎉 evo - Your OpenAPI spec has been converted into ready to use orval!
✨  Done in 4.64s.
```

Here's my config FWIW:

```ts
// orval/config.ts

import { defineConfig } from "orval";

export default defineConfig({
  evo: {
    input: {
      target: "http://localhost:3002/v3/api-docs",
    },
    output: {
      mode: "tags",
      schemas: "../src/generated/models/user-service",
      client: "axios",
      target: "../src/generated/api/user-service",
      mock: false,
      prettier: true,
      clean: true,
      tsconfig: "../tsconfig.json",
      packageJson: "../package.json",
      override: {
        useDates: true,
        mutator: {
          path: "../src/api/mutator/custom-instance.ts",
          name: "customInstance",
        },
      },
    },
  },
});
```

**Comment by kabaehr** [comment]
In which release should this be included?
I still have the issue with 6.22.1, is this to be expected?
