### ISSUE TITLE
Parse array with `uniqueItems: true` as a `Set`

### ISSUE THREAD

**Issue by dawsonbooth** [anymaniax/orval#672]
## What are the steps to reproduce this issue?

1. Add `uniqueItems: true` to a field in the OpenAPI doc
2. Run Orval

## What happens?

The field comes back as an array.

## What were you expecting to happen?

n/a

## Any logs, error output, etc?

n/a

## Any other comments?

As in the example of parsing dates as `Date` instances, it would be helpful to be able to parse an array of items that are known to be unique as a `Set` and have the generated type match that.

## What versions are you using?

6.10.2

**Comment by anymaniax** [comment]
Hello @dawsonbooth, can you give me a quick example of what you expect?

**Comment by dawsonbooth** [comment]
I have a few endpoints that return a list of available actions to the user as an array. I know these actions to be unique within the array and have noted the return type as such in the `swagger.json` by setting `uniqueItems: true`, so I would like to use that information to parse the array as a `Set` upon receiving the data.

I know that I can just convert the array ad hoc for each specific query that I want, but it would be nice to be able to do this automatically for any items marked with `uniqueItems: true` and have the generated types from running orval use `Set` as well.

I figure this could be done either automatically by way of a flag in the orval config file, or it can be handled in the response parsing side similar to the `Date` parsing example in the docs.

**Comment by dawsonbooth** [comment]
On second thought, I'm realizing that this would be much better suited as a discussion item instead of an issue!
https://github.com/anymaniax/orval/discussions/674
