### ISSUE TITLE
Axios: Mutator is parsing commented out lines

### ISSUE THREAD

**Issue by rajesh-vishwa** [anymaniax/orval#673]
## What are the steps to reproduce this issue?
```
export default defineConfig({
  scgapi: {
    input: { target: "https://scg-nest-api.vercel.app/api-json" },
    output: {
      target: "./services/generated-api.ts",
      client: "axios",
      schemas: "./services/model",
      mode: "tags-split",
      prettier: true,
      override: {
        title: (title) => `${title}Service`,
        mutator: {
          path: "./http-client/api.client.ts",
          name: "axiosInstance",
        },
      },
    },
  },
});
```
1. …
2. …
3. …

## What happens?

```
const playerControllerAddPlayer = (
    createPlayerDto: BodyType<CreatePlayerDto>,
    options?: SecondParameter<typeof axiosInstance>
  ) => {
    return axiosInstance<PlayerControllerAddPlayer201>(
      {
        url: `/player/add`,
        method: "post",
        headers: { "Content-Type": "application/json" },
        data: createPlayerDto,
      },
      options
    );
  };
```
…

## What were you expecting to happen?

…

## Any logs, error output, etc?

…

## Any other comments?

…

## What versions are you using?

**Operating System:** …
**Package Version:** …
**Browser Version:** …

**Comment by anymaniax** [comment]
Hello @rajesh-vishwa, can I also get a copy of your mutator file to see where is the problem?

**Comment by rajesh-vishwa** [comment]
> Hello @rajesh-vishwa, can I also get a copy of your mutator file to see where is the problem?

`import Axios, { AxiosError, AxiosRequestConfig, HeadersDefaults } from "axios";

import { User } from "../types/user.type";
import { getStoredUser } from "../utils/user-storage";

export const AXIOS_INSTANCE = Axios.create({
  baseURL: process.env.NEXT_API_URL,
});

export type FailResponse = {
  readonly success: boolean;
  readonly message: string;
};

export type SuccessResponse<T> = {
  readonly success: boolean;
  message: string;
  value: T;
};

export type ApiResponse<T> = FailResponse | SuccessResponse<T>;

export const isSuccessResponse = <T>(
  fa: ApiResponse<T>
): fa is SuccessResponse<T> => fa.success === true;

export const isFailResponse = <T>(fa: ApiResponse<T>): fa is FailResponse =>
  fa.success === false;

type headers = {
  "Content-Type": string;
  Accept: string;
  Authorization: string;
};

AXIOS_INSTANCE.defaults.headers = {
  "Content-Type": "application/json",
  Accept: "application/json",
} as headers & HeadersDefaults;

export const axiosInstance = <T>(
  config: AxiosRequestConfig,
  options?: AxiosRequestConfig
): Promise<ApiResponse<T>> => {
  const source = Axios.CancelToken.source();
  const promise = AXIOS_INSTANCE({
    ...config,
    ...options,
    cancelToken: source.token,
  }).then(({ data }) => data);

  // @ts-ignore
  promise.cancel = () => {
    source.cancel("Query was cancelled");
  };

  return promise;
};

// Adding Authorization header for all requests

AXIOS_INSTANCE.interceptors.request.use(
  (config) => {
    const user = getStoredUser();
    if (user) {
      // Configure this as per your backend requirements
      config.headers!["Authorization"] = user.accessToken;
    }
    return config;
  },
  (error) => {
    return Promise.reject(error);
  }
);

export function getJWTHeader(user: User): Record<string, string> {
  return { Authorization: `${user.accessToken}` };
}

export default axiosInstance;

// In some case with react-query and swr you want to be able to override the return error type so you can also do it here like this
//export type ErrorType<Error> = AxiosError<Error>;
// In case you want to wrap the body type (optional)
// (if the custom instance is processing data before sending it, like changing the case for example)
export type BodyType<BodyData> = CamelCase<BodyType>;
//export type BodyType<BodyData> = BodyType;
`

**Comment by anymaniax** [comment]
I am not sure to understand what do expect here.

**Comment by vyrotek** [comment]
@anymaniax I think I'm hitting the same issue as them. The problem I'm seeing is that the generated code is still trying to import BodyType and ErrorType when they don't exist. It's documented as being optional and so we expect to not have to export anything.

**Comment by anymaniax** [comment]
Normally should be the case. Do you have an export of a type or interface BodyType in your file?

**Comment by KaanMol** [comment]
I had the same issue and have figured out how it came. It looks like Orval ignores if the line is a comment or not. By removing the comment and regenerating it, it fixes the problem

**Comment by melloware** [comment]
This is because in mutator.ts its looking for this

```js
  const hasErrorType =
    rawFile.includes('export type ErrorType') ||
    rawFile.includes('export interface ErrorType');

  const hasBodyType =
    rawFile.includes(`export type ${BODY_TYPE_NAME}`) ||
    rawFile.includes(`export interface ${BODY_TYPE_NAME}`);

```

Which does not account for commented out lines.
