### ISSUE TITLE
Path Parameters Are Not Encoded

### ISSUE THREAD

**Issue by lew** [anymaniax/orval#679]
## What are the steps to reproduce this issue?

1. Create a minimal OpenAPI example like    
```json
{
  "info": {
    "title": "My API",
    "version": "1.0.0"
  },
  "openapi": "3.0.0",
  "paths": {
    "/test/{parameter}": {
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "parameter",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}

```
2. Generate the functions.
3. Use a parameter with special characters in above example.

## What happens?

The parameter `parameter` is just string concatenated into the URL:
```ts
export const getTestParameter = <TData = AxiosResponse<void>>(
  parameter: string,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/test/${parameter}`, options)
}
```

As a result, requests fail. 

## What were you expecting to happen?

Strings in the path fragment must be encoded 

```ts
export const getTestParameter = <TData = AxiosResponse<void>>(
  parameter: string,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/test/${encodeURIComponent(parameter)}`, options)
}
```

## Any other comments?

URL encoding should take place here because neither the rest of the app should care about encoding nor is it possible to later encode a fully constructed URL. 

A programmer would typically prefer to use a method like this to avoid having to worry about internals:
```ts
const someParam = 'special[s]/?test'
const results = useGetTestParameter(someParam)
```

This bug happens at different places in the generated code.

## What versions are you using?

    "orval": "6.11.0-alpha.6"

**Comment by lew** [comment]
I believe it is a good idea not to allow the function's user to provide input that breaks the execution.
When a user enters a path segment with a character like `/`, it completely changes the resulting URI; when they enter a path segment with a reserved character, it can result in invalid HTTP requests. 

The [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-2.4) explicitly mentions when to encode the URI:
> Under normal circumstances, the only time when octets within a URI
   are percent-encoded is during the process of producing the URI from
   its component parts.  This is when an implementation determines which
   of the reserved characters are to be used as subcomponent delimiters
   and which can be safely used as data.  Once produced, a URI is always
   in its percent-encoded form.

In my opinion, this is within orval's code in lines such as
```ts
  return axios.get(`/test/${parameter}`, options)
```

What are the downsides to encoding in this place?

Side note:    
The [querystring](https://nodejs.org/api/querystring.html#querystringstringifyobj-sep-eq-options) built-in node module transparently translates URI segments, for example: 
```ts
import querystring from 'querystring'

const qs = querystring.stringify({ param1: 'some&value', param2: 'some other value' })

console.log(qs)
// param1=some%26value&param2=some%20other%20value
```

**Comment by lukaw3d** [comment]
Some related docs and issues:
- https://generator.swagger.io/ always encodes slashes
- spec defines allowReserved option for query parameters https://swagger.io/docs/specification/describing-parameters/#allowReserved
- but not for path parameters :/
  - https://github.com/swagger-api/swagger-js/pull/2597
  - https://github.com/OAI/OpenAPI-Specification/issues/892

**Comment by anymaniax** [comment]
We could add it conditionally with an option in the orval config if it's ok for you

**Comment by Maxim-Mazurok** [comment]
We used to generate API with openapi-generator-cli using `typescript-axios` template.
It had this:
```ts
const localVarPath = `/api/v1/search/{searchTerm}`.replace(`{${"searchTerm"}}`, encodeURIComponent(String(searchTerm)));
```

Now with orval we got a bug when user tried to search for URL. Would be great to have this option.
