### ISSUE TITLE
The plus sign ("+") is stripped in enums

### ISSUE THREAD

**Issue by guyariely** [anymaniax/orval#689]
## What are the steps to reproduce this issue?
 
Use the following schema in a valid OpenAPI spec:
 
```yaml
Grade:
  type: string
  enum:
    - A+
    - A
    - A-
```
 
## What happens?
 
Orval generates the following object (note the missing "+" sign):
 
```ts
export const Grade = {
  A: "A+",
  A: "A",
  "A-": "A-",
} as const;
```
 
## What were you expecting to happen?
 
For the generated object to look like this:
 
```ts
export const Grade = {
  "A+": "A+",
  A: "A",
  "A-": "A-",
} as const;
```
 
## Any logs, error output, etc?
 
Orval does not output any error about this.
 
## What versions are you using?
 
**Package Version:** 6.10.3

**Comment by anymaniax** [comment]
Hello @guyariely, it should be fixed on `orval@alpha` can you try it?

**Comment by guyariely** [comment]
@anymaniax I tried it out and it works as expected, thanks!
