### ISSUE TITLE
Types are not generated correctly for nullable enums

### ISSUE THREAD

**Issue by denisorehovsky** [anymaniax/orval#702]
I have these two nullable fields:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/9641784/207851236-61f6435d-9ae7-4d61-8c5f-3ac91fb4a483.png">

When I generate types, I get this result:
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/9641784/207851367-33764c93-c92e-40bc-9e0c-00b35c43c526.png">

As you can see, the fields are not nullable.

I even upgraded to the latest orval version. No result. Am I doing something wrong?

**Comment by anymaniax** [comment]
Can you try with orval@alpha

**Comment by denisorehovsky** [comment]
@anymaniax Looks like alpha is working:
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/9641784/207857209-c7b50b59-278f-4845-80be-67d73cf7fc80.png">
