### ISSUE TITLE
WEB Playground

### ISSUE THREAD

**Issue by jozef-slezak** [anymaniax/orval#718]
Please provide Orval WEB Playground -(similar to what GraphQL Code Generator has on the web page https://the-guild.dev/graphql/codegen)
* monaco editor for swagger with example swagger/openapi
* monaco editor for generated typescript

<img width="575" alt="image" src="https://user-images.githubusercontent.com/16844103/210635023-7240413e-5c9a-4f40-a753-ef0f4823a13e.png">

**Comment by anymaniax** [comment]
Good idea should be possible

**Comment by jozef-slezak** [comment]
Perfect, I believe it will help quick try out without instalation.

When you prepare Orval browser build ten I could integrate Orval to iteria.tools web.

**Comment by anymaniax** [comment]
I use [this](https://github.com/anymaniax/orval/blob/master/docs/src/pages/api/generate.js) so I don't know if it can run in the browser 😅. I never tested that case tbh.
