### ISSUE TITLE
Provide way to convert dates

### ISSUE THREAD

**Issue by bartlangelaan** [anymaniax/orval#723]
First of all, thanks for this awesome library! It's very easy to setup and works great.

In the documentation there is a mention about how you can use a response transformer to convert all dates to real Date instances. While this approach is okay, it will greatly reduce performance on endpoints that return a big amount of data. That's why we are excluding some endpoints from this transformer, but that's not ideal.

Due to the openapi spec, we already know which endpoints and properties will contain dates, so it must be possible to do this for dates only. The openapi-generator is able to generate functions that map dates to their expected type.

It would be awesome if Orval was also able to do this - I think it can make a huge impact on projects that work with a lot of data.

**Comment by melloware** [comment]
You can already do this. See: https://orval.dev/reference/configuration/output#usedates

I use this in production.

**Comment by melloware** [comment]
Oh you are saying it doesn't perform fast enough.

**Comment by jamalsoueidan** [comment]
maybe json.parse handle this for you?
```
JSON.parse = function (data) {
  return parse(data, dateParser);
};

```

**Comment by bartlangelaan** [comment]
No, it's still too slow when having a response with millions of objects. It performs fine when it doesn't have to perform a regex on every string.

Some endpoints contain dates, some don't. It is currently wasting time and resources on endpoints that will never contain dates. And a regex wouldn't even be needed if we know beforehand which properties are dates.

I fixed it by preventing the regex transform to happen on certain endpoints (hardcoded exclusions) but of course that is not ideal.

**Comment by melloware** [comment]
So if your performance hit is the regex call you can write your own custom isdate function if for example you KNOW the fields that are dates for example.


```js
function isIsoDateString(key:string, value: any): boolean {
   return value && typeof value === 'string' && key.endsWith('date');
 }
```
That would just see if the JSON property ended with the word date or you could hardcode your fields that are dates etc if truly you are juts trying to save the REGEX.  But at SOME point something has to know its a date to call the `new Date(` on it right?
