### ISSUE TITLE
Broken footer section in modes: tags, split-tags

### ISSUE THREAD

**Issue by yekver** [anymaniax/orval#736]
## What are the steps to reproduce this issue?

1. Use `axios` adapter
2. Use mode `tags` or `split-tags`

## What happens?

Empty footer section will be generated
```javascript
export const someApi => {
 export const listPets = () => { ... };
 
// footer
  return {}
}
```

## What were you expecting to happen?

Footer section should be generated as expected

```javascript
export const someApi => {
  export const listPets = () => { ... };
 
// footer
  export type ListPetsResult = NonNullable<Awaited<ReturnType<typeof listPets>>>;
  return { listPets }
}
```

## Any other comments?

Broken since [release 6.10.0](https://github.com/anymaniax/orval/releases/tag/v6.10.0)

**Comment by anymaniax** [comment]
Thanks @yekver I cannot check before next week but I will as soon as I can

**Comment by anymaniax** [comment]
hello @yekver, with 6.11.1 everything seems to work correctly

**Comment by JoeHillyard** [comment]
I am still experiencing this issue on any version >6.9.6 - both the footer is empty and result types are not being generated. Any help would be appreciated!

**Comment by melloware** [comment]
@JoeHillyard can you provide your OpenApI json and config you are using that this happens?  It's the only way we can see what is going on.

**Comment by melloware** [comment]
Will close from now unless someone can provide a reproducer with 6.20.0
