### ISSUE TITLE
Add option to filter out generated endpoints and dtos

### ISSUE THREAD

**Issue by mat-mik** [anymaniax/orval#739]
## What are the steps to reproduce this issue?

1. Have legacy system with hundreds of endpoints
2. Generate schemas

## What happens?

Hundreds/Thousands of files are generated.

## What were you expecting to happen?

Generate only a subset of endpoints and dtos. Maybe by OpenAPI `tags`? Configuration could look like:
```ts
input: {
      target: 'xxx',
      filter: {
            containsTags: ['abc']
      }
},
```

## What versions are you using?

**Package Version:** 6.11.1

**Comment by melloware** [comment]
Closing as this has been implemented.
