### ISSUE TITLE
Axios 1.2.3 breaks clients generated by orval

### ISSUE THREAD

**Issue by soulchild** [anymaniax/orval#740]
## What are the steps to reproduce this issue?

1. Upgrade axios from 1.2.2 to 1.2.3

## What happens?

Axios 1.2.3 introduced changes to its types which break clients generated by Orval:

```ts
error TS2345: Argument of type '{ headers?: AxiosRequestHeaders | undefined; url?: string | undefined; method?: string | undefined; baseURL?: string | undefined; transformRequest?: AxiosRequestTransformer | AxiosRequestTransformer[] | undefined; ... 31 more ...; formSerializer?: FormSerializerOptions | undefined; }' is not assignable to parameter of type 'AxiosRequestConfig<any>'.
Types of property 'headers' are incompatible.
  Type 'AxiosRequestHeaders | undefined' is not assignable to type 'AxiosRequestHeaders'.
    Type 'undefined' is not assignable to type 'AxiosRequestHeaders'.
      Type 'undefined' is not assignable to type 'Partial<RawAxiosHeaders & MethodsHeaders & CommonHeaders>'.
```

## What were you expecting to happen?

Axios patch-level upgrades shouldn't break existing code. ;-)

`openapi-generator`, `zodios` and a couple of other libraries are broken as well. There's an ongoing discussion over at https://github.com/axios/axios/pull/5420

**Comment by soulchild** [comment]
Seems like there is already a PR underway which is supposed to fix this: https://github.com/axios/axios/pull/5486

**Comment by melloware** [comment]
This is already fixed in Axios and can be closed.
