### ISSUE TITLE
Add Fetch API

### ISSUE THREAD

**Issue by hahanein** [anymaniax/orval#745]
Would you be interested in a pull request adding the Fetch API as a standard client?

**Comment by gkweb** [comment]
Please add 👀

**Comment by anymaniax** [comment]
Hello guys, you can use a mutator to do that. Just like [this](https://github.com/anymaniax/orval/blob/master/samples/react-query/custom-client/src/api/mutator/custom-client.ts).

**Comment by meixger** [comment]
Very happy with the mutator. Works great with within Nuxt 3!

**Comment by gkweb** [comment]
There is actually an example of a custom client using fetch in the docs like shared above. 

https://orval.dev/guides/custom-client

**Comment by michalusio** [comment]
Agree with @hahanein.
The default options should require no additional packages, and so Fetch should be the default.

**Comment by anymaniax** [comment]
We could for sure add a fetch client directly but for the moment it cannot be the default client since it would be a breaking change
