### ISSUE TITLE
React Query 

### ISSUE THREAD

**Issue by ngregrichardson** [anymaniax/orval#749]
Hi, sorry for not using the issue template -- I just started using this and have loved it so far, but I have a few questions. For context, I'm using it with React Query.

1. Is there a way to change how the names of the query hooks generate? The way I'd want to is to remove the controller names from them.
2. Is there a way to make it so the whole axios request isn't returned in `data` from the query hook, but just the `data` parameter from inside of it?

If these aren't possible, that's okay, but I just wondered if I was missing something.

Thanks!

**Comment by Mistes974** [comment]
Hi @ngregrichardson,

Regarding your second question, I found a solution using `axios.interceptors.response`, however, I would like to inquire if there is a better alternative available...

```
axios.interceptors.response.use(function (response) {
    // Any status code that lie within the range of 2xx cause this function to trigger
    // Do something with response data
    return response?.data;
}, function (error) {
    // Any status codes that falls outside the range of 2xx cause this function to trigger
    // Do something with response error
    return Promise.reject(error);
});
```

**Comment by ngregrichardson** [comment]
That looks like it would work, but it probably wouldn't change the typings right?

**Comment by anymaniax** [comment]
Hello @ngregrichardson, for point 2 you can use a [mutator](https://orval.dev/reference/configuration/output#mutator) and for point 1 I am not sure to understand. The name of the hooks generated are based on the operationId you can modify them with [this](https://orval.dev/reference/configuration/output#operationname)

**Comment by ngregrichardson** [comment]
I will look into those, thanks! Like I said, I wasn't able to easily find those in the docs, so I was just wondering if I was missing them. Thanks!

**Comment by anymaniax** [comment]
In conclusion the doc need to be improved 😃. If you have the time, help is appreciated

**Comment by vyrotek** [comment]
@anymaniax We've been looking for a solution to #1 as well but stumbled onto a blocker with using the `operationName` override you suggested.

Currently, Orval generates a type name to represent the input params for an operation. (e.g. `AccountsGetUserParams`) If you use the operationName override and provide a new operation name of "GetUser" then Orval will generate `GetUserParams` for the input param type.

We too are trying to remove the controllers from the operation names. In order to avoid name conflicts across controllers, we use the `tags` output mode to group methods from the same controller together. 

The problem is that the params type is not grouped with the generated tag modules. All models are kept in a single common module which results in type conflicts! This isn't an issue for response types because those are not renamed when overriding the operation name.

Could we have the params type generation behave like the response types and keep their original full qualified names?

**Comment by anymaniax** [comment]
Hello @vyrotek can you give me an example with code sandbox to be sure I understood well the problem?

**Comment by vyrotek** [comment]
Hi @anymaniax, thanks for your time.

Hopefully this illustrates the issue.
https://codesandbox.io/p/sandbox/cool-fire-wto6rv

`swagger.json` was generated off of 2 controllers each with a single endpoint.
`/Things/FindSomething?search=aaaa` tagged in swagger.json with `Things` (Note: ?search)
`/Widgets/FindSomething?filter=bbbb` tagged in swager.json with `Widgets` (Note: ?filter)

`orval.config.ts` is configured to split output based on tags and also uses `operationName` to rename the operations and strip the controller prefix from the name. In this example, the override results in two 

Note: (Working as expected)
`\src\app\api\models\thingsFindSomethingResponse.ts` was **not renamed** with the new operation name.
`\src\app\api\models\widgetsFindSomethingResponse.ts` was **not renamed** with the new operation name.

Issues:
`\src\app\api\models` contains only a single `findSomethingParams.ts` which **was renamed** and only has a `filter` field.
`\src\app\api\models\index.ts` contains 2 references to the same findSomethingParams.
`\src\app\api\things.ts` has a `findSomething` operation using the single `FindSomethingParams`
`\src\app\api\widgets.ts` has a `findSomething` operation using the single `FindSomethingParams`

Expected:
`\src\app\api\models\thingsFindSomethingParams.ts` with a `search` field.
`\src\app\api\models\widgetsFindSomethingParams.ts` with a `filter` field.

**Comment by anymaniax** [comment]
Hello @vyrotek, I checked your codesandbox. The problem right now is that when you use operationName property to change operationId it became the new unique Id. And in your case it’s not unique anymore.

**Comment by vyrotek** [comment]
@anymaniax What was surprising is that the other response models didn't change too though. Those stayed the full original name and not the new operation name.

Seems inconsistent and unexpected to have it behave the way it does now?

**Comment by anymaniax** [comment]
@vyrotek the others stay like that because they are part of the schemas and they have also a name that is separated from the operation Id and I have no direct way to link them together. 

For the second part, currently there is no way to split the models by tag too

**Comment by vyrotek** [comment]
@anymaniax  Ah, I understand.

 I've seen other Swagger/TS libraries just generate operation inputs as in-lined types instead. That would technically get around this conflict. Would you be open to an option like that? 🤔

Alternatively, the brute-force option would be to provide something similar to operationName but for every type and allow a custom name to be provided for query and response models. I don't think this exists, right?

**Comment by anymaniax** [comment]
@vyrotek if you find a good way to add it sure!

**Comment by melloware** [comment]
@vyrotek no response in 7 months so going to close this ticket. Happy to reopen if a solution is provided.
