### ISSUE TITLE
vue-query or @tanstack/vue-query? 

### ISSUE THREAD

**Issue by gkweb** [anymaniax/orval#757]
## What are the steps to reproduce this issue?

@tanstack/vue-query appear to be the library for vue-query moving forwards. See: https://github.com/DamianOsipiuk/vue-query/issues/252

## What happens?

Generation output is vue-query.

## What were you expecting to happen?

Should be latest vue-query approach.

## Any logs, error output, etc?

none

## Any other comments?

-

## What versions are you using?

-

**Comment by anymaniax** [comment]
Hello @gkweb, you just have to install the new dependency `@tanstack/vue-query` and it should work directly

**Comment by gkweb** [comment]
> Hello @gkweb, you just have to install the new dependency `@tanstack/vue-query` and it should work directly


@anymaniax just to confirm this is in the latest 6.11.1 release?

I've noticed you've made the changes on master here - but can't see a tagged release with this capability.

Many thanks

**Comment by anymaniax** [comment]
Haha my bad completely forgot that’s it’s not released yet 😅

**Comment by gkweb** [comment]
> Haha my bad completely forgot that’s it’s not released yet 😅

eagerly awaiting the next release then! 

Cheers and great utility you've created!

**Comment by anymaniax** [comment]
@gkweb  Released with `6.12.0`
