### ISSUE TITLE
inferring type using custom axios 

### ISSUE THREAD

**Issue by ido-journey** [anymaniax/orval#763]
## What are the steps to reproduce this issue?

setup Orval using react query and custom Axios

## What happens?

hooks are using "unknown" type when calling usecustomaxios: 
``` 
export const useSomeHook = () => {
  const listSomething = useCustomAxios<**unknown**>();

  return (params?: SomeParams, signal?: AbortSignal) => {
    return listSomething({ url: `/something`, method: 'get', params, signal });
  };
};
```

## What were you expecting to happen?

type should be inferred

## Any other comments?

feels like I'm doing something wrong and it is achievable to have that type, thanks for the help in advance

## What versions are you using?

**Operating System:** macOS
**Package Version:** 6.9.0
**Browser Version:** chrome 109.0.5414.119

**Comment by melloware** [comment]
Feels like something wrong with your swagger or your setup. I have never seen this issue using Orval on multiple projects. Will reopen if you can provide a reproducer using 6.20.0
