### ISSUE TITLE
useInfiniteQuery: pageParams are overridden in queryFn when trying to implement infinite scroll functionality.

### ISSUE THREAD

**Issue by james-altis** [anymaniax/orval#765]
Might be my specific use case, but I can't seem to increment the pageParam in my infinite query. It gets overidden by the rest operator in the queryFn.

## What are the steps to reproduce this issue?

Relevant orval config  
```typescript     
operations: {
  get_all_utterances_for_conversation_paginated: {
      query: {
        useQuery: true,
        useInfinite: true,
        useInfiniteQueryParam: "page", // <----- I want to increment this
      },
    },
  },
```
Generated queryFn
```typescript
  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUtterancesForConversationPaginated>>> = ({ pageParam }) => getAllUtterancesForConversationPaginated(orgUuid,conversationUuid,{ page: pageParam, ...params }, requestOptions);
```

Request
```typescript
export const getAllUtterancesForConversationPaginated = (
    orgUuid: string,
    conversationUuid: string,
    params?: GetAllUtterancesForConversationPaginatedParams,
    options?: SecondParameter<typeof customInstance>,) =>  {
    console.log(params?.page) // <------- this doesn't  increment. 
      return customInstance<UtteranceReadPaginated>(
      {url: `/api/org/${orgUuid}/conversation/${conversationUuid}/utterances-paginated`, method: 'get',
        params 
    },
      options);
    }
```

## What happens?

The pageParam does not update as expected because it is overridden by the rest operator. 

```typescript
  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUtterancesForConversationPaginated>>> = ({ pageParam }) => getAllUtterancesForConversationPaginated(orgUuid,conversationUuid,{ page: pageParam, ...params }, requestOptions);  // <------ HERE
```
…

## What were you expecting to happen?
I think the `...params` rest operator should go before the pageParam, like this:

```typescript
{ ...params, page: pageParam,}
```
This way we can update the page param, and spread all other params into the request

…

## Any logs, error output, etc?

…

## Any other comments?

…

## What versions are you using?

**Operating System:** …
**Package Version:** …
**Browser Version:** …

**Comment by anymaniax** [comment]
hello @james-altis, it shouldn't be overidded if you don't pass the page into the params

**Comment by SamyZog** [comment]
> hello @james-altis, it shouldn't be overridden if you don't pass the page into the params

what if the query initially needs a 'page' parameter for the first request?
