### ISSUE TITLE
Custom override file for error handling? Core/Query

### ISSUE THREAD

**Issue by gkweb** [anymaniax/orval#772]
How can I specify a custom override file that sits outside of the ones you've provided?

For example I want to be able to specify a custom error handler file. 

```typescript
query: {
  errorHandler: {
      path: './src/some-api-client/overrides/error.ts',
      name: 'useOnError',
    },
}
```

Custom options appear to be heavily baked such that I can't pass in arguments to the custom options function easily by modifying the generator.

https://github.com/anymaniax/orval/blob/c2554a7bebf33d0ce3d706378360faa928fcd140/packages/query/src/index.ts#L785

A use case I have here is that I need an error handler that has access to the vue context. 

This might be handled like so: 

```typescript
const vm = getCurrentInstance() // vue
const customOptions= someOptions({ ... }, { vm })

// someOptions
export function someOptions(options, { vm }) {
options.onError = useOnError(vm)
}

// OR

const vm = getCurrentInstance() // vue
const customOptions= someOtherCustomOptions({ ... })
customOptions.onError = useOnError(vm)
```

This is really simple to do but because of the baked function arguments in the options override, the output is unpredictable. 

**Either:**
1. Is it possible to specify custom override files? (and how??) 
2. Can a standard error handler override be added? I feel there is definitely a use case for other users.

**Comment by anymaniax** [comment]
Hello @gkweb, I am not sure to understand what exactly you want to do. If you want to have the customOptions like tanstask query you can add `requestOptions:false` that will remove the possibility to have a second argument in your mutator or pass custom options to your axios instance. If you want to customize a query option you can also provide a mutator to [queryOptions](https://orval.dev/reference/configuration/output#queryoptions)  in your orval config

**Comment by gkweb** [comment]
> Hello @gkweb, I am not sure to understand what exactly you want to do. If you want to have the customOptions like tanstask query you can add `requestOptions:false` that will remove the possibility to have a second argument in your mutator or pass custom options to your axios instance. If you want to customize a query option you can also provide a mutator to [queryOptions](https://orval.dev/reference/configuration/output#queryoptions) in your orval config

Hey @anymaniax, this might make some more sense to you. How can I add an override file and use this in my own implementation. An example of how this will look using the example from the docs. 

Thanks

```typescript
// orval.config.ts

import {defineConfig} from 'orval'

export default defineConfig({
   petstore: {
     output: {
       override: {
         query: {
           queryOptions: {
             path: './api/query/custom-query-options.ts',
             name: 'customQueryOptionsFn',
             // default: true
           },
           // This is a custom query override - The file will be automatically imported and have a reference available
           errorHandler: {
             path: './api/query/error-handler.ts',
             name: 'useOnError',
            }
         },
       },
     },
   },
 });

// In my own client generator
`options.onError = ${overrides.errorHandler.name}(vm)`

// Which outputs:
options.onError = useOnError(vm)

```

**Comment by anymaniax** [comment]
The only solution here is to have custom query options like the following that always pass your custom onError function.

#### orval.config.ts
```ts
import { defineConfig } from 'orval';

export default defineConfig({
  petstore: {
    output: {
      mode: 'split',
      target: 'src/api/endpoints/petstoreFromFileSpecWithTransformer.ts',
      schemas: 'src/api/model',
      client: 'react-query',
      mock: true,
      override: {
        query: {
          queryOptions: {
            path: './src/api/mutator/custom-query-options.ts',
            name: 'useCustomQueryOptions',
          },
        },
      },
    },
    input: {
      target: './petstore.yaml',
    },
  },
});
```


#### custom-query-options.ts
```ts
export const useCustomQueryOptions = <TOptions>(
  options: TOptions,
): TOptions => {
  return {
    onError: () => {
      // handle your error
    },
    ...options,
  } as const;
};

```

or you can also do it with the queryClient from tanstack query too

```ts
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      onError: (error) => {
        // handle error
      },
    },
  },
});
```

**Comment by gkweb** [comment]
> The only solution here is to have custom query options like the following that always pass your custom onError function.
> 


Thanks @anymaniax, and yeah this doesn't match the requirement. I suspect you may need to split up the query package soon as the way they are typed and implementations might vary quite a bit. In this use case we need the vue context to be in the error handlers scope.
