### ISSUE TITLE
Orval updates files that did not change

### ISSUE THREAD

**Issue by cassis163** [anymaniax/orval#780]
## What are the steps to reproduce this issue?

1. Run `npm run generate-api`
2. Maybe add and commit the changes
3. Run it `npm run generate-api` again
4. Notice that some files are updated, but no real changes are present

## What happens?
Running Orval applies changes to objects that have not changed at all. All it does is shuffle some fields.

## What were you expecting to happen?
Orval should leave these files alone.

## Any logs, error output, etc?
![image](https://user-images.githubusercontent.com/42798012/221619262-40657006-5c02-410f-a7c4-9083d8bd2f0a.png)

## What versions are you using?

**Package Version:** 6.10.3

**Comment by marko-hologram** [comment]
Similar issue with things being shuffled around was reported here https://github.com/anymaniax/orval/issues/703, but that one is for MSW mocks.

**Comment by arlyon** [comment]
Yes, I think the underlying issue is the same.

**Comment by melloware** [comment]
Fixed in this PR: https://github.com/anymaniax/orval/pull/965
