### ISSUE TITLE
Use MSW generator as a standalone tool

### ISSUE THREAD

**Issue by marko-hologram** [anymaniax/orval#781]
## Feature Request

Hey, first of all, love the project and it seems to be robust. It doesn't fit my needs 100%, but I've tried it just to test it and it is really good. One thing that I would love is the ability to only generate MSW mocks. I'm using a different API client generator that suits my needs a bit better and I already set it up for my needs, but that one doesn't have MSW mock generation. I've come across orval as a great MSW mock generator, but unfortunately it seems to be tied to API client generation and cannot be used standalone or at least I haven't found a way to do it.

Is there a way to just generate MSW mocks without generating everything else? I do understand that TS types need to be generated and are then imported into the MSW mock file so I guess it does depend on some existing generator, but it would be great if MSW generator could be used as a standalone tool. I'm also fine with running orval and then potentially just deleting some files if that will make all of this work, but I didn't see it as a viable option in my limited time spent trying this out. Maybe I just overlooked something 😄

P.S. I know this is not really an "issue", but I thought it would get more traction being opened as an issue instead of a "discussion". Feel free to convert it to a discussion if you think that's more appropriate.

**Comment by melloware** [comment]
I don't think this will be implemented so closing for now. Happy to re-open if someone donates a PR.
