### ISSUE TITLE
Redundant {...} in generated file

### ISSUE THREAD

**Issue by DiggesT** [anymaniax/orval#782]
## What are the steps to reproduce this issue?

1. use Axios mutator
2. setup a custom instance of axios, like [this](https://orval.dev/guides/custom-axios)
3. try to generate api files

## What happens?

Incorrectly generated file using mutator.

## What were you expecting to happen?

Correctly generated files.

## Any logs, error output, etc?

Generated line with error: 
```javascript
const query = useQuery<Awaited<ReturnType<typeof getApiV1AuthWhoami>>, TError, TData>(
  { queryKey, queryFn, { staleTime: 10000, ...queryOptions
  }}) 
as  UseQueryResult<TData, TError> & { queryKey: QueryKey };
```

Previous versions generated line:
```javascript
const query = useQuery<Awaited<ReturnType<typeof getApiV1AuthWhoami>>, TError, TData>(
  queryKey, queryFn, { staleTime: 10000, ...queryOptions,
  })
as UseQueryResult<TData, TError> & { queryKey: QueryKey }
```

Redundant`{...}` added for `useQuery` parameters. (2,3 example lines)
Looks like this [commit](https://github.com/anymaniax/orval/commit/c2554a7bebf33d0ce3d706378360faa928fcd140) matters.

## Any other comments?

Happens after [6.12.0](https://github.com/anymaniax/orval/releases/tag/v6.12.0) release.

## What versions are you using?

**Operating System:** MacOS Monterey
**Package Version:** 6.12.0

**Comment by anymaniax** [comment]
Fixed will be in the next release

**Comment by anymaniax** [comment]
Hello @DiggesT, should be fixed with the last release

**Comment by DiggesT** [comment]
Hello @anymaniax, that's right, works perfectly, thank you.
