### ISSUE TITLE
difference query parameter types

### ISSUE THREAD

**Issue by path-lucas** [anymaniax/orval#795]
hi
How should we handle the difference between the actual requested parameter model type and the automated model type?

ex )
automation => { pageable: Pageable; searchType?: GetStudentsSearchType; searchKeyword?: string }
real => { page?: number;  size?: number;  sort?: string[], searchType?: string; searchKeyword?: string }

1. doc json
<img width="618" alt="image" src="https://user-images.githubusercontent.com/126146447/223383166-0f4af41d-7dd7-438c-a646-785281276b8f.png">

2. api code
<img width="618" alt="image" src="https://user-images.githubusercontent.com/126146447/223383236-57b51734-6062-4450-a25e-b0b66290ca83.png">

3. swagger ui
<img width="145" alt="image" src="https://user-images.githubusercontent.com/126146447/223383333-8fb0ec88-b57d-488e-a0f2-03505d7b2c94.png">

4. gen type
<img width="999" alt="image" src="https://user-images.githubusercontent.com/126146447/223383762-3c2872c4-0565-4736-ad99-748ccc3b6da9.png">

**Comment by path-lucas** [comment]
please answer me! save me!

**Comment by anymaniax** [comment]
Hello @path-lucas, I don't understand question. The code generated seems good.

**Comment by path-lucas** [comment]
@anymaniax 

The actual requested parameter types are: **{ page?: number; size?: number; sort?: string[], searchType?: string; searchKeyword?: string }**

Parameter types created with orval were created as paging objects. : **{ pageable: Pageable; searchType?: GetStudentsSearchType; searchKeyword?: string }**


Can't we make the type so that the paging object parameters are actually requested separately, just like the request parameters?

**Comment by anymaniax** [comment]
You need to modify the swagger that your code generate or your code description. Because as you can see the generate open api specifications as the pageable object. You can modify the doc using a [transformer](https://orval.dev/reference/configuration/input#transformer) in the orval config but I really think that something in your code need to change to generate the specification.
