### ISSUE TITLE
feature: add useSWRInfinite as additional client swr

### ISSUE THREAD

**Issue by majkl-zumberi** [anymaniax/orval#796]
it would be nice to add an additional configuration to tell to orval to generate useSWRInfinite hooks

**Comment by soartec-lab** [comment]
@melloware @anymaniax 

Hi, I would like to deal with this issue, so could you please assign it to me?

Using [`query`](https://github.com/anymaniax/orval/blob/master/packages/query/src/index.ts) as a reference, I would like to make it extensible as follows.

```
{
  output: 
    override: {
     swr: {
      useInfinite: true,
    },
  },
}
```
