### ISSUE TITLE
ResolverError not process exit code

### ISSUE THREAD

**Issue by hvasc** [anymaniax/orval#797]
## What are the steps to reproduce this issue?

1. setting up wrong target url or wrong network status
2. generate from orval
3. orval say ResolverError
```
🛑  myproject - ResolverError: Error downloading https://domain/openapi.json 
```

## What happens?

sometimes occurred network error when my CI build app with generate orval
so I add in my node script retry when catch process error
but orval say ResolverError but not return process error or exit code

## What were you expecting to happen?

when occurred Resolver error then my node script will retry generate orval

## Any logs, error output, etc?

```
🍻 Start orval v6.12.0 - A swagger client generator for typescript
🛑  myproject - ResolverError: Error downloading https://mydomain/openapi.json 
getaddrinfo ENOTFOUND mydomain
```
or socket hang up

## Any other comments?
I expected change generateSpecs function in catch code call process.exit(1) but this function is very sensitive.
So I decided to write an issue instead of pr

## What versions are you using?

**Operating System:** Ubuntu 22.04.2  LTS github action machine
**Package Version:** v6.12.0
**Browser Version:** node16

**Comment by skovhus** [comment]
There are multiple cases where proper exit codes are not used, also when a mutator path fail to resolve. 

Will you accept a PR fixing this?

**Comment by anymaniax** [comment]
@skovhus sure!

**Comment by skovhus** [comment]
Thanks! To accommodate for both CLI usage and as a code dependency, I suggest we throw custom errors all the cases in the code where something goes wrong. These errors can then be caught when using Orval through code and will result in a non 0 exit code when using the CLI. Shallowing errors makes Orval really hard to integrate with (for example on CI or through code).

**Comment by anymaniax** [comment]
Sound great!

**Comment by o-alexandrov** [comment]
@skovhus please let us know: is this change in progress?

**Comment by skovhus** [comment]
Unfortunately I never started on this. Feel free to take over. :)

**Comment by o-alexandrov** [comment]
@anymaniax could you please take a look at #898? It's a breaking change for those who relied on non-throwing behavior of orval. I believe throwing on errors should be the default and I couldn't think of a reason not to throw on errors, so I didn't add docs.
