### ISSUE TITLE
split swr logic in its own file for better compatibility with next.js ssr (/app directory)

### ISSUE THREAD

**Issue by essuraj** [anymaniax/orval#799]
Next.js app directory changes makes using the api calls imposible in server side because the api calls and useSwr are in the same file. importing it throws an error 
![image](https://user-images.githubusercontent.com/1737617/224469813-2e43a44f-b36d-48a8-909a-021c2403c98e.png)

maybe if swr logic was moved to another file, i can use the one without swr import and do a standard http call

**Comment by mverissimo** [comment]
I'm facing this problem too, so I moved the services into a new file! Maybe a new option to split the `services` into a new file solves this.

**Comment by essuraj** [comment]
i migrated to react-query with "@openapi-codegen/cli": "2.0.0",
    "@openapi-codegen/typescript": "6.1.2", so closing as im no longer tracking

**Comment by anymaniax** [comment]
Sorry for the issue. Currently there is no way to split the generated swr code to two different files. But a solution could be to combine it with another client like the axios-functions. I know it’s not ideal. If you have the time your help to find a solution would be really appreciated
