### ISSUE TITLE
guides/custom-axios doens't work

### ISSUE THREAD

**Issue by rwb196884** [anymaniax/orval#803]
The `.ts` example file at https://orval.dev/guides/custom-axios doens't work.

* `AxiosError` needs to be added to the import from `axios`,
* fuck knows what `CamelCase` is.

Futhermore the example at https://github.com/anymaniax/orval/blob/master/samples/react-app/src/api/mutator/custom-instance.ts doesn't work because it doesn't export `BodyType` which is imported by the generated code.

**Comment by melloware** [comment]
@rwb196884 can you submit a PR fixing the issues?

**Comment by vyrotek** [comment]
Seems like the BodyType problem popped up in this issue too. https://github.com/anymaniax/orval/issues/673

**Comment by janvasiljevic** [comment]
Had the same problem that the `BodyType` was being imported even if it was commented. Like it was said in the other issue, just remove the line in the custom instance where your export the body type, since it seems that Orval doesn't ignore it if it's commented out.
