### ISSUE TITLE
useApi in react-app example

### ISSUE THREAD

**Issue by rwb196884** [anymaniax/orval#804]
In 
https://github.com/anymaniax/orval/blob/master/samples/react-app/src/api/useApi.ts
is
```
import { getSwaggerPetstore } from './endpoints/petstoreFromFileSpecWithTransformer';
```
but `petstoreFromFileSpecWithTransformer.ts`
at
https://github.com/anymaniax/orval/blob/master/samples/react-app/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
contains no such method.

**Comment by melloware** [comment]
This has been switched to `import * as api from './endpoints/petstoreFromFileSpecWithTransformer';`
