### ISSUE TITLE
zod generator produces `import * as * as zod`

### ISSUE THREAD

**Issue by mgansler** [anymaniax/orval#817]
First of all thank you for adding support for zod. I played around with generating zod schemas from types but couldn't find a library that could satisfy my needs. Unfortunately there I found a small issue when I tried it out.

## What are the steps to reproduce this issue?

My orval config looks like this:

```
module.exports = defineConfig({
  api: {
    // ...
  },
  validation: {
    input: { target: 'http://127.0.01:8000/openapi.json' },
    output: {
      client: 'zod',
      target: './src/client/zod.ts',
    },
    hooks: {
      afterAllFilesWrite: ['yarn lint', 'yarn prettier --write src/client'],
    },
  },
})
```

I then just generate the clients with `orval --config orval.config.ts`.

## What happens?

The `./src/client/zod.ts` looks like this:
```
/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import * as * as zod from 'zod';
```

## What were you expecting to happen?

It should look like this:

```
/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
```

This would also work:
```
import { z as zod } from 'zod';
```

## Any other comments?

The fix should be easy, the offending line seems to be L25 in `packages/zod/src/index.ts`. 
I think it should be `name: 'zod',` instead of `name: '* as zod',` but I'm not sure if this has any other implications. I just changed it in my node_modules directory and the generated output looks like expected.

## What versions are you using?

**Operating System:** macos
**Node:** v19.6.0
**Package Version:** v6.13.1

**Comment by anymaniax** [comment]
Hello @mgansler, should be an easy fix indeed. Gonna check that asap

**Comment by anymaniax** [comment]
Hello @mgansler, just did a fix will be in the next release
