### ISSUE TITLE
Zod generator produced unnecessary consts for min and max values

### ISSUE THREAD

**Issue by sirtimbly** [anymaniax/orval#819]
## What are the steps to reproduce this issue?

Zod 6.13.1

Create a zod schema. In the OAS have a number property in a schema that specifies a minimum or maximum. Generate a zod schema client.

## What happens?

A `const` representing the value of the `min` or `max` arguments is exported and re-exported multiple times. The same variable name string can be re-generated in the same file multiple times because they are deterministic, and not guaranteed to be unique.

```ts
export const postFooServiceHeader = zod.object({
  "x-operation": zod.string().uuid()
})

export const postFooServicePurchasedAreaMin = 0;

export const postFooServiceBody = zod.object({
  "purchasedArea": zod.number().min(postFooServicePurchasedAreaMin),"cYear": zod.string(),"active": zod.boolean(),"enrollmentId": zod.string().uuid().optional(),"endDate": zod.string().datetime(),"startDate": zod.string().datetime(),"cOrgId": zod.string()
})

export const postFooServicePurchasedAreaMin = 0;export const postFooServiceTotalPriceMin = 0;

export const postFooServiceResponse = zod.object({
  "purchasedArea": zod.number().min(postFooServicePurchasedAreaMin),"active": zod.boolean(),"creatorGId": zod.string().uuid().optional(),"enrollmentId": zod.string().uuid(),"totalPrice": zod.number().min(postFooServiceTotalPriceMin),"endDate": zod.string().datetime(),"startDate": zod.string().datetime(),"connexOrgId": zod.string().optional()
})
```

The typescript error looks something like

`Cannot redeclare block-scoped variable 'postFooServicePurchasedAreaMin'.ts(2451)
const postFooServicePurchasedAreaMin: 0`

## What were you expecting to happen?
Just put scalar values directly in the function ... I don't think the consts are improving things.

## Any other comments?

I think I can submit a PR to fix this... but I'm not sure what to do about regex ... a scalar value of a number doesn't really need to be optimized, but re-creating the regex multiple times might be a real performance impact?

See https://github.com/anymaniax/orval/blob/master/packages/zod/src/index.ts#L188

## What versions are you using?

**Operating System:** MacOS
**Package Version:** 6.13.1

**Comment by anymaniax** [comment]
Hello @sirtimbly, the constants are done on purpose this case can be fixed by passing an additional key to the argument name of each execution of the function `generateZodValidationSchemaDefinition`. It's not perfect because we will probably have duplicate constants. It can be improved by generating each schema independently and not referring only to the operation.

**Comment by sirtimbly** [comment]
Maybe we can 'uniq' the whole list of consts before output?

**Comment by anymaniax** [comment]
it's also a solution but it will not solve all the problems I think at the moment doing both is the better solution. Do you want me to do it or you update your pull request?

**Comment by sirtimbly** [comment]
Feel free to update it, I'm not sure I see all the constraints like you do.

**Comment by anymaniax** [comment]
Just pushed a fix

**Comment by sirtimbly** [comment]
Confirmed-  the const names are unique now.
