### ISSUE TITLE
Add support for bigint

### ISSUE THREAD

**Issue by mkermani144** [anymaniax/orval#824]
## What happens?

When we generate code using an open api spec which contains `int64` numbers, they are converted to `number`s in the generated code.

## What were you expecting to happen?

The `int64` values should be converted to `bigint`, as js `Number.MAX_SAFE_INTEGER` cannot contain very large numbers (larger than 2^53).

Anyway, I think this should be an option, not a default.

**Comment by mkermani144** [comment]
I wonder if the main part of the fix is as simple as changing this:

https://github.com/anymaniax/orval/blob/94e2c8e4d8d07c76d249e90b6cc07c225e177ee0/packages/core/src/getters/scalar.ts#L31

to this:
```ts
let value = item.format === 'int64' ? 'bigint' : 'number';

**Comment by anymaniax** [comment]
Hello @mkermani144, indeed should be only that

**Comment by mkermani144** [comment]
@anymaniax 
Hi,
I can open a PR if you want.

**Comment by anymaniax** [comment]
@mkermani144 with pleasure!

**Comment by mkermani144** [comment]
Opened #829.

**Comment by anymaniax** [comment]
Merged @mkermani144. thanks

**Comment by RichardLindhout** [comment]
![Scherm­afbeelding 2023-04-24 om 17 08 51](https://user-images.githubusercontent.com/6492229/234038493-6972ce93-cd9e-4d24-8816-4beb1233c30f.png)
Stuff like this

**Comment by anymaniax** [comment]
sure @RichardLindhout can you do a pull request with that?

**Comment by GBDev13** [comment]
@anymaniax would that work well? https://github.com/anymaniax/orval/pull/841

**Comment by lukaw3d** [comment]
Can you add a test where https://github.com/anymaniax/orval/pull/829 works?

When targeting react-query neither bigint parameters nor bigint responses work correctly.
```yaml
paths:
  /big-param:
    get:
      parameters:
        - in: query
          name: aaa
          schema:
            type: integer
            format: int64
```
`useGetBigParam({ aaa: 5n })` throws `Uncaught TypeError: Do not know how to serialize a BigInt`

```yaml
paths:
  /big-response:
    get:
      responses:
        '200':
          description: a
          content:
            application/json:
              schema:
                type: object
                properties:
                  aaa:
                    type: integer
                    format: int64
```
`useGetBigResponse().data?.data.aaa` is typed as `bigint | undefined` but is still `number | undefined` in runtime
