### ISSUE TITLE
SWR conditional fetch

### ISSUE THREAD

**Issue by rwb196884** [anymaniax/orval#831]
Described here.
https://swr.vercel.app/docs/conditional-fetching

Can this be done in the proxy code generated by `orval`?

**Comment by anymaniax** [comment]
Hello @rwb196884, why do you need to do that? You can do it with the swrOptions enabled no?

**Comment by rwb196884** [comment]
It's really not an unreasonable thing to need to do; I've been doing it for years in perl, php, ASP.NET,...

Turns out the generated `use...` methods take an object valued parameter that can be this
```
{ swr: { enabled: api === allowKeyDates } }
```
https://github.com/anymaniax/orval/issues/830#issuecomment-1513688831

I'd never have guessed that.

**Comment by rwb196884** [comment]
Not documented at https://swr.vercel.app/docs/api

**Comment by rwb196884** [comment]
That's looking like this
```
    let { data: globalAges, error, mutate, isValidating, isLoading, swrKey } = useGenericGetAll(props.datasetId, 'GlobalAges', { swr: { enabled: api === allowKeyDates } });
    if (allowKeyDates && ((globalAges as GlobalAges[])?.length ?? 0) > 0 && !isLoading && !error) {
        let [k, d]: [boolean, Date | undefined] = apiKeyDateToDate(props.model[props.metadata.Name!], globalAges as GlobalAges[]);
        setDateValue(d);
        if (k) {
            setDateTypeName('exact date');
        }
        setLoading(isLoading);
    }
```

Am I stuck with `unknown` for the type of `data`?

That condition is rather cumbersome; is it really that difficult to check for success?

**Comment by NimmLor** [comment]
> Not documented at https://swr.vercel.app/docs/api
> 
> Nor at https://swr.vercel.app/docs/conditional-fetching

The `enabled` flag isn't an SWR feature, it's just workaround that sets the key to `null` which disables data fetching in swr. It works exactly in the same way as with [Tanstack-Query](https://tanstack.com/query/v4/docs/react/guides/disabling-queries).
This feature is seen in the `https://orval.dev/guides/swr` but could be documented a bit better. It should be clear when looking at the generated code though :)
