### ISSUE TITLE
Extend the filter option of the input to apply regular expressions.

### ISSUE THREAD

**Issue by ta1m1kam** [anymaniax/orval#834]
## What are the steps to reproduce this issue?

1. A new endpoint is added to OpenAPI yaml with new tag.
2. I have to add new tags in the filter option.

## What happens?
This [patch](https://github.com/anymaniax/orval/pull/810) gave us to limit which endpoints are actually generated.
However, I’m thinking it even more useful to be able to specify by RegExp. (For example, negative conditions such as other than specific pattern can be used.)

This eliminates the hassle of setting a new tag in the filter each time an endpoint is generated.

## What were you expecting to happen?
Allow Regex to filter OpenAPI yaml tags.

Add a regex option to filter that accepts a boolean and tags will be able to receive string[] or RegExp.
If regex option is true, tags receive RegExp
If regex option is false or undefined, tags receive string[].

Configuration look like:
```
input: {
      target: 'xxx',
      filter: {
            regex: true,
            tags: /abc/
      }
},
```

Of course, you can still use the tags filter.

```
input: {
      target: 'xxx',
      filter: {
            tags: ['tag1', 'tag2']
      }
},
```

## What versions are you using?

**Package Version:** 6.14.3

**Comment by melloware** [comment]
This has been implemented so closing
