### ISSUE TITLE
mutatoroptions not correct in https://orval.dev/reference/configuration/output#mutatoroptions

### ISSUE THREAD

**Issue by richard-infai** [anymaniax/orval#850]
## What are the steps to reproduce this issue?

Use `mutatoroptions` in output config.

## What happens?

Documentation of the homepage is not correct: https://orval.dev/reference/configuration/output#mutatoroptions
This field is called `mutationOptions` in OperationOptions from '@orval/core'

## What were you expecting to happen?

Update the document

## What versions are you using?
* "orval": "^6.11.1"
* npm

**Operating System:** …
**Package Version:** …
**Browser Version:** …

**Comment by anymaniax** [comment]
indeed it's an error can you do a pull request to fix it?
