### ISSUE TITLE
@orval/msw has deprecated and insecure dependency

### ISSUE THREAD

**Issue by IamJoseph** [anymaniax/orval#855]
## What are the steps to reproduce this issue?

Install orval

OR if already installed

Run `node -e "Object.entries(require('./package-lock.json').packages).filter(([_,x])=>x.deprecated).forEach(([pkg,{deprecated:msg}])=>{console.log(pkg + ': ' + msg + '\n')})"`

## What happens?

Notice the deprecated message `npm WARN deprecated cuid@2.1.8: cuid and other k-sortable and non-cryptographic ids (Ulid, ObjectId, KSUID, all UUIDs) are all insecure. Use @para lleldrive/cuid2 instead.`

Run `npm ls cuid`

Notice that is is coming from the `@orval/msw` package

## What were you expecting to happen?

The package should be secure and use lleldrive/cuid2 instead

## Any logs, error output, etc?

Just the deprecated warning message

## What versions are you using?

**Operating System:** MacOS
**Package Version:** orval V6.15.0

**Comment by oivindth** [comment]
Deprecated orval packages:
 
 WARN  deprecated cuid@2.1.8: Cuid and other k-sortable and non-cryptographic ids (Ulid, ObjectId, KSUID, all UUIDs) are all insecure. Use @paralleldrive/cuid2 instead.
 WARN  deprecated json-schema-ref-parser@5.1.3: Please switch to @apidevtools/json-schema-ref-parser
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

**Comment by melloware** [comment]
@Will-Mann-16 can I assign this to you too?
