### ISSUE TITLE
Make all params optional

### ISSUE THREAD

**Issue by Maxim-Mazurok** [anymaniax/orval#858]
This is realted to https://github.com/gkweb/orval/pull/2

Basically there are checks in place to `enable` query only when query parameters are not falsy, but when I try to pass something like `Ref<string | undefined>` to `useBla()` - it doesn't let me because it expects parameter to be `MaybeRef<string>`.

Here's a potential solution:

```diff
diff --git a/packages/query/src/utils.ts b/packages/query/src/utils.ts
index b5a9424..51e5e9a 100644
--- a/packages/query/src/utils.ts
+++ b/packages/query/src/utils.ts
@@ -87,7 +87,7 @@ export function vueWrapTypeWithMaybeRef(input: string): string {
     .map((param) => {
       const [paramName, paramType] = param.split(':');
       if (paramType) {
-        return `${paramName}: MaybeRef<${paramType.trim()}>,`;
+        return `${paramName}: MaybeRef<${paramType.trim()} | undefined | null>,`;
       } else {
         return `${param},`;
       }
```

I didn't want to include `null`, but since our API is in C# it's kinda hard to avoid dealing with nulls in responses, etc.

**Comment by WickyNilliams** [comment]
why make them optional? shouldn't you follow whatever the schema says? if you want them optional, you can wrap the generated composable in your own which handles this, no?

**Comment by Maxim-Mazurok** [comment]
> why make them optional? shouldn't you follow whatever the schema says? if you want them optional, you can wrap the generated composable in your own which handles this, no?

replied https://github.com/anymaniax/orval/pull/894#issuecomment-1752225205
