### ISSUE TITLE
React-query enable react-query hook when search param equals 0 

### ISSUE THREAD

**Issue by jaroslawkyc** [anymaniax/orval#860]
## What are the steps to reproduce this issue?

1. have a GET endpoint with a search param eg. `/products/1`
2. generate react-query api

## What happens?
Orval generates a part of code to get query options. The problem is that inside this function, orval does double negation to check if value is falsy.

```
export const useGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetHook>>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetHook>>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetHook>>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryKey(id);

  const get =  useGetHook();
  
    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetHook>>>> = ({ signal }) => get(id, signal);
    
      
      
   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions}}
   ```

…

## What were you expecting to happen?

I would expect orval to check if search param is nullish or empty instead of falsy. Is there any way to do that? For example let's say I have a product with id `0`. When I use generated react-query hook to fetch that, the data it isn't send because 0 is falsy. I've searched the issues and docs but I didn't find solution for my problem.

**Comment by katerinatiddy** [comment]
I have the same issue, is there an easy override for this or perhaps a change is needed to check if it is explicitly false

**Comment by melloware** [comment]
@jaroslawkyc do you have a PR or suggested fix. You mention don't do double negation but what exactly should change?

**Comment by melloware** [comment]
I believe this is happening in TanStack Query as it makes the default enabled flag the values of the params.  I would check TanStack Query if this has been fixed.
