### ISSUE TITLE
Set properties to `null` instead of `undefined` for generated types

### ISSUE THREAD

**Issue by usersina** [anymaniax/orval#862]
Not really an issue but a small inquiry and something I could not find digging through the options. Instead of having types resolved to `undefined`, I would like to have them resolved to `null` instead.

Is that doable? Thanks

**Comment by NimmLor** [comment]
I'm not sure what you mean exactly, but you can use the `required` and the `nullable` property in your definition.

Given the following example:

```json
{
  "components": {
    "schemas": {
      "Example": {
        "properties": {
          "bar": { "nullable": true, "type": "string" },
          "foo": { "nullable": true, "type": "string" },
          "quaz": { "type": "string" },
          "qux": { "type": "string" }
        },
        "required": ["bar", "qux"]
      }
    }
  }
}
```
Orval generate the following:

```tsx
export interface Example {
  bar: string | null
  foo?: string | null
  quaz?: string
  qux: string
}
```

**Comment by usersina** [comment]
That's exactly what I meant, thank you.
