### ISSUE TITLE
IfEquals Unexpected token, expected "?"

### ISSUE THREAD

**Issue by gunnartorfis** [anymaniax/orval#867]
## What are the steps to reproduce this issue?

1. Generate your client
2. When using the client with Typescript 5.x the error occurs when building

## What happens?
<img width="726" alt="Screenshot 2023-05-21 at 13 05 57" src="https://github.com/anymaniax/orval/assets/5333875/0780fe7f-8fed-460b-a082-70615ec607f8">

This pops up when building my Next.js project that uses an Orval generated client. 

## What were you expecting to happen?

There shouldn't be an error. 

## Any other comments?

I asked ChatGPT about this and here's the response

`
The error you're encountering in TypeScript 5 is related to a syntax change introduced in TypeScript 4.1. The error message suggests that the "extends" keyword is not being recognized in the position where it appears. This issue is caused by a limitation in TypeScript 4.0 and earlier versions, where conditional types (the construct with the extends keyword) could not be used in arrow function return types.
`

Furthermore, it suggests the following replacement
```ts
type IfEquals<X, Y, A = X, B = never> = [X] extends [Y] ? ([Y] extends [X] ? A : B) : B;
```

When I manually change the generated output to match that, the error disappears. I'm not a Typescript wizard myself so I'm not quite sure if this code is equivalent. If it is and you guys want me to open a PR, let me know. 

## What versions are you using?

**Operating System:** macOS Ventura 13.0
**Package Version:** 6.15.0
**Browser Version:** Not running on browser yet.

**Comment by melloware** [comment]
Interested in submitting a PR?

**Comment by melloware** [comment]
No response from OP. Closing.
