### ISSUE TITLE
6.16.0: Transforming const to the configured target environment ("es5") is not supported yet

### ISSUE THREAD

**Issue by melloware** [anymaniax/orval#872]
## What are the steps to reproduce this issue?

1. Download Orval 6.16.0
2. Run code gen with Axios Mutator
3. …

## What happens?

Error: Transforming const to the configured target environment ("es5") is not supported yet
```
Transforming const to the configured target environment ("es5") is not supported yet

    src/service/AxiosMutator.ts:5:7:
      5 │ export const useAxiosMutator = <T>(): ((config: RawAxiosRequestConfig) => Promise<T>) => {
```

## What were you expecting to happen?

It works if you revert to 6.15.0.

## Any logs, error output, etc?

See above

## Any other comments?

works with 6.15.0

## What versions are you using?

**Operating System:**  Windows 10
**Package Version:** 6.16.0

**Comment by anymaniax** [comment]
if you change your tsconfig to target es6 you shouldn't have any problem

**Comment by melloware** [comment]
Yes!  I am a dummy.  Fixed.

**Comment by patrickstubner** [comment]
That doesn't really help if I need to stay on es5.
Any fix for target es5?

**Comment by r1ft1** [comment]
I want to write a custom fetch so I can add an Auth header to my request, but I'm also on target es5, is there a workaround or a different way to add headers when using httpClient fetch?

**Comment by melloware** [comment]
@r1ft1 you should ask this question on the Discord channel.
