### ISSUE TITLE
Zod: Client unable to resolve ref in linked openapi spec file

### ISSUE THREAD

**Issue by kenny-grubb** [anymaniax/orval#874]
## What are the steps to reproduce this issue?
Generate a zod client for the attached [specs.zip](https://github.com/anymaniax/orval/files/11615912/specs.zip) organization.openapi3.json file. The models.openapi3.json file should also exist in the same folder. Here is an example orval config

```
export default defineConfig({
  organization: {
    output: {
      mode: 'single',
      target: `organization.ts`,
      schemas: `organization/model`,
      client: 'zod',
      workspace: `src/zod`,
    },
    input: {
      target: `./organization.openapi3.json`,
    },
  },
});
```

## What happens?
Orval fails to generate the client. 
organization - Oups... 🍻. Ref not found: #/components/schemas/Region

## What were you expecting to happen?
Orval should correctly resolve this schema and generate the client.

## Any logs, error output, etc?
I think it may be possible that the context in which Region is trying to be looked up is still the organization.openapi3.json file instead of switching over to the models.openapi3.json file.

was able to get a stack trace
at resolveRef (/projects/orval-master/packages/core/dist/index.js:1448:13)
    at deference (/projects/orval-master/packages/zod/dist/index.js:259:65)
    at deferenceScalar (/projects/orval-master/packages/zod/dist/index.js:251:12)
    at /projects/orval-master/packages/zod/dist/index.js:261:16
    at Array.reduce (<anonymous>)
    at deference (/projects/orval-master/packages/zod/dist/index.js:260:41)
    at deferenceScalar (/projects/orval-master/packages/zod/dist/index.js:251:12)
    at /projects/orval-master/packages/zod/dist/index.js:261:16
    at Array.reduce (<anonymous>)
    at deference (/projects/orval-master/packages/zod/dist/index.js:260:41)

## Any other comments?
This works for other clients like react-query and axios

## What versions are you using?
6.16.0

**Comment by dpnolte** [comment]
I've encountered the same issue. I noticed this happens when you add a ref under components. I've made a repro reproducing the issue using the multi-file example:
https://codesandbox.io/p/sandbox/blissful-keller-v2biyv

**Comment by kenny-grubb** [comment]
Thanks for looking into this. I tried out your fix, and I'm now  a similar error if the linked file contains a ref to a schema within itself.

**Comment by melloware** [comment]
@kenny-grubb your new issue is reported under another ticket. So closing this one
