### ISSUE TITLE
How to migrate React Query 3 to  React Query 4?

### ISSUE THREAD

**Issue by mMarcos208** [anymaniax/orval#882]
## What are the steps to reproduce this issue?

1. yarn remove react-query
2. yarn add @tanstack/react-query
3. change client in `orval.config.js` to `@tanstack/react-query`

## What happens?

Oups... 🍻. Client not found: @tanstack/react-query

## What versions are you using?

**Operating System:** ubuntu 22.04
**Package Version:**  orval: "5.4.4",

**Comment by grzennio** [comment]
Hey, went into same issue.
I think we could upgrade this lib, most of it is supported from API side.

For now i've just update imports in generated files. Works nicely.
Here is update_import.js that could be utilized 

```
const fs = require('fs');
const path = require('path');

function updateImports(dir) {
  const files = fs.readdirSync(dir);

  files.forEach(file => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);

    if (stat.isDirectory()) {
      updateImports(filePath);
    } else if (path.extname(file) === '.ts' || path.extname(file) === '.tsx') {
      let content = fs.readFileSync(filePath, 'utf8');
      content = content.replace(/from\s+['"]react-query['"]/g, "from '@tanstack/react-query'");
      fs.writeFileSync(filePath, content);
    }
  });
}

updateImports('./src/');````

**Comment by mMarcos208** [comment]
@grzennio  Where I put this code?

**Comment by lluia** [comment]
Bump on this 🙏🏽

**Comment by anymaniax** [comment]
You just keep react-query and it’s just checking you dependencies
