### ISSUE TITLE
Zod: client generates wrong RegExp

### ISSUE THREAD

**Issue by irrvrsl** [anymaniax/orval#889]
## What are the steps to reproduce this issue?

1. Have `pattern` property in your OpenAPI's Schema, e.g. `"^\\+\\d{10, 15}"` (took from schema.json, pattern for `phone_number` property)
2. Generate Schema

## What happens?
Output will have RegExp string without special character escapes `"^+d{10, 15}"`

## What were you expecting to happen?
Output should have valid RegExp string  `"^\+\d{10, 15}"`

## Any logs, error output, etc?
N/A

## Any other comments?
Currently I just omit this property with `transformer` function

## What versions are you using?

**Operating System:** MacOS Ventura 13.4
**Package Version:** 6.16.0
**Browser Version:** Firefox 114.0.2

**Comment by melloware** [comment]
I just wrote this test which is what the Zod generator is doing and it looks correct?

```js
describe('string testing', () => {
  it('cleanse JS String', () => {
    expect(new RegExp(jsStringEscape('^\\+\\d{10, 15}'))).toEqual(
      /^\\+\\d{10, 15}/,
    );
  });
});
```

**Comment by melloware** [comment]
@irrvrsl according to OpenAPI your regex is incorrect.

https://swagger.io/docs/specification/data-models/data-types/

The pattern should be in JS format already like...

```js
pattern: '^^\+\d{10, 15}'
```
