### ISSUE TITLE
Output title override not working

### ISSUE THREAD

**Issue by christian-draeger** [anymaniax/orval#897]
I want to add a Suffix to generated models and hooks titles.

This is important since barrel files exports would have name clash when i generating from multiple specs that include models or operations with the same name.

### see reproducer project to showcase exactly: https://github.com/christian-draeger/orval-name-override-example

1. create orval config with >= 2 api specs
2. try to suffix output titles as [described in the orval docs ](https://orval.dev/reference/configuration/output#title)
3. generate

## What happens?

Generated output titles are not suffixed or changed. Looks like title config will be ignored by orval

## What were you expecting to happen?

Generated output titles should be suffixed as described in the orval config.

**Comment by christian-draeger** [comment]
but still beeing curious if this is the way to go to avoid name clashes between operations and schemas of different specs that would result in the same name

**Comment by anymaniax** [comment]
Hello @christian-draeger, operationName is the way to go to modify the operationId and the suffix is for your schemas. If you want you can also use a transformer in the input config. To have access to your specification directly and modify it

**Comment by anymaniax** [comment]
If you use the axios client or angular it’s override the class name or the name of the object containing all the endpoints. It’s the title of your specification in fact
