### ISSUE TITLE
How to use orval with React Query 5

### ISSUE THREAD

**Issue by mrxsal** [anymaniax/orval#899]
I know React Query 5 is in Alpha, but i was hoping I could still use Orval.

## What are the steps to reproduce this issue?

1. Install [react-query v5.0.0-alpha.86](https://github.com/TanStack/query/releases/tag/v5.0.0-alpha.86)

## What happens?
after `orval --config ./orval.config.js` and the file is generated, the following part gives an error:
```
  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };
```
queryOptions can't be passed ot useQuery like this anymore.
…

## What were you expecting to happen?
It is expected behavior at the moment

…

## Any logs, error output, etc?

The [docs ](https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5#supports-a-single-signature-one-object)show the following change:
```
- useQuery(key, fn, options)
+ useQuery({ queryKey, queryFn, ...options })
```
…

## Any other comments?

Is there a way I can adjust the config to pass the options correctly?

…

**Comment by anymaniax** [comment]
Hi, queryOptions is in the good format already normally. So it’s the type that isn’t good?

**Comment by mrxsal** [comment]
@anymaniax Yes, it seems to be a typing issue. Sorry I am still relatively new to Typescript and i was having trouble understanding the error.

Here's an example of the generated code:

```
const queryOptions = getSpacesListQueryOptions(params, options);
const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
  queryKey: QueryKey;
};
```

When I try to compile this code, I get the following TypeScript error:

```
No overload matches this call.
  Overload 1 of 2, '(options: UndefinedInitialDataOptions<AxiosResponse<SpacesList200, unknown>, TError, TData, QueryKey>, queryClient?: QueryClient | undefined): UseQueryResult<...>', gave the following error.
    Argument of type 'UseQueryOptions<AxiosResponse<SpacesList200, unknown>, TError, TData, QueryKey> & { queryKey: QueryKey; }' is not assignable to parameter of type 'UndefinedInitialDataOptions<AxiosResponse<SpacesList200, unknown>, TError, TData, QueryKey>'.
      Type 'UseQueryOptions<AxiosResponse<SpacesList200, unknown>, TError, TData, QueryKey> & { queryKey: QueryKey; }' is not assignable to type '{ initialData?: undefined; }'.
        Types of property 'initialData' are incompatible.
          Type 'AxiosResponse<SpacesList200, unknown> | InitialDataFunction<AxiosResponse<SpacesList200, unknown>> | undefined' is not assignable to type 'undefined'.
            Type 'AxiosResponse<SpacesList200, unknown>' is not assignable to type 'undefined'.
  Overload 2 of 2, '(options: DefinedInitialDataOptions<AxiosResponse<SpacesList200, unknown>, TError, TData, QueryKey>, queryClient?: QueryClient | undefined): DefinedUseQueryResult<...>', gave the following error.
    Argument of type 'UseQueryOptions<AxiosResponse<SpacesList200, unknown>, TError, TData, QueryKey> & { queryKey: QueryKey; }' is not assignable to parameter of type 'DefinedInitialDataOptions<AxiosResponse<SpacesList200, unknown>, TError, TData, QueryKey>'.
      Type 'UseQueryOptions<AxiosResponse<SpacesList200, unknown>, TError, TData, QueryKey> & { queryKey: QueryKey; }' is not assignable to type '{ initialData: AxiosResponse<SpacesList200, unknown> | (() => AxiosResponse<SpacesList200, unknown>); }'.
        Types of property 'initialData' are incompatible.
          Type 'AxiosResponse<SpacesList200, unknown> | InitialDataFunction<AxiosResponse<SpacesList200, unknown>> | undefined' is not assignable to type 'AxiosResponse<SpacesList200, unknown> | (() => AxiosResponse<SpacesList200, unknown>)'.
            Type 'undefined' is not assignable to type 'AxiosResponse<SpacesList200, unknown> | (() => AxiosResponse<SpacesList200, unknown>)'.
```

The error seems to be related to the `initialData` field in the `queryOptions` object. The type of initialData in queryOptions is `AxiosResponse<SpacesList200, unknown> | InitialDataFunction<AxiosResponse<SpacesList200, unknown>> | undefined`, but react-query v5 expects either `undefined` or `AxiosResponse<SpacesList200, unknown> | (() => AxiosResponse<SpacesList200, unknown>)`.

**Comment by shahbazshueb** [comment]
I am also facing the same issue. Any resolutions for this issue?

**Comment by mrxsal** [comment]
@shahbazshueb, As @anymaniax mentioned, queryOptions is already in the right format, it's just a typing issue. Although it's bad practice, for now I ended up adding `// @ts-nocheck` to the top of my generated file to avoid the errors. The functions/hooks themselves are working fine.

**Comment by melloware** [comment]
I still think we should try and fix this correctly and not need ts-ignore

**Comment by melloware** [comment]
Can one of you try 6.19.1 which has a queryKey fix in it?

**Comment by maapteh** [comment]
@melloware  please reopen

using version 6.23.0 and React-Query  5.17.1

I get the following error `Property 'queryKey' is missing`

**Comment by ruiaraujo012** [comment]
> @melloware please reopen
> 
> using version 6.23.0 and React-Query 5.17.1
> 
> I get the following error `Property 'queryKey' is missing`

Same here

**Comment by melloware** [comment]
Hmmm here are the fixes between Orval 6.22.1 and 6.23.0 and its not much?  https://github.com/anymaniax/orval/issues?q=is%3Aclosed+milestone%3A6.23.0

**Comment by maapteh** [comment]
As far as i understand Orval adds the `UseQueryResult<TData, TError> & { queryKey: QueryKey } => {` to the useQuery  which makes the queryKey suddenly required when you do:

```
useSnip({
    query: {
      retry: 0,
      gcTime: 0,
    },
  })
  ```

**Comment by maapteh** [comment]
Thanks both, so this was locally on our end in the end. Rui got it working, our setup takes little more time. But ticket can stay closed!

**Comment by soartec-lab** [comment]
The discussion on this issue ends with [this](https://github.com/anymaniax/orval/issues/975#issuecomment-1877993764), so I'll mark it.

**Comment by dinakar17** [comment]
> @maapteh I've just downgraded from the latest to the 6.22.1, `pnpm add -D oval@6.22.1` and run de generate again and it worked. I'm using the react query `"@tanstack/react-query": "^5.17.0"`
> 
> <img alt="image" width="917" src="https://private-user-images.githubusercontent.com/16304685/294300181-5fb3ee7f-edc7-48f2-b4cd-9d045d4c51c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTk0NTAsIm5iZiI6MTcxNjkxOTE1MCwicGF0aCI6Ii8xNjMwNDY4NS8yOTQzMDAxODEtNWZiM2VlN2YtZWRjNy00OGYyLWI0Y2QtOWQwNDVkNGM1MWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDE3NTkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YTA4MzViYjBmOGJkNWVlNjY2YzY0MTRlNWFjNGNkNGM5ZjUyZjcyOWU1NTQzZGI0YWE2Yjc3MjZjZGNmYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s1_s6v6zIEZzEQG9gZTChpZwFjc66VGj1oIkvGD6PII">

How did you do the generation using @tanstack/react-query library. I got the following error when I tried to generate the code.

Oups... 🍻. Client not found: @tanstack/react-query

This is my config file for orval
![image](https://github.com/anymaniax/orval/assets/85105044/b103a318-fd0a-4b44-a05b-d7b3f900a5b2)

**Comment by maapteh** [comment]
See, https://github.com/anymaniax/orval/blob/master/samples/react-query/basic/orval.config.ts#L10 use 'react-query'
The package `@tanstack/react-query` is the npm dependency which your app will need :)

**Comment by dinakar17** [comment]
Finally, I understood. I've been googling for a while (probably more than a couple of hours). Thank you very much for saving time and answering it quickly. Really appreciate it.

**Comment by agamm** [comment]
I'm still getiing an error:

Versions:
```
    "orval": "^6.31.0",
    "typescript": "^5.5.3"
    "@tanstack/react-query": "^5.51.9",
```

```
 ⨯ TypeError: (0 , _tanstack_react_query__WEBPACK_IMPORTED_MODULE_2__.useQuery) is not a function
    at useDashboardDashboardGet (./src/apischema.ts:191:82)
    at Home (./src/app/page.tsx:11:108)
    at stringify (<anonymous>)
digest: "2998683142"
  450 |   const queryOptions = getDashboardDashboardGetQueryOptions(options);
  451 |
> 452 |   const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
      |                          ^
  453 |     queryKey: QueryKey;
  454 |   };
  455 |
  ```

**Comment by melloware** [comment]
It works fine for me.  See my package.json: https://github.com/melloware/quarkus-primereact/blob/main/src/main/webui/package.json

see the whole app here: https://github.com/melloware/quarkus-primereact

If you want to run the whole app go here and run `mvn quarkus:dev` if you are a Java person.

**Comment by agamm** [comment]
@melloware It happens to me when I use react-query from the server (without "use client" on next) is this the reason?

**Comment by melloware** [comment]
@agamm yes SSR is a complex beast and tanStack has an entire guide on SSR: https://tanstack.com/query/v5/docs/framework/react/guides/ssr

I know other Orval users are using SSR just fine.
