### ISSUE TITLE
Generate enum instead of type + const

### ISSUE THREAD

**Issue by Sergey-Ubogov** [anymaniax/orval#907]
## What are the steps to reproduce this issue?

Why are type + const generated instead of enum?
```
    MyEnum:
      type: string
      enum:
        - testA
        - testB
        - testC
```

## What happens?
generating
```ts
export type MyEnum = typeof MyEnum[keyof typeof MyEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MyEnum = {
    testA: 'testA',
    testB: 'testB',
    testC: 'testC',
} as const;
```

## What were you expecting to happen?
generating
```ts
export enum MyEnum {
    testA = 'testA',
    testB = 'testB',
    testC = 'testC',
}
```

## Any other comments?
typescript supports enums https://www.typescriptlang.org/docs/handbook/enums.html
I do not understand why it is impossible to generate it?

why do I need this:
```ts
export type MyEnum = typeof MyEnum[keyof typeof MyEnum];
export const MyEnum = {
    testA: 'testA',
    testB: 'testB',
    testC: 'testC',
} as const;

const a = MyEnum.testA;
const arr = [MyEnum.testB, MyEnum.testC];
arr.includes(a); // TS2345: Argument of type '"testA"' is not assignable to parameter of type '"testB" | "testC"'. 
```
how to fix:
1.
```ts
...
const arr: MyEnum[] = [MyEnum.testB, MyEnum.testC];
arr.includes(a); // ok, but I don't want to put down the types manually
```
2. (best way with enums!)
```ts
export enum MyEnum {
    testA = 'testA',
    testB = 'testB',
    testC = 'testC',
}

const a = MyEnum.testA;
const arr = [MyEnum.testB, MyEnum.testC];
arr.includes(a); // ok! I don't need to put array types manually!
```

## What versions are you using?
6.13.1
**Operating System:** macOs ventura 13.4.1
**typescript version:** 4.7.4
**Package Version:** …
**Browser Version:** …

**Comment by Wtiben** [comment]
https://blog.graphqleditor.com/enums-are-still-bad

**Comment by Sergey-Ubogov** [comment]
@Wtiben, the article is misleading, because it says:
`Essentially we're getting everything we would from an enum, without the drawbacks of actually using an enum.`
and
`key issue of ‘why not just use a const’ will remain for those who find them entirely redundant`.

I gave the answer to their question above, but I'll duplicate it here for you. With a constant, you will get a non-working code:
```ts
export type MyEnum = typeof MyEnum[keyof typeof MyEnum];
export const MyEnum = {
    testA: 'testA',
    testB: 'testB',
    testC: 'testC',
} as const;

const a = MyEnum.testA;
const arr = [MyEnum.testB, MyEnum.testC];
arr.includes(a); // TS2345: Argument of type '"testA"' is not assignable to parameter of type '"testB" | "testC"'. 
```
At the same time, with enum you will get a working and more concise code:
```ts
export enum MyEnum {
    testA = 'testA',
    testB = 'testB',
    testC = 'testC',
}

const a = MyEnum.testA;
const arr = [MyEnum.testB, MyEnum.testC];
arr.includes(a);
```

Besides, I don't insist on generating enum by default. this can be done by some flag in the config

**Comment by dsthode** [comment]
Hey, I've taken up the gauntlet and contributed [my first PR](https://github.com/anymaniax/orval/pull/1058) to the project with an optional configuration parameter to generate native Typescript enums and the code to handle it.

**Comment by melloware** [comment]
@dsthode sent you 1 review comment

**Comment by dsthode** [comment]
@melloware thank you for the comment, I've performed the changes requested.
