### ISSUE TITLE
Numeric models imported without N prefix

### ISSUE THREAD

**Issue by rjmackay** [anymaniax/orval#911]
## What are the steps to reproduce this issue?

1. Add a response schema at #/components/responses/200
2. Reference that in an operation
3. Generate a client

## What happens?

The response schema is generated with the name `N200Response` but it's imported in the output as just `200Response`

## What were you expecting to happen?

The type should be imported as `N200Response`

## What versions are you using?

**Package Version:** 6.17.0

**Comment by melloware** [comment]
Duplicate of #1055
