### ISSUE TITLE
Nullable enums break strict mode tsc checks. 

### ISSUE THREAD

**Issue by lenwhite** [anymaniax/orval#913]
## What are the steps to reproduce this issue?

Have a swagger file with a nullable enum, e.g.

```
"choices": {
  "enum": [1, 2, 3],
  "type": "integer",
  "nullable": true,
```

## What happens?

The following code is generated:

```
export const Choices = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  null: null,
} as const;
```

With the `--noImplicitAny` or strict mode on, `tsc` complains with the following error, as it is unable to infer the type for `null` for some reason. 

```
error TS7018: Object literal's property 'null' implicitly has an 'any' type.
```

## What were you expecting to happen?

One way to sidestep this would be to type it explicitly, if a bit redundantly:

```
export const Choices: {
  NUMBER_1: 1;
  NUMBER_2: 2;
  NUMBER_3: 3;
  null: null;
} = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  null: null,
} as const;
```

Alternatively, leaving out `null` as an option of the object and having it as part of the type declaration instead

```
export const Choices = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;

... 

export type Choices = typeof Choices[keyof typeof Choices] | null;
```
## Any other comments?

I could take a stab at contributing a fix.

**Comment by melloware** [comment]
Also reported here: https://github.com/anymaniax/orval/issues/981  if you two want to collaborate on a fix.
