### ISSUE TITLE
Parse Error: Invalid header value char

### ISSUE THREAD

**Issue by MickaelAustoni** [anymaniax/orval#926]
Hello,

when i try to use `url` input target : 

```
input: {
    target: "https://{MY_DOMAIN}/openapi.json",
},
```

i got a error : 

> Parse Error: Invalid header value char

but when i download the json file and set local path target :

```
 input: "./openapi.json",
```

it's work !!

I have try to disable parser validation : 

```
input: {
  parserOptions: {
    validate: false,
  },
  target: "https://{MY_DOMAIN}/openapi.json",
},
```

but i got a other error : 

> api - Error: ENOENT: no such file or directory, open "https://{MY_DOMAIN}/openapi.json"

## What versions are you using?

**Operating System:** : MacOs
**Package Version:** : 6.17.0
**Browser Version:** Chrome  116.0.5845.140

**Comment by melloware** [comment]
What is {MY_DOMAIN} where is it declared?   Doesn't this need to be a real URL?

**Comment by MickaelAustoni** [comment]
> What is {MY_DOMAIN} where is it declared? Doesn't this need to be a real URL?
MY_DOMAIN is just for the example !

**Comment by melloware** [comment]
Yep I fixed it for next release.

**Comment by MickaelAustoni** [comment]
@melloware Very nice 💪
