### ISSUE TITLE
Invalid generated typings for a case w/ multiple objects w/ different schemas

### ISSUE THREAD

**Issue by o-alexandrov** [anymaniax/orval#935]
## What are the steps to reproduce this issue?

1. Document API endpoint's `responses` to:
```ts
schema: {
  oneOf: [
    {
      type: 'object',
      properties: { message: { type: 'string' } },
    },
    {
      type: 'object',
      properties: {
        message: { type: 'string' },
        provider: { type: 'string' },
      },
    },
  ],
},
```
2. Observe generated by `orval` typings:
```ts
export type Status200OneOfTwo = {
  message?: string;
  provider?: string;
};

export type Status200OneOf = {
  message?: string;
};

export type Status200 = Status200OneOf | Status200OneOfTwo
```

3. Observe the typings error (bad DX) when using the generated type:
```ts
const a = {} as Status200
// next line triggers a typings error
if (a.provider) {} // property 'provider' does not exist on type 'Status200'
```

## What happens?

Typings errors (see step 3 in how to reproduce above)

## What were you expecting to happen?

No typings errors

## Any other comments?

To fix this DX issue, `orval` should generate:
```ts
import * as TF from 'type-fest'

export type Status200 = TF.MergeExclusive<Status200OneOf, Status200OneOfTwo>
```

If there are more than 2 schemas in `oneOf/anyOf`, `orval` should:
- continue to wrap items in MergeExclusive (related issue https://github.com/sindresorhus/type-fest/issues/366)

```ts
import * as TF from 'type-fest'

export type Status200 = TF.MergeExclusive<TF.MergeExclusive<A, C>, TF.MergeExclusive<B, D>>
```

## What versions are you using?

**Package Version:** `6.17.0`

**Comment by melloware** [comment]
PR is welcome

**Comment by o-alexandrov** [comment]
Unfortunately, I don't have time yet to fix this in the `orval`'s generated typings.
However, I realized this could be solved simply:
- by generating `provider?: never` to `Status200OneOf` object in the example above

@melloware please let the community know, if such solution would be accepted in a PR

**Comment by melloware** [comment]
Sounds good to me and reasonable if you want to submit it.  I also like it doesn't introduce another library!
