### ISSUE TITLE
Dependencies deprecated

### ISSUE THREAD

**Issue by James-Lam** [anymaniax/orval#939]
## What are the steps to reproduce this issue?
run `npm install`

## What happens?
There are warnings that the dependencies are deprecated.

## What were you expecting to happen?
No `npm WARN deprecated`

## Any logs, error output, etc?

npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated cuid@2.1.8: Cuid and other k-sortable and non-cryptographic ids (Ulid, ObjectId, KSUID, all UUIDs) are all insecure. Use @paralleldrive/cuid2 instead.
npm WARN deprecated json-schema-ref-parser@5.1.3: Please switch to @apidevtools/json-schema-ref-parser
<img width="667" alt="image" src="https://github.com/anymaniax/orval/assets/15834794/b97bc454-4b0f-45cf-a9ad-4f42635d7db6">

```bash
❯ npm ls sourcemap-codec                                                     
└─┬ orval@6.17.0
  └─┬ @orval/core@6.17.0
    └─┬ ibm-openapi-validator@0.97.5
      └─┬ @stoplight/spectral-cli@6.10.1
        └─┬ @stoplight/spectral-ruleset-bundler@1.5.2
          └─┬ @rollup/plugin-commonjs@22.0.2
            └─┬ magic-string@0.25.9
              └── sourcemap-codec@1.4.8
```
```bash
❯ npm ls cuid               
└─┬ orval@6.17.0
  └─┬ @orval/msw@6.17.0
    └── cuid@2.1.8
```
```bash
❯ npm ls json-schema-ref-parser    
└─┬ orval@6.17.0
  └─┬ @orval/core@6.17.0
    └─┬ ibm-openapi-validator@0.97.5
      └── json-schema-ref-parser@5.1.3
```
## Any other comments?
`ibm-openapi-validator` has been outdated, please update.
Repo: https://github.com/IBM/openapi-validator

## What versions are you using?

**Operating System:** Mac OS Ventura 13.5.2
**Package Version:** orval@6.17.0

**Comment by melloware** [comment]
I opened this issue: https://github.com/IBM/openapi-validator/issues/640
