### ISSUE TITLE
Need for better performance

### ISSUE THREAD

**Issue by EwenQuim** [anymaniax/orval#948]
**Operating System:** Team using latest MacOS, Linux & WSL
**Package Version:** 6.15

Thank you for this project, it saves a lot of time and it's wonderful to have the frontend in sync with the backend!

But the generation takes usually ~45s, it would be very nice to speed this a little bit  🚀  Maybe by looking at a profiler ? We could identify bottlenecks and optimize this.

I'm willing to contribute, but I noticed you do not have any `CONTRIBUTING.md`, where can I look at ? How to set up the project locally ?

**Comment by EwenQuim** [comment]
I investigated a little, here is what I have found:
The main loading time is composed of `importSpecs`and `writeSpecs`, being 70% / 30% of time
- `await importSpecs` in `generate.ts` take 28 seconds
  - `generateVerbsOptions` is especially slow - depends linearly on the number of endpoints
  - `getScalar` is called 47k times - my project only have a 40k openAPI file : maybe a loop somewhere ? Too many calls ?
- `await writeSpecs` in `generate.ts` takes 13 seconds

I may updated this investigation in the future.

**Comment by codebutler** [comment]
I have observed that a lot of time is spent doing string operations:

![image](https://github.com/anymaniax/orval/assets/3827/44961e71-718c-4220-ba33-a7733f8bfd6e)

**Comment by EwenQuim** [comment]
Yeah I noticed too that the Pascal function is a bottleneck. I have an idea for a patch.

Please, how did you get this profiling ? How did you manage to make Orval work in a browser ? I use it through Node only.

**Comment by anymaniax** [comment]
I am interested too 😅

**Comment by EwenQuim** [comment]
1. Another bottleneck happen in ref resolving. Definitely checking these this week.

<img width="304" alt="image" src="https://github.com/anymaniax/orval/assets/46993939/ad25bb51-f775-4e68-80ec-ff985039bb59">

---

2. Replacing `pascal` by `(s) => return s` just made the generation 28x faster lol.

Replacing it with the code below (more accurate) made generation 2x faster. @anymaniax is it just a normal PascalCase function, or did you have something more specific in mind ? Is there any test cases so I can work on an implementation against some tests, to make sure I do not introduce any regression ? I didn't find any.
If not, no problem, I will make some and come back with a pull request.

```js
s.replace(
    /\w+/g,
    (w) => w[0].toUpperCase() + w.slice(1).toLowerCase(),
  )
```

Thank you very much @codebutler and @anymaniax, we're gonna make it to the moon 🚀

**Comment by anymaniax** [comment]
The pascal case function was coming from another library if I remember well. If working it’s good for me. And not we don’t have any test case for that

**Comment by codebutler** [comment]
1. From within your project dir run:
   ```
   node --cpu-prof ./node_modules/orval/dist/bin/orval.js
   ```
     This will create a `.cpuprofile` file in the current directory.

2. Open a chrome tab to anywhere (`about:blank`) and open the dev inspector (Cmd+Option+I)
3. Select the Performance tab, then drag & drop the profile file into the panel.

**Comment by codebutler** [comment]
I spent a little time trying to replace the pascal function. Note that the handling of strings like "API" is different than a naïve solution:

```ts
import _ from "lodash"
import { pascal } from "@orval/core";

const pascal2 = _.flow(_.camelCase, _.upperFirst);

console.log(pascal("foo_bar_API")) # FooBarAPI
console.log(pascal2("foo_bar_API")) # FooBarApi
``` 

Unit tests are a good idea before changing the implementation.
