### ISSUE TITLE
Zod: Query Params Validator is unusable with URLSearchParams for booleans/numbers

### ISSUE THREAD

**Issue by solomonhawk** [anymaniax/orval#961]
The issue is that query string values are only ever represented as `string`s within `URLSearchParams`, so they can never be parsed effectively by a `zod` schema like `z.boolean()` or `z.number()` (they _can_ be parsed by `z.coerce.boolean()` or `z.coerce.number()`).

## What are the steps to reproduce this issue?

1. Generate a some zod schema based on a swagger file with an endpoint that has `parameters` that include a boolean field named `active`
2. Construct a `URLSearchParams` from a query string like `?active=true`, `?active=1`, `?active`
3. Try to parse this with the generated zod schema `generatedZodSchemaFn.parse(Object.fromEntries(new URLSearchParams('?active=true')))`

## What happens?

The schema will throw an error, because `active` will be `"true"`, `"1"`, or `""` (respective to the examples listed above), which are strings and not booleans.

## What were you expecting to happen?

If I were to write this zod schema myself, expecting to use it to parse query params, I would use `z.coerce.boolean()` (for the simple case) or `z.transform(..).boolean()` if I needed more flexibility in interpreting a parameter as a boolean value.

## Any logs, error output, etc?

Just the typical zod parse error for "expected boolean".

## Any other comments?

Casting data is difficult to get right in the general case. I was hoping there might be a way for me to customize this via the config but I didn't find anything. It _could_ be sensible to use the `z.coerce` variants specifically for the `XQueryParams` schemas.

## What versions are you using?

**Operating System:** Mac/OSX 12.4
**Package Version:** `orval` 6.18.1, `zod` 3.22.4
**Browser Version:** Chrome Version 117.0.5938.149 (Official Build) (arm64)

**Comment by melloware** [comment]
PR is welcome!

**Comment by solomonhawk** [comment]
Added in #1045. Not 100% convinced this is the correct path forward, but it is _a_ path and hopefully fosters some fruitful discussion on the subject.
