### ISSUE TITLE
Hangs at 100% CPU usage while generating client code

### ISSUE THREAD

**Issue by thhermansen** [anymaniax/orval#967]
## What are the steps to reproduce this issue?

1. Download schema from https://tripletex.no/v2/swagger.json
2. Try to run: `orval --input tripletex-schema.json --output src/client.ts`

## What happens?

Nothing happens, other than:

<img width="965" alt="image" src="https://github.com/anymaniax/orval/assets/92300/eba689c0-9757-4fb8-9413-bc0a721e8b99">

Seems to go on indefinitely. 

## What were you expecting to happen?

To get some generated code :-)

## Any logs, error output, etc?

No, but can I get some debug logging turned on somehow? :)

## What versions are you using?

**Operating System:** MacOS 14.0
**Package Version:** 6.18.1
**Node version:** v20.5.1

**Comment by melloware** [comment]
Can you try 6.19.0 please?

**Comment by thhermansen** [comment]
I tried, same symptom :-(

Does it work for you?

**Comment by melloware** [comment]
OK thanks for reporting back.  I will try and test it later this week.

**Comment by thhermansen** [comment]
Thank you. Don't sweat too much, as we are testing https://openapi-ts.pages.dev/ too now. It seems to be able to consume the swagger json (after running it through https://github.com/Mermade/oas-kit/blob/main/packages/swagger2openapi/README.md), so it is an alternative for us.

**Comment by melloware** [comment]
Confirmed it hangs for me too.

**Comment by melloware** [comment]
I think this is the same as #868

**Comment by jamalsoueidan** [comment]
It hangs to me also if I have the file open, or if I do it from visual code, but I do it from the console, and close vscode before generating the file.

**Comment by YukiKitagata** [comment]
There was no improvement on the schema file attached to this PR, but I have submitted a PR #1083 that fixes one of the causes of this problem.

I was also reproducing the freezing problem with my schema file, which now works with the fixes in this PR #1083.
