### ISSUE TITLE
TanStack Query v5

### ISSUE THREAD

**Issue by melloware** [anymaniax/orval#970]
Has anyone tried TanStack Query v5 yet?

they have a migration guide here: https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5

was just wondering if Orval will need to make any changes?

**Comment by codebutler** [comment]
Support for suspense was moved into its own hook, so without changes to orval there will be no way to continue using that.

We could consider the approach taken by this compiler which returns a query options object that can be used with either hook: https://github.com/connectrpc/connect-query-es#quickstart

**Comment by melloware** [comment]
I am open to anything supporting v5 as I love Orval and love Tanstack.

**Comment by anymaniax** [comment]
I did some preparation for the v5 not long ago. We just need to add the new suspense hook and we should be good form what I know

**Comment by anymaniax** [comment]
Also since we expose a function to get the query options you can already use the suspense hook like that too

**Comment by anymaniax** [comment]
@codebutler @melloware are you on discord? if yes could you ping me there?

**Comment by melloware** [comment]
Yep I will ping you

**Comment by anymaniax** [comment]
Support for suspense hooks will be in the next release

**Comment by leniency** [comment]
I just tried and ran into a typescript issue. It looks like `queryKey` is now required so calling the generated use hooks with additional query options raises typescript errors:

```
const { data } = useGetMyQuery({
        query: {
            // Raises a typescript error here that the queryKey is required, but it's being set
            // in the generated code. This creates an annoyance here if all we want to do
            // is just set some other option and don't want to re-declare the query key.
        }
    });
```

In the generated endpoint, this can be solved by wrapping the options.query type in a `Partial<>` in the endpoint hook and the options function:

```
export const useGetMyQuery= <TData = Awaited<ReturnType<typeof getMyQuery>>, TError = ErrorType<void>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyQuery>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  ...
}
```

**Comment by melloware** [comment]
Can you offer a PR to fix it?

**Comment by leniency** [comment]
Yeah, I think I have some time cleared up here so will send one in.

**Comment by hasanaktas** [comment]
Is there any progress on this issue?

**Comment by melloware** [comment]
@hasanaktas I believe Orval 6.19.1 you can use Tanstack v5 with . Please test and let us know.

**Comment by hasanaktas** [comment]
@melloware  
In our tests, we did not see any problems in general with the requests made on the client side.

The issue here needs to be resolved for more testing because we have a lot of requests submitted on the ssr side.

https://github.com/anymaniax/orval/issues/985
