### ISSUE TITLE
Zod: generate wrong validation for type string format date

### ISSUE THREAD

**Issue by mortezakarimi** [anymaniax/orval#971]
## What are the steps to reproduce this issue?

1. Create a body field with type `string` and format `date`
2. generate schema using zod client with `useDates: true` override
3. validation will be `zod.string().regex(new RegExp(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/))`

## What happens?

Wrong validation for zod client `zod.string().regex(new RegExp(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/))`

## What were you expecting to happen?

Validation should be `zod.date()`

## Any logs, error output, etc?
-

## Any other comments?

-

## What versions are you using?

**Operating System:** Ubuntu 22.04
**Package Version:** 6.18.1
**Browser Version:** Google Chrome Version 118.0.5993.70 (Official Build) (64-bit)

**Comment by melloware** [comment]
A PR is welcome since you seem to know the fix?

**Comment by mortezakarimi** [comment]
Yes, I try in the next week and send PR
