### ISSUE TITLE
Refs are not handled in schema properties

### ISSUE THREAD

**Issue by bnussman** [anymaniax/orval#973]
## What are the steps to reproduce this issue?

- Run the command
```sh
yarn orval --input https://raw.githubusercontent.com/linode/linode-api-docs/development/openapi.yaml --output ./generated/linode.ts
```
- Observe Typescript type-checking errors in the generated types

## Spec that is causing issues

```yaml
      requestBody:
        description: Updated information for the Managed MySQL Database.
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Updated information for the Managed MySQL Database.
              properties:
                label:
                  $ref: '#/components/schemas/DatabaseMySQLRequest/properties/label'
                allow_list:
                  $ref: '#/components/schemas/DatabaseMySQLRequest/properties/allow_list'
                updates:
                  $ref: '#/components/schemas/DatabaseMySQL/properties/updates'
```

## What happens?

Typescript types are used but the interface for them does not exist

![Screenshot from 2023-10-19 23-46-56](https://github.com/anymaniax/orval/assets/6440455/3028d956-eb40-4dc7-a25e-35d0bbc35c41)

## What were you expecting to happen?

This package should recursively resolve refs used in schema properties

![Screenshot from 2023-10-19 23-48-30](https://github.com/anymaniax/orval/assets/6440455/4fc66e4c-4f7b-4354-8f2c-bdfb301eb251)

## Any logs, error output, etc?

No errors occour

## Any other comments?

I'm very unfamiliar with this codebase but it looks like references are not being handled here:

https://github.com/anymaniax/orval/blob/8f1682ce72d721d8992b4c613513191b31029c7c/packages/core/src/getters/object.ts#L60-L77

## What versions are you using?

**Operating System:** Pop_OS!
**Package Version:** 6.19.0
**Browser Version:** Chrome

**Comment by bnussman** [comment]
This may be a duplicate of https://github.com/anymaniax/orval/issues/811

**Comment by melloware** [comment]
Definitely looks like a duplicate to me
